### ISSUE TITLE
Conditional expression evaluated incorrectly by the NB

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#10000]
Please check `ScalableTestSuite.Thermal.HeatExchanger.ScaledExperiments.CocurrentHeatExchangerEquations_N_10`, variable `TA[1]`, which is governed by the following equation
```modelica
  TA[1] = if time < 8 then 300 else 301;
```

With the old backend, it has this behaviour:
![immagine](https://user-images.githubusercontent.com/4233148/210461020-57c6b34d-7e47-491b-bddb-6952225ae4f4.png)

With the new backend, it has this behaviour:
![immagine](https://user-images.githubusercontent.com/4233148/210461141-5498fa65-7abc-4ed0-813e-a9c2a5af1459.png)

Apparently, there is something going wrong with the conditional expression in the NB.

**Comment by kabdelhak** [comment]
I fixed this issue on a minimal model in  #10009, but this model fails with a different message for me:

```
stdout            | warning | division by zero in partial equation: areaA * cpA * l * rhoA
|                 | |       | at Time=0.000000
|                 | |       | [line] 34 | [file] ScalableTestSuite.Thermal.HeatExchanger.ScaledExperiments.CocurrentHeatExchangerEquations_N_10_functions.c
```

i guess this is the issue mentioned in  #9986

**Comment by casella** [comment]
I guess you are not using the latest version of the library, so you still get sliced arrays, hence the division by zero thing. Please use version 2.0.3.

**Comment by casella** [comment]
After #10009 the correct results are produced, see [test report](https://libraries.openmodelica.org/branches/newInst-newBackend/ScalableTestSuite_noopt/ScalableTestSuite_noopt.html)
