### ISSUE TITLE
Very large real numbers should be written in exponential form

### ISSUE THREAD

**Issue by ceraolo** [OpenModelica/OpenModelica#10476]
### Description

Very large real numbers should be written in exponential form also in plotting perspective
### Steps to Reproduce
Run the following code:
```
model Test
 parameter Real X=1e9;
 Real y;
equation
 y=time;
end Test;
```
This is what is displayed in plotting perspective:
![image](https://user-images.githubusercontent.com/7373030/228961911-23caa060-a287-4356-b67a-7d59b49f6df0.png)
X is too large, and difficult to read

### Expected Behavior
I propose that numerical values be written in a more compact way. In this case the number could be written in several easily-readable ways, such as  1e9, 1.0e9, even 1.000e9. 
Written as 1000000000 is unsatisfying for me: it requires the user to count zeros. Up to 1.000e9, the number is immediately identified without the need of counting zeros.

### Version and OS
1.20.0

 - OpenModelica Version: [e.g. `omc --version` or `Help->About OMEdit` from OMEdit]
 - OS: [e.g. Windows 10, 64 bit]
 - Versions of used Modelica libraries if applicable

**Comment by bilderbuchi** [comment]
In the same breath, very large non-"round" *integers* should probably _not_ be written in floating-point notation? See this from your other issue #10475 -- this obfuscates the true value of the local seed variable (parameter integer).
![image](https://user-images.githubusercontent.com/327442/229041611-45afa53c-fe59-4f8a-b341-bc794d1e31d1.png)

**Comment by ceraolo** [comment]
> In the same breath, very large non-"round" _integers_ should probably _not_ be written in floating-point notation? See this from your other issue #10475 -- this obfuscates the true value of the local seed variable (parameter integer). ![image](https://user-images.githubusercontent.com/327442/229041611-45afa53c-fe59-4f8a-b341-bc794d1e31d1.png)

I agree. However, this is a minor issue (how many people would be interested in knowing all digits of a very large integer number?).

**Comment by casella** [comment]
I guess Integers should be treated as such, an Reals as such. If X is a Real, it should be represented as 1e9, but if localSeed is an Integer, it should be represented as -698243567 (or whatever).

Another case for #8865.

**Comment by casella** [comment]
> how many people would be interested in knowing all digits of a very large integer number?).

For example, if the integer is the seed of a random number generator, you need to see all the digits.

**Comment by ceraolo** [comment]
> > how many people would be interested in knowing all digits of a very large integer number?).
> 
> For example, if the integer is the seed of a random number generator, you need to see all the digits.

Obviously. This was also in https://github.com/OpenModelica/OpenModelica/issues/10476#issuecomment-1491386563, which, btw,came  from an example of mine!
Just because I'm working on these kinds of simulations, I understand the importance of knowing the seed. That's why I called it "a minor issue" (I did not say that it is not an issue).

**Comment by casella** [comment]
This should be easily fixed once we are done with PR 11168, we can just use `_ryu_to_minimal` with `real_output = 0`.

**Comment by casella** [comment]
This issue is now fixed thanks to the Ryu library.

![immagine](https://github.com/OpenModelica/OpenModelica/assets/4233148/7178676d-63cd-40a2-8f0c-5052402bf9b8)

**Comment by ceraolo** [comment]
I've just chcked thte MWE proposed in the ticket description ("Steps to reproduce") using
 v1.22.0-dev-341-gbf24d82543 

I saw that the issue is still there.
