### ISSUE TITLE
Regression in 1.21.0-beta FMU export of integer source fails

### ISSUE THREAD

**Issue by dietmarw** [OpenModelica/OpenModelica#10523]
### Description

With version 1.20.0 it was possible to generate an FMU of a integer source. This is no longer possible with 1.21.0-beta and later (up to  at least `1.22.0~dev-6-g6ab888e`) 

### Steps to Reproduce

With the settings of a source-code only CS FMU, in OMEdit export the block `Modelica.Blocks.IntegerConstant` as FMU.

You will get: 

```
[4] 14:53:02 Translation Error
[Modelica.Blocks.Interfaces: 815:5-816:56]: [Argument ‘$outputAlias_y‘ of der is not differentiable.](omeditmessagesbrowser:///Modelica.Blocks.Interfaces?lineNumber=815)

[5] 14:53:02 Translation Error
pre-optimization module expandDerOperator (simulation) failed.
```

### Expected Behavior

It should create a FMU with Integer output

### Version and OS

 - OpenModelica Version: 1.21.0-beta and later
 - OS: Windows and Linux

**Comment by AnHeuermann** [comment]
@arun3688 could this because of directional derivatives or the dependency analysis for FMUs? I think we had a similar issue at some point.

**Comment by arun3688** [comment]
@AnHeuermann the issue is because of this module `preoptModule=introduceOutputRealDerivatives` , I can confirm this with the below mos script

```
setCommandLineOptions("--preOptModules-=introduceOutputRealDerivatives");
getErrorString();
loadModel(Modelica);
getErrorString();
buildModelFMU(Modelica.Blocks.Sources.IntegerConstant, version="2.0", fmuType="cs");
getErrorString();
```

If we disable that module then it works. 

@dietmarw As an work around you should disable the backend pipeline module `introduceOutputRealDerivatives` and it should work

**Comment by casella** [comment]
@arun3688 thanks for the analysis. The question is, why introduce should introduceOutput _Real_ Derivatives involve Integers? I guess this should be fixed.

**Comment by dietmarw** [comment]
> @dietmarw As an work around you should disable the backend pipeline module `introduceOutputRealDerivatives` and it should work 

@arun3688 Any hint as how this can be achieved with OMEdit?

**Comment by arun3688** [comment]
@dietmarw I found a fix and i will push it today and you can test it tomorrow nightly builds

**Comment by arun3688** [comment]
@dietmarw The issue is fixed with this commit https://github.com/OpenModelica/OpenModelica/commit/2380f7ac3254bcebf76c3ebc3567581bd37cf37f, Please download the nightly builds from tomorrow and test it

**Comment by dietmarw** [comment]
@arun3688 I Just tested with 1.22.0~dev-17-g88d7b96 and it still fails, unfortunately.

**Comment by dietmarw** [comment]
> (maybe the Linux nightly job is broken?)

Yes, that could be the case. What was the address to find the status of those builds again? Is there some documentation on openmodelica.org that I'm missing?

**Comment by bilderbuchi** [comment]
Could be https://test.openmodelica.org/jenkins/job/LINUX_BUILDS/

**Comment by arun3688** [comment]
@dietmarw I am not sure about linux builds, but the windows version works fine, @adrpo can you check the linux builds

**Comment by mahge** [comment]
The Linux builds are indeed broken. I added some C++14 code to `OMPlot` and that seems to have broken it. I am checking if I can fix it quickly.

**Comment by mahge** [comment]
I think C++14 is already available. The failing commandline looks like this
```sh
/opt/rh/devtoolset-11/root/usr/bin/g++ -std=c++14 -c -Os -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -O2 -std=gnu++11 -w -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_SVG_LIB -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -I../../../build/include/omplot/qwt -I../../../build/include/omc/c -I. -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtSvg -isystem /usr/include/qt5/QtPrintSupport -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtCore -I../generatedfiles/moc -isystem /usr/include/libdrm -I/usr/lib64/qt5/mkspecs/linux-g++ -o PlotWindow.o PlotWindow.cpp
```

It first specifies -`std=c++14` and then `-std=gnu++11`. I guess the second specification takes priority. I am trying to see what is adding `-std=gnu++11` option to the commands.

**Comment by mahge** [comment]
I think #10534 should fix it. I have started a [new build](https://test.openmodelica.org/jenkins/blue/organizations/jenkins/LINUX_BUILDS/detail/LINUX_BUILDS/2138/pipeline) for the nightly packages. If everything goes well there should be new packages in about 2 hours.

**Comment by mahge** [comment]
The last build did not pick up the changes (I guess I should have started the build for source packages first. The source packages are built automatically every 1 hour and are now ready). 

There is a [new one running](https://test.openmodelica.org/jenkins/blue/organizations/jenkins/LINUX_BUILDS/detail/LINUX_BUILDS/2139/pipeline/126) which seems to have picked them up. So in about 2 hours more it should be ready 🤞.

**Comment by dietmarw** [comment]
@mahge Thanks, yes latest nightly was available and it works now. So I guess this issue can be closed as fixed via  #10530

**Comment by casella** [comment]
> I will cherry pick this to maintenance/v1.21.

Please don't forget 😄, I still can't see it [there](https://github.com/OpenModelica/OpenModelica/commits/maintenance/v1.21).
