### ISSUE TITLE
Setting a modifier of a replaceable class lets final parameters appear again

### ISSUE THREAD

**Issue by abuntrock** [OpenModelica/OpenModelica#10655]
### Description

Thanks to #7826 we are able to set modifiers of replaceable components via the parameter dialogue using today's nightly with the instance API. However, setting such a modifier seems to make the problem solved in #10394 appear again. Final parameters of the replaceable class are then shown in the parameter dialog again.

### Steps to Reproduce

1. Load the BRSL 2.2.1.
2. Open a new Modelica class.
3. Instantiate `Rexroth_Generic.BRSL_World` and then `Rexroth_Pumps.AxialPistonUnits.VariableUnits_ClosedCircuit.A10VG`.
4. Open the parameter dialogue of the pump and select a choice for the replaceable component `axialPistonUnit`. The modelica text should look like this:
```modelica
model Test
  inner Rexroth_Generic.BRSL_World bRSL_World 
    annotation(Placement(visible = true, transformation(origin = {-66, 88}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Rexroth_Pumps.AxialPistonUnits.VariableUnits_ClosedCircuit.A10VG a10vg_1(redeclare Rexroth_Pumps.Internal.AxialPistonUnits.Database.A10VG.A10VG18_10 axialPistonUnit "A10VG18_______/10")  annotation(
    Placement(visible = true, transformation(origin = {-20, 4}, extent = {{-18, -10}, {10, 10}}, rotation = 0)));

annotation(
    uses(Rexroth_Generic(version = "2.2.1"), Rexroth_Pumps(version = "2.2.1")));
end Test;
```
7. Open the parameter dialogue of the replaceable component `axialPistonUnit` via the new edit button. All the parameters modified with final in the replaceable component declaration shown below are not visible anymore thanks to #10394. (see first screenshot)
```modelica
replaceable Rexroth_Pumps.Internal.AxialPistonUnits.Database.A10VG.A10VG18_10 axialPistonUnit(
final internalUsage = false,
final fluidIndex = fluidIndex,
final flowPulsation = flowPulsation,
final PowerAndEtaCalc = PowerAndEtaCalc,
final useThroughDriveShaft = useThroughDriveShaft,
final showName = showName,
final showPortDescription = showPortDescription,
final phi,
final n,
final pL,
final pA,
final pB,
final usePressureFiltration = usePressureFiltration,
final useExternalFlowSource = useExternalFlowSource,
final rotaryDirection = rotaryDirection,
final pBoost)
```
8. Modify any parameter in the dialogue of `axialPistonUnit` (in our case `dpOpenBoostPRV`), which works perfectly thanks to #7826. The new modelica text of the test model now looks like 
```modelica
model Test
  inner Rexroth_Generic.BRSL_World bRSL_World 
    annotation(Placement(visible = true, transformation(origin = {-66, 88}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Rexroth_Pumps.AxialPistonUnits.VariableUnits_ClosedCircuit.A10VG a10vg_1(redeclare Rexroth_Pumps.Internal.AxialPistonUnits.Database.A10VG.A10VG18_10 axialPistonUnit(dpOpenBoostPRV = 3500000)  "A10VG18_______/10")  annotation(
    Placement(visible = true, transformation(origin = {-20, 4}, extent = {{-18, -10}, {10, 10}}, rotation = 0)));

annotation(
    uses(Rexroth_Generic(version = "2.2.1"), Rexroth_Pumps(version = "2.2.1")));
end Test;
```
9. Close all parameter dialogues.
10. Open the parameter dialogue of the pump and then from `axialPistonUnit` again. The final parameters listed in point 7 are now visible as shown in the second screenshot.

### Expected Behavior

Modifying a parameter of a replaceable class does not change the final attribute (visibility) of other parameters of the same replaceable class.

### Screenshots
My colleague @niklwors will add the two pictures of the parameter dialogue before and after setting a modifier as a comment.

### Version and OS

 - OpenModelica Version: v1.22.0-dev-91-gc254033131 (64-bit) with instance API
 - OS: Windows 10, 64 bit
 - MSL 4.0.0 and BRSL 2.2.1

Thanks for looking into this
Aaron Buntrock - Bosch rexroth

**Comment by niklwors** [comment]
picture 1.
![image001](https://user-images.githubusercontent.com/12269776/236468095-6ce39c2f-db7b-4686-b6d2-c0ddffd2d215.png)
picture 2:

![image002](https://user-images.githubusercontent.com/12269776/236468245-4c0b7145-74f4-43f9-b160-b151f81678a3.png)

**Comment by abuntrock** [comment]
I also checked the flat model output as suggested for the initial ticket #10394.
All the parameters like `axialPistonUnit.PowerAndEtaCalc` are declared as final there. So like in the initial ticket, this seems to be a GUI issue here.

**Comment by casella** [comment]
@perost could you please check if this is an API problem or an OMEdit problem?

**Comment by adeas31** [comment]
I can't reproduce this. I believe this is already fixed as part of #10664 and #10659.

**Comment by abuntrock** [comment]
I can still reproduce this with today's nightly (v1.22.0-dev-97-g721e7e1a28). Is #10664 already included there or will it be included in the upcoming nightly for the first time?

**Comment by abuntrock** [comment]
With today's nightly (v1.22.0-dev-97-g721e7e1a28) I could successfully test the completion of #10659. However, the issue from this ticket is still occuring for me

**Comment by abuntrock** [comment]
@adeas31 Thanks for reopening. I'll try to provide a minimum example independent from the BRSL

**Comment by abuntrock** [comment]
@adeas31 I was able to reproduce this issue with today's nightly (v1.22.0-dev-97-g721e7e1a28) and the following minimum example independent from the BRSL and MSL. 

```modelica
package FinalParamInReplaceable

  model InstanceClassWithReplaceable

    ClassWithReplaceable classWithReplaceable annotation (Placement(transformation(extent={{-20,0},{0,20}})));
  end InstanceClassWithReplaceable;

  model ClassWithReplaceable

    parameter Boolean booleanParam = true;

    replaceable FinalParamInReplaceable.ClassToBeReplaced replaceableComponent(
    final booleanParam = booleanParam)
      annotation(choices(choice(redeclare FinalParamInReplaceable.ClassToBeReplaced replaceableComponent "Some description string")));

  end ClassWithReplaceable;

  model ClassToBeReplaced

    parameter Boolean booleanParam = true;
    parameter Real realParam = 3.5;

  end ClassToBeReplaced;
end FinalParamInReplaceable;
```

Steps to Reproduce:
1. Open `InstanceClassWithReplaceable` and open the parameter dialogue of `classWithReplaceable`. 
2. Select the only available choice for `replaceableComponent`.
3. Step into the parameter dialogue of `replaceableComponent`. Only one parameter (`realParam`) is visible. 
4. Assign any value to `realParam` so that the text layer of `InstanceClassWithReplaceable` looks as follows:
```modelica
model InstanceClassWithReplaceable

  ClassWithReplaceable classWithReplaceable(redeclare FinalParamInReplaceable.ClassToBeReplaced replaceableComponent(realParam = 4.0)  "Some description string")  annotation (Placement(transformation(extent={{-20,0},{0,20}})));
end InstanceClassWithReplaceable;
```
5. Close all parameter dialogues.
6. Repeat steps 1 to 3. Now there are two parameters visible in the parameter dialogue of `replaceableComponent` (`realParam` and `booleanParam`). The second one should not appear since it is always set to final.

**Comment by abuntrock** [comment]
@adeas31 This now works as expected. Thanks a lot.
