### ISSUE TITLE
Some troubles when "Enable instance API" is ON

### ISSUE THREAD

**Issue by mpradovelasco** [OpenModelica/OpenModelica#10697]
### Description
This report affects to three issues commented in discussion issue #10678 concerning the use of a non literal value for Dialog.enable into Annotations. One of them seems a bug, whereas the others two are warnings (second) and a relevant (I think) comment (three) about the behaviour of the enable field.

I try to simplify and give minimal examples. I am working with OpenModelica 1.21 in Windows 11 64 bits.

1. Icons and diagrams with fillpatterns (mainly) generate scripting errors as "Error: Variable FillPattern.Solid not found in scope bryPortPBPK" that impede to see propertly the model diagram.
2. Many new warnings appear. I could not repeat this issue. Perhaps it was due to a bad reset of OpenModelica reset, after activating the "Enable instance API". 
3. If I select enable = boolean (with value false), the input field is disabled, but it is kept on the dialog. 

**Issue 1** 

This code works well:
```
within CybSim;
package Test // LINE
extends Icons.IconsPackage;
import Modelica.Icons;
 partial class Example
 annotation(
    Icon(graphics = {
      Rectangle( lineColor = {255, 170, 0}, fillColor = {255, 170, 0}, fillPattern = FillPattern.Solid, lineThickness = 1, extent = {{-70, 30}, {70, -30}})}, coordinateSystem(initialScale = 0.1)));
 end Example;
end Test;
```
whereas when Line
`package Test // LINE`
is substituted by  
`encapsulated package Test // LINE`
the following error is generated:
[1] 13:31:54 Scripting Error [C:/DESARROLLOYDATOS/Areas/ProyectosNoFinanciados/CybSim/lib/CybSim  Prot/Test.mo:10:10-11:157:writable] Error: Variable FillPattern.Solid not found in scope Example.
And so, the icon of Example class does not appear.

**Issue 3**

The following parameter is deactivated in the dialog when bBloodVfracF = false
```
parameter SI.VolumeFraction BloodVfracF[nBout - 1] "Venous Blood volume fractions for first outputs"
    annotation(Dialog(enable = bBloodVfracF));
```
As shown in the snapshot, the input field is kept in the dialog. 
![NewEnableDialog](https://github.com/OpenModelica/OpenModelica/assets/114144098/0519b45f-8896-4be9-8c17-67d81be77ced)
The alternative behavior that I referred was to hide it on the dialog. I think that both behaviours are compliant with the modelica specifications, but the dialog is simplified when it is hidden. I think this could be an advantage in complex models.

Thank you for your help!

**Comment by casella** [comment]
@mpradovelasco if you want to experiment with the Enable instance API, you should definitely try the latest nightly build. Several issues [have been fixed in the meantime](https://github.com/OpenModelica/OpenModelica/issues?q=label%3A%22COMP%2FGUI%2FInstBased+Interface%22+milestone%3A1.22.0+is%3Aclosed), maybe this problem is solved already.

**Comment by mpradovelasco** [comment]
Hi again,

I have tested the _enable instance API_ issue on 1.22 dev latest, and the issue persists. This one seems associated with "encapsulated" packages. 

For instance, the icon of volEntity fails (Scripting Error CybSim/lib/CybSim Prot/Physiology/Icons.mo:53:12-53:276:writable] Error: Variable Arrow.Filled not found in scope bdryBarrier) in this code:
```
within CybSim.Physiology;
encapsulated package Icons
  extends Icons.IconsPackage;
  import Modelica.Icons;
  partial class volEntity 
    "Base Symbol for a general physiological entity"
    annotation(
      Icon(graphics = {
        Rectangle( lineColor = {255, 170, 0}, fillColor = {255, 170, 0}, fillPattern = FillPattern.Solid, lineThickness = 1, extent = {{-70, 30}, {70, -30}})}, 
        coordinateSystem(initialScale = 0.1)));
  end volEntity;
```
Whereas it works properly in this one:
```
within CybSim.Physiology;
package Icons
  extends Icons.IconsPackage;
  import Modelica.Icons;
  partial class volEntity 
    "Base Symbol for a general physiological entity"
    annotation(
      Icon(graphics = {
        Rectangle( lineColor = {255, 170, 0}, fillColor = {255, 170, 0}, fillPattern = FillPattern.Solid, lineThickness = 1, extent = {{-70, 30}, {70, -30}})}, 
        coordinateSystem(initialScale = 0.1)));
  end volEntity;
```

Thank you!

**Comment by adeas31** [comment]
> 1. Icons and diagrams with fillpatterns (mainly) generate scripting errors as "Error: Variable FillPattern.Solid not found in scope bryPortPBPK" that impede to see propertly the model diagram.

@perost can you please take a look at it.

> 2. If I select enable = boolean (with value false), the input field is disabled, but it is kept on the dialog.

I think this will stay like the way it is now. This is the expected behavior.

**Comment by perost** [comment]
The issue with annotations not being found in encapsulated classes should be fixed in #10758.

**Comment by mpradovelasco** [comment]
Hi @adeas31 
I have tested with success this issue. Thank you again!
