### ISSUE TITLE
Deleting a record deletes the entire model

### ISSUE THREAD

**Issue by ceraolo** [OpenModelica/OpenModelica#10988]
### Description
I have a package which works well with OM 1.20.0.
With OM 1.21.0 if I delete a record from a diagram the entire model is deleted

### Steps to Reproduce
1. Load the package PowerLineMC.mo (I can send it privately: it is the full package of a paper, which cannot be disclosed, nor simplified since every attempt to reduce it caused different and strange issues to pop up; please tell me who I can send it to)
2. open PowerLineWithFence
3. try to delete "g" (click on its icon and push the "del" button on the keyboard)
 => the entire model is deleted and the following message pops up:
![image](https://github.com/OpenModelica/OpenModelica/assets/37046832/f65f4c91-ebd2-4ac1-9186-b1c29b4efb0f)

### Expected Behavior
Just "g" is deleted, not the entire model 

### Version and OS
The issue is observed with OM 1.21.0, with the following general options:
![image](https://github.com/OpenModelica/OpenModelica/assets/37046832/34b9cede-eda4-44ab-bd34-de1e45652074)

It does not occur with OM 1.20 with the followinng general options:
![image](https://github.com/OpenModelica/OpenModelica/assets/37046832/17ecf941-c23c-4580-bbe0-b3f34f3a5d62)

 - OpenModelica Version: [e.g. `omc --version` or `Help->About OMEdit` from OMEdit]
 - OS: [e.g. Windows 10, 64 bit]
 - Versions of used Modelica libraries if applicable

**Comment by casella** [comment]
@ceraolo the model is not deleted, it is just not shown because it becomes invalid (there are reference in the model to a non-existent record `g`) and the new instance-based GUI fails. If you check the textual source code, it is still there.

The new instance-base interface relies on the new frontend to flatten the model, before passing back to OMEdit all the info needed for graphical display. If the flattening fails, no info is returned. The problem is, while one is building a model graphically, the model may actually be incomplete (so it cannot be properly flattened), but there is still enough information to display its parts. So, the new front-end must be made more "tolerant" in this case, and proceed with the flattening anyway.

A lot of these issues have been resolved since 1.20.0 was released. Please try with the latest nightly build. If it works fine, then please close this ticket, otherwise please comment on that, so that @perost can fix this when he comes back.

@perost I guess you can make an MWE yourself very easily, you need a model that uses a record parameter, you drop the record, type its name in the parameter window, and then delete the record.

**Comment by ceraolo** [comment]
> @ceraolo the model is not deleted, it is just not shown because it becomes invalid

It was to be more dramatic and draw attention to this ticket ;-)

>A lot of these issues have been resolved since 1.20.0 was released. 

At least one has been created. As you can see in the ticket's description, the issue is not there with OM 1.20.0, but is appearent with 1.21.0.

**Comment by casella** [comment]
Sorry, I meant "a lot of these issues have been resolved since **1.21.0** was released". Please try with the nightly build.

**Comment by ceraolo** [comment]
Tried with today's nitght build (1.22.0-dev-248). 
The problem is still there.

**Comment by casella** [comment]
OK, @perost and @adeas31 will look into it when they are back from their holidays.

**Comment by perost** [comment]
I improved the handling of invalid references in #11081 and #11082, but I'm mostly just guessing what the issue might be. Let me know if this fixes the issue for you.

**Comment by ceraolo** [comment]
The issue is still present in today's nightly.

If you want I can transfer the model showing the issue to you. Since I don't have your mail, I could ask @casella the favour of sending it to you.
The test is very simple: just try to delete a record from the diagram of PowerLineWithFence, and see whether the rest of the diagram is still there.

**Comment by perost** [comment]
#11101 should fix the remaining issue, now I can view the diagram of the model and deleting `g` from `PowerLineWithFenceSC` also works.

**Comment by ceraolo** [comment]
Thank you!
