### ISSUE TITLE
OMEdit with --NAPI=true segfaults when opening a model

### ISSUE THREAD

**Issue by mwetter** [OpenModelica/OpenModelica#11054]
### Description

OMEdit segfaults when opening `Buildings.Fluid.Movers.BaseClasses.IdealSource`.

### Steps to Reproduce

Use Buildings Library, commit 3185e8f3288c64723f5aa1ba576d3075077c476b (or other versions may also experience it as this is an old model).
Run 
```
cd Buildings
OMEdit --NAPI=true package.mo
```
In the library browser, double click on `Buildings.Fluid.Movers.BaseClasses.IdealSource`

### Expected Behavior

The model should load, instead OMEdit opens the window to provide feedback, and then crashes with a Segmentation fault.

### Version and OS

OpenModelica 1.22.0~dev-263-gfae4e48
Ubuntu 20.04
Buildings, commit 3185e8f3288c64723f5aa1ba576d3075077c476b

### Additional Context

With `--NAPI=false`, OMEdit does not crash.

**Comment by perost** [comment]
Fixed with #11058.

The issue was that OMEdit tried to evaluate a component binding, but the variable lookup returned an empty expression which `Expression::evaluate` didn't handle. The fix solves the immediate issue of crashing by guarding against such things, but I'm not sure if `Model::getVariableBinding` should actually be returning empty expressions in the first place. Something for @adeas31 to look into perhaps?

**Comment by adeas31** [comment]
> but I'm not sure if Model::getVariableBinding should actually be returning empty expressions in the first place. Something for @adeas31 to look into perhaps?

It is fine with empty expressions.

The actual issue is not fixed yet. Its just deferred. Now it is crashing in `Expression::boolValue()`.

**Comment by perost** [comment]
> The actual issue is not fixed yet. Its just deferred. Now it is crashing in `Expression::boolValue()`.

I can't replicate that issue myself, but #11061 should hopefully fix that too.

**Comment by adeas31** [comment]
Thanks @perost. It works now with #11061
