### ISSUE TITLE
ModelicaSystem().getSolutions() does not retrieve the contents of a variable unless the Modelica model is first loaded.

### ISSUE THREAD

**Issue by mjschuh** [OpenModelica/OpenModelica#11052]
### Description

`ModelicaSystem().getSolutions()` does not retrieve the contents of a variable unless the Modelica model is first loaded.  I want to quickly retrieve values from results .mat files and loading the Modelica model takes more than five minutes for my project.  

Using `OMCSessionZMQ.sendExpression("val ...")` quickly returns a variable value at a given time but not all of the values for the duration of the simulation.

Is there a way to `ModelicaSystem().getSolutions()` to retrieve all of the values of variable for the duration of a simulation or a way to use `OMCSessionZMQ.sendExpression("val ...")` or some other `OMCSessionZMQ.sendExpression()` call to retrieve all of the values of a variable?

### Steps to Reproduce

```
-rwxrwxrwx 1 mschuh mschuh    95 Aug  1 09:06 Test.mo
-rwxrwxrwx 1 mschuh mschuh 12398 Aug 16 08:19 Test_res.mat
```
`ModelicaSystem().getSolutions()` does not retrieve the contents of a variable unless the Modelica model is first loaded.
```
Python 3.8.10 (default, May 26 2023, 14:05:08) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from OMPython import ModelicaSystem
>>> mod=ModelicaSystem()
>>> mod.getSolutions(resultfile="Test_res.mat")
('time', 'x', 'y')
>>> mod.getSolutions('x',resultfile="Test_res.mat")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mschuh/.local/lib/python3.8/site-packages/OMPython/__init__.py", line 1319, in getSolutions
    if (varList not in [l["name"] for l in self.quantitiesList] and varList!="time"):
AttributeError: 'ModelicaSystem' object has no attribute 'quantitiesList'
>>> 
```
`getSolutions()` returns the `x` values if `Test.mo` and `Test` are loaded first.  The problem with this is that for my full simulation, it takes more than five minutes for the `ModelicaSystem("Test.mo", "Test")` command to complete.

```
Python 3.8.10 (default, May 26 2023, 14:05:08) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from OMPython import ModelicaSystem
>>> mod_loaded = ModelicaSystem("Test.mo", "Test")
>>> mod_loaded.getSolutions('x',resultfile="Test_res.mat")
array([[5.    , 5.0066, 5.0132, 5.0198, 5.0264, 5.033 , 5.0396, 5.0462,
        5.0528, 5.0594, 5.066 , 5.0726, 5.0792, 5.0858, 5.0924, 5.099 ,
        6.9008, 6.9074, 6.914 , 6.9206, 6.9272, 6.9338, 6.9404, 6.947 ,
        ... many lines not shown ...
        8.2736, 8.2802, 8.2868, 8.2934, 8.3   , 8.3   ]])
```

Using `OMCSessionZMQ` is able to return a value of `x` at a given time, but I am unable to retrieve the entire contents of the `x` variable.
```
Python 3.8.10 (default, May 26 2023, 14:05:08) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from OMPython import OMCSessionZMQ
>>> omc = OMCSessionZMQ()
>>> omc.sendExpression("val(x, 0.5, fileName=\"Test_res.mat\")")
5.5
```

Here is the source code for `Test.mo`
```
model Test "Testing OpenModelica Scripts"
Real x, y;
equation
x = 5.0+time; y = 6.0;
end Test;
```

### Version and OS
```
omc --version
OpenModelica 1.22.0~dev-250-g48ea6c4
```

```
uname -a
Linux ARDWG0121101002 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by arun3688** [comment]
@mjschuh the issue is fixed with this commit https://github.com/OpenModelica/OMPython/commit/a1ec56e2503f239e757c39fbc6242fc3277c84e0, Please pull the latest changes from the master and test it

**Comment by mjschuh** [comment]
Thank you @arun3688 .  I did an `apt-get update; apt-get upgrade` and still seeing the same error message.

By chance do I need to wait for a nightly build or something before I get the updated version you created?

```
mschuh@ARDWG0121101002:~/Training/omshell$ omc --version
OpenModelica 1.22.0~dev-263-gfae4e48
```

```
Python 3.8.10 (default, May 26 2023, 14:05:08) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from OMPython import ModelicaSystem
>>> mod=ModelicaSystem()

>>> mod.getSolutions(resultfile="Test_res.mat")
('time', 'x', 'y')

>>> mod.getSolutions('x', resultfile="Test_res.mat")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mschuh/.local/lib/python3.8/site-packages/OMPython/__init__.py", line 1319, in getSolutions
    if (varList not in [l["name"] for l in self.quantitiesList] and varList!="time"):
AttributeError: 'ModelicaSystem' object has no attribute 'quantitiesList'

```

**Comment by arun3688** [comment]
@mjschuh OMPython is standalone package and you can install it via the pip package, But the changes are pushed to master so you can run the following command to get the latest updates

`python -m pip install -U https://github.com/OpenModelica/OMPython/archive/master.zip
`
see the readme.md for more information https://github.com/OpenModelica/OMPython

**Comment by mjschuh** [comment]
### First question answered - Thanks!
@arun3688  Your patch works!  Thanks!

Is there way to use `OMCSessionZMQ.sendExpression("val ...")` or some other `OMCSessionZMQ.sendExpression()` call to retrieve all of the values of a variable for each timestep like the `mod.getSolutions('x', resultfile="Test_res.mat")` call?

```
python3 -m pip install -U https://github.com/OpenModelica/OMPython/archive/master.zip
```

```
Python 3.8.10 (default, May 26 2023, 14:05:08)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from OMPython import ModelicaSystem
>>> mod=ModelicaSystem()
>>> mod.getSolutions(resultfile="Test_res.mat")
('time', 'x', 'y')

>>> mod.getSolutions('x', resultfile="Test_res.mat")
array([[5.   , 5.002, 5.004, 5.006, 5.008, 5.01 , 5.012, 5.014, 5.016,
        5.018, 5.02 , 5.022, 5.024, 5.026, 5.028, 5.03 , 5.032, 5.034,
        ... many lines not shown ...
        5.972, 5.974, 5.976, 5.978, 5.98 , 5.982, 5.984, 5.986, 5.988,
        5.99 , 5.992, 5.994, 5.996, 5.998, 6.   , 6.   ]])
>>>
```
### More help requested for second approach question
From reading one of your @arun3688 comments in [Error using OMMatlab](https://github.com/OpenModelica/OMMatlab/issues/3), it looks like I should be able to use `readSimulationResult()` to read the values of a variable.  While both `readSimulationResultVars()` and `readSimulationResultSize()` both work for me, I get an error when I try using `readSimulationResult()`.  Can you help me figure out what I am doing wrong?

```
Python 3.8.10 (default, May 26 2023, 14:05:08)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from OMPython import OMCSessionZMQ
>>> omc = OMCSessionZMQ()
>>> omc.sendExpression('readSimulationResultVars(fileName="Test_res.mat")')
('time', 'x', 'y')

>>> omc.sendExpression('readSimulationResultSize(fileName="Test_res.mat")')
502

>>> omc.sendExpression('readSimulationResult(fileName="Test_res.mat", {x, y})')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mschuh/.local/lib/python3.8/site-packages/OMPython/__init__.py", line 782, in sendExpression
    answer = OMTypedParser.parseString(result)
  File "/home/mschuh/.local/lib/python3.8/site-packages/OMPython/OMTypedParser.py", line 120, in parseString
    res = omcGrammar.parseString(string)
  File "/home/mschuh/.local/lib/python3.8/site-packages/pyparsing/util.py", line 256, in _inner
    return fn(self, *args, **kwargs)
  File "/home/mschuh/.local/lib/python3.8/site-packages/pyparsing/core.py", line 1197, in parse_string
    raise exc.with_traceback(None)
pyparsing.exceptions.ParseException: Expected end of text, found 'occurred'  (at char 6), (line:1, col:7)
>>>
```

I tried using OMShell and could not figure out how to properly call readSimulationResult() in the shell either.
```
mschuh@ARLWL0122064005:~/Training/omshell$ OMShell-terminal
OMShell Copyright 1997-2023, Open Source Modelica Consortium (OSMC)
Distributed under OMSC-PL and GPL, see www.openmodelica.org

To get help on using OMShell and OpenModelica, type "help()" and press enter
Set shortOutput flag: true

>>> readSimulationResultVars(fileName="Test_res.mat")
{"time","x","y"}

>>> readSimulationResultSize("Test_res.mat")
502

>>> readSimulationResult("Test_res.mat", "x")

"[<interactive>:1:1-1:0:writable] Error: Class readSimulationResult not found in scope <global scope> (looking for a function or record).
"
```

**Comment by arun3688** [comment]
> Is there way to use `OMCSessionZMQ.sendExpression("val ...")` or some other `OMCSessionZMQ.sendExpression()` call to retrieve all of the values of a variable for each timestep like the `mod.getSolutions('x', resultfile="Test_res.mat")` call?

Yes it is possible to retrieve all the values of a variable, you can use something like below

```
>>> from OMPython import ModelicaSystem
>>> mod = ModelicaSystem()
>>> vars=mod.getSolutions(resultfile="test_res.mat")
>>> vars
('der(x)', 'time', 'x')
>>> mod.getSolutions(list(vars),resultfile="test_res.mat")
array([[1.00000000e+00, 1.00200200e+00, 1.00400801e+00, ...,
        2.71285941e+00, 2.71829058e+00, 2.71829058e+00],
       [0.00000000e+00, 2.00000000e-03, 4.00000000e-03, ...,
        9.98000000e-01, 1.00000000e+00, 1.00000000e+00],
       [1.00000000e+00, 1.00200200e+00, 1.00400801e+00, ...,
        2.71285941e+00, 2.71829058e+00, 2.71829058e+00]])
```

**Comment by arun3688** [comment]
> From reading one of your @arun3688 comments in [Error using OMMatlab](https://github.com/OpenModelica/OMMatlab/issues/3), it looks like I should be able to use `readSimulationResult()` to read the values of a variable. While both `readSimulationResultVars()` and `readSimulationResultSize()` both work for me, I get an error when I try using `readSimulationResult()`. Can you help me figure out what I am doing wrong?

You should escape double quotes, see below

```
>>> from OMPython import OMCSessionZMQ
>>> omc = OMCSessionZMQ()
>>> omc.sendExpression("readSimulationResultVars(\"test_res.mat\")")
('der(x)', 'time', 'x')
>>> omc.sendExpression("readSimulationResultSize(\"test_res.mat\")")
502
>>> omc.sendExpression("readSimulationResult(\"test_res.mat\",{x,der(x)})")
((1.0, 1.00200200161546, 1.00400801286228, 1.006018046344643, 1.008032102968328, 1.010050213246223, 1.012072371599247, 1.014098575878353, 1.016128826083}}

```

**Comment by mjschuh** [comment]
Thank you very much @arun3688 for the help!!!

I think I am missing something when reading the man pages interface information.  I looked back at the many things I tried before posting my previous question and found that I was really close.  I had tried `omc.sendExpression("readSimulationResult(filename=\"Test_res.mat\", {x})")`.  If I had removed the `filename=`, it would have worked.

```
>>> omc.sendExpression("readSimulationResult(filename=\"Test_res.mat\", {x})")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mschuh/.local/lib/python3.8/site-packages/OMPython/__init__.py", line 782, in sendExpression
    answer = OMTypedParser.parseString(result)
  File "/home/mschuh/.local/lib/python3.8/site-packages/OMPython/OMTypedParser.py", line 120, in parseString
    res = omcGrammar.parseString(string)
  File "/home/mschuh/.local/lib/python3.8/site-packages/pyparsing/util.py", line 256, in _inner
    return fn(self, *args, **kwargs)
  File "/home/mschuh/.local/lib/python3.8/site-packages/pyparsing/core.py", line 1197, in parse_string
    raise exc.with_traceback(None)
pyparsing.exceptions.ParseException: Expected end of text, found 'occurred'  (at char 6), (line:1, col:7)
```

The [.OpenModelica.Scripting.readSimulationResult](https://build.openmodelica.org/Documentation/OpenModelica.Scripting.readSimulationResult.html) documentation lists `input String filename;`.  How come `omc.sendExpression("readSimulationResult(filename=\"Test_res.mat\", {x})")` fails and dropping the `filename=` works?

**Comment by arun3688** [comment]
@mjschuh if you are using named arguments in the constructor you should provide all the named arguments that does not have default values, So it should be something like below and it works 

`omc.sendExpression("readSimulationResult(filename=\"test_res.mat\",variables={x})")`

**Comment by bilderbuchi** [comment]
The error message could be improved, I guess. Something like Python's `SyntaxError: positional argument follows keyword argument` (which afaict is exactly the problem at hand) would be clearer, I think.

**Comment by mjschuh** [comment]
Thank you @arun3688 !!!  

It is very helpful to know that all of the named arguments are needed in the constructor if any of them are used.  I did not know this and I will definitely keep this rule in mind when writing code.

When going through old bug reports to figure something out, I find it helpful if they include a copy of what works so here is what worked for me.

```
Python 3.8.10 (default, May 26 2023, 14:05:08)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
>>> omc = OMCSessionZMQ()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'OMCSessionZMQ' is not defined
>>> from OMPython import OMCSessionZMQ
>>> omc = OMCSessionZMQ()

>>> omc.sendExpression("readSimulationResult(filename=\"Test_res.mat\", variables = {x})")
((5.0, 5.0066, 5.0132, 5.0198, ... many values not shown ... 8.2868, 8.2934, 8.3, 8.3),)
```

Here is what did not work because it does not include all of the named arguments in the constructor.
```

>>> omc.sendExpression("readSimulationResult(filename=\"Test_res.mat\", {x})")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mschuh/.local/lib/python3.8/site-packages/OMPython/__init__.py", line 782, in sendExpression
    answer = OMTypedParser.parseString(result)
  File "/home/mschuh/.local/lib/python3.8/site-packages/OMPython/OMTypedParser.py", line 120, in parseString
    res = omcGrammar.parseString(string)
  File "/home/mschuh/.local/lib/python3.8/site-packages/pyparsing/core.py", line 1141, in parse_string
    raise exc.with_traceback(None)
pyparsing.exceptions.ParseException: Expected end of text, found 'occurred'  (at char 6), (line:1, col:7)
```

**Comment by arun3688** [comment]
@casella the issue is fixed with this commit https://github.com/OpenModelica/OMPython/commit/a1ec56e2503f239e757c39fbc6242fc3277c84e0, So i am closing this now
