### ISSUE TITLE
Animation of icon on the diagram is not working like supposed to do

### ISSUE THREAD

**Issue by sbaetzing** [OpenModelica/OpenModelica#11386]
### Description

We have tested different scenarios for the animation feature inside OMEdit (by dynamicSelect annotation). We faced some issues during that. Find attached a powerpoint presentation with a detailed description aswell as a library containing minimal examples

 - OpenModelica Version: [e.g. `omc --version` or `Help->About OMEdit` from OMEdit]
 - OS:  Windows 10, 64 bit

### Additional Context

[icon_anim_testing_OMEdit.pptx](https://github.com/OpenModelica/OpenModelica/files/12928285/icon_anim_testing_OMEdit.pptx)

[icon_anim_testing_OMEdit.zip](https://github.com/OpenModelica/OpenModelica/files/12928287/icon_anim_testing_OMEdit.zip)

Best regards

Sven

**Comment by casella** [comment]
Thanks @sbaetzing for the report. I guess that's too much for fixing 1.22.0, which ought to be rolled out anytime soon. Maybe we could fix this in a maintenance release.

**Comment by sbaetzing** [comment]
thats totally fine. Thats not required in 1.22. Here the used omedit version:
![image](https://github.com/OpenModelica/OpenModelica/assets/84787397/5534e576-2112-46ec-986f-89040bbaec81)

**Comment by casella** [comment]
You should rather try 1.22.0-dev.beta.4

**Comment by adeas31** [comment]
I looked at the attached presentation. The `DynamicSelect` works in normal cases but doesn't work when the non-editing argument contains a conditional statement.

**Comment by casella** [comment]
@sbaetzing we will target this for 1.23.0, to be released end of Q1 2024. We can't really make it for 1.22.1, which is due in a couple of weeks.

**Comment by sbaetzing** [comment]
fine for us. just a  nice to have feature for education usecases

**Comment by AlesVojacek** [comment]
The first three examples attached above are working well when one set instead of zero, a numerical zero (Modelica.Constants.eps).

**Comment by sbaetzing** [comment]
Thanks for first analyses. We where able to confirm that checking for > or < a real small value make the first examples work.
Unfortunately we faced an regarding using an import statement like
  import EPS = Modelica.Constants.eps;

using u > -EPS does not work. but u > -1e-15 works fine.

In my opinion checking for eps should be sufficient.

best regards Sven

**Comment by casella** [comment]
`Modelica.Constants.eps` is the smallest Real number so that `1 + eps <> 1`. This gives you an order of magnitude for numerical rounding errors, but it's not to be considered as an exact value for non-zero threshold, as there may be other approximations involved. You could use something as:
```modelica
constant Real eps = 10*Modelica.Constants.eps;
```

**Comment by perost** [comment]
The first issue with the conditional should be fixed with #12856.

The issue wasn't actually directly related to using a conditional but due to the `y >= 0` expression. The evaluation of relational operations like this in OMEdit didn't take into account that Integers can be type cast to Real and failed on this expression because `y` is `Real` and `0` is an `Integer`.

As for the second issue I'm not sure what you mean by "inherited values", but the actual issue is that we don't support evaluation of functions inside `DynamicSelect` yet. The difference is that when you use
```Modelica
Real direction = IsPositive(x);
...
  visible = DynamicSelect(true, direction)
```
then the function call is evaluated as part of the simulation of `direction`, but in
```Modelica
  visible = DynamicSelect(true, IsPositive(x))
```
then the function isn't a part of the simulation model and won't be evaluated.

Implementing function evaluation in OMEdit hasn't been done yet since it's quite hard if we actually want OMEdit to have the ability to evaluate functions. But these examples demonstrate an alternative solution, maybe we could just break out function calls in DynamicSelect and introduce simulation variables for them instead.

**Comment by abuntrock** [comment]
Sorry for the late reply.  But the first issue with the `y>=0` expression now looks perfect in today's nightly. Thanks a lot.

**Comment by abuntrock** [comment]
@casella As far as I understand the second part of this ticket (function evaluation inside of dynamicSelect statements) is still not working. Is this handled as part of another ticket or should we keep this one open?

**Comment by casella** [comment]
See #13293
