### ISSUE TITLE
Multiple changes of the displayUnit change the actual parameter value

### ISSUE THREAD

**Issue by abuntrock** [OpenModelica/OpenModelica#12004]
### Description

Changing the displayUnit of a parameter multiple times via the parameter dialog can alter the actual value listed in the text view. This problem probably has the same root cause as #12003 but since the symptoms are different I thought opening another ticket would be good. 

### Steps to Reproduce

1. Drag `Modelica.Mechanics.Translational.Components.Mass` onto a new model and add `1` as the value for its length:
```modelica
model test
  Modelica.Mechanics.Translational.Components.Mass mass(L = 1)  
  annotation(Placement(transformation(origin = {-4, 2}, extent = {{-10, -10}, {10, 10}})));
annotation(uses(Modelica(version = "4.0.0")));
end test;
```
2. Change the displayUnit to `mm` via the parameter dialog. The value in the parameter dialog is correctly displayed as `1000` and the text view is also changed accordingly:
```modelica
model test
  Modelica.Mechanics.Translational.Components.Mass mass(L (displayUnit = "mm")= 1)  
  annotation(Placement(transformation(origin = {-4, 2}, extent = {{-10, -10}, {10, 10}})));
annotation(uses(Modelica(version = "4.0.0")));
end test;
```
3. Remove the mass instance from your testmodel and instantiate it again. Add `1` as the length value again. Close and reopen the parameter dialog and change the displayUnit to `km`. Everything is changed correctly.
4. Open the parameter dialog again and change the displayUnit from `km` to `mm`. The value is displayed as `1000.00...1`. Then, the text view looks as follows. When opening the parameter dialog again, the value equals the text view (trailing 1 changed to 2).
```modelica
model test
  Modelica.Mechanics.Translational.Components.Mass mass(L (displayUnit = "mm")= 1.0000000000000002)  
  annotation(Placement(transformation(origin = {-30, 32}, extent = {{-10, -10}, {10, 10}})));
annotation(uses(Modelica(version = "4.0.0")));
end test;
```
5. The actual value is changed only by changing the default value. There seems to be some conversion between `km` and `mm` (difference results in step 2 and 4) happening. 

1. If one repeats the second process again but this time with the display units `Gm` and then `nm`, the value written in the text view is completely different from the actual value `mass(L(displayUnit = "nm") = 1.0000000000000003e-18)`. In addition to that, the display unit cannot be changed view the parameter dialog anymore because the dropdown menu is "frozen".

### Expected Behavior

1. The actual value listed in the text view is independent from the selected displayUnit via the parameter dialog (like it was in OMEdit 1.22.1 where only the displayed value showed rounding problems).
2. The displayUnit can always be changed and does not "freeze" only by changing it multiple times.

### Version and OS

 - OpenModelica Version: v1.23.0-dev-316-g3a47d5ed12
 - OS: Windows 10, 64 bit
 - MSL 4.0.0

### Additional Context

Thanks for looking into this
Aaron Buntrock - Bosch Rexroth

**Comment by casella** [comment]
I think we should fix #8860 first, then look at this issue again.

**Comment by abuntrock** [comment]
This sounds reasonable. I thought that all those rounding problems are fixed but I did not read about about the corner case mentioned in #8860

**Comment by casella** [comment]
After PR #12052 was merged, steps from 1. to 5. no longer have any issues. Point 6 is still valid, something weird is still happening when you first set the length unit to Gm and then change it to nm. New steps to reproduce:
1. Drag the Mass component in a new system
2. Double-click on it, set L to 1 m and click OK
3. Double-click again on it and change the unit to Gm. The underlying code reads `mass(L (displayUnit = "Gm")= 1)`, which is still correct. Unfortunately, after doing this, any further change to the unit do not trigger an immediate unit conversion of the previous value, but only change the display unit, resulting in a different SI unit value which gets saved into the Modelica code.

**Comment by abuntrock** [comment]
This remaining issue might be linked to #12009 right?

**Comment by casella** [comment]
New MWE

1. load the following model
```model
model S
  Modelica.Mechanics.Translational.Components.Mass mass(L = 1) annotation(
    Placement(transformation(origin = {4, 6}, extent = {{-10, -10}, {10, 10}})));
  annotation(
    uses(Modelica(version = "4.0.0")));
end S;
```
2. Double-click on the component and change the unit for L. If units that lead to decimal values (e.g. km leading to 0.001 or mm leading to 1000) are set, the displayed value is updated correctly and the drop-down menu continues to work properly.
3. As soon as a unit leading to a value in scientific notation is triggered (e.g. Gm or um), values stop being updated, leading to wrong SI values being written to the Modelica code

**Comment by casella** [comment]
@adeas31 I think there are two issues to be debugged here. The first shows up with this MWE:
```
model S
  Modelica.Mechanics.Translational.Components.Mass mass(L (displayUnit = "Gm")= 1) annotation(
    Placement(transformation(origin = {4, 6}, extent = {{-10, -10}, {10, 10}})));
  annotation(
    uses(Modelica(version = "4.0.0")));
end S;
```
In this case, the displayed value is in scientific form and is very small (1e-9). The unit drop-down menu can still be used, but it has no effect

The other MWE is
```modelica
model S
  Modelica.Mechanics.Translational.Components.Mass mass(L (displayUnit = "um")= 1e-15) annotation(
    Placement(transformation(origin = {4, 6}, extent = {{-10, -10}, {10, 10}})));
  annotation(
    uses(Modelica(version = "4.0.0")));
end S;
```
In this case the displayed value is even smaller (1e-15) and the display unit drop-down menu is disabled for some reason.

I guess both need to be fixed.

**Comment by casella** [comment]
BTW I'm not really sure if this happens because of my latest fixes to ryu_to_hr, or if it was already broken previously.

**Comment by casella** [comment]
Another, even weirder finding. If you try this MWE:
```
model S
  Modelica.Mechanics.Translational.Components.Mass mass(L = 1e2) annotation(
    Placement(transformation(origin = {4, 6}, extent = {{-10, -10}, {10, 10}})));
  annotation(
    uses(Modelica(version = "4.0.0")));
end S;
```
the unit drop-down menu is disable, and it is so _if you change the modifier value in the source code to any scientific notation value_. Note that there is no unit conversion involved here, as there is no displayUnit annotation.

As I understand, the root cause of the problem is that OMEdit **does not recognize literal Real values written in scientific notation as such**, so it disables unit conversion as if it was presented some generic expression. @adeas31, can you please check that?

**Comment by adeas31** [comment]
Yeah I noticed this as well. PR #12064 fixes the scientific notation issue.

As a workaround, if you start from this model,

```Modelica
model test
  Modelica.Mechanics.Translational.Components.Mass mass(L = 1)  
  annotation(Placement(transformation(origin = {-4, 2}, extent = {{-10, -10}, {10, 10}})));
annotation(uses(Modelica(version = "4.0.0")));
end test;
```

Change the display unit to `nm` and then to `pm` and then to `m`. You don't need to close the dialog. Just the switch between the display units. You started with the whole number 2 and the value that you get back is not a whole number.

**Comment by casella** [comment]
> Yeah I noticed this as well. PR #12064 fixes the scientific notation issue.

Great!

> As a workaround, if you start from this model,
> ...
> Change the display unit to `nm` and then to `pm` and then to `m`. You don't need to close the dialog. Just the switch between the display units. You started with the whole number 2 and the value that you get back is not a whole number.

I guess you need to have L=2 when you start. Indeed, when converting from m to pm, I get 1.9999999999999998e9.

I'll investigate that.

**Comment by casella** [comment]
@adeas31 reports: 

I tested this. Works well with model,
```modelica
model test
  Modelica.Mechanics.Translational.Components.Mass mass(L = 2)  
annotation(Placement(transformation(origin = {-4, 2}, extent = {{-10, -10}, {10, 10}})));
annotation(uses(Modelica(version = "4.0.0")));
end test;
```
Change display unit to nm and then to pm  and then back to meter. Works fine.

But if `L=1` the same cycle doesn't produce the correct result.

**Comment by casella** [comment]
Starting from 1 m and changing unit to nm gives 0e8 instead of 1e9. I guess the [sprintf(str3, "%.12f", mant);](https://github.com/casella/OMCompiler-3rdParty/blob/5451463dd841c7b8c96a3b43e7e49035e49cd936/ryu/ryu/om_format.c#L99) statement gives 10e8 instead of 1e9. I'll investigate that ASAP

**Comment by casella** [comment]
It was 9.9999999999999 being rounded to 10.000000000000, which has two digits before the decimal point and screws up the whole thing. https://github.com/OpenModelica/OMCompiler-3rdParty/pull/156 should fix it.

**Comment by casella** [comment]
Issue solved

**Comment by abuntrock** [comment]
This looks perfect with the current nightly. Thanks a lot

**Comment by abuntrock** [comment]
@casella  @adeas31  I found a remaining problem with today's nightly in my opinion. 
Consider the following modelica package:
```modelica
package DisplayUnit
  model ClassWithInstance
  ClassWithParameter classWithParameter(angularVelocity = 104.71975511965978)  annotation(
      Placement(transformation(origin = {-10, 10}, extent = {{-10, -10}, {10, 10}})));
  end ClassWithInstance;

  model ClassWithParameter
    parameter Modelica.Units.SI.AngularVelocity angularVelocity(displayUnit = "rpm") = 104.71975511965978;
  end ClassWithParameter;

end DisplayUnit;
```

Open the instance `classWithParameter` in the class `ClassWithInstance`. Change the displayUnit to e.g. `"prad/s"` using the parameter dialog. This changes the text layer like follows:

```modelica
model ClassWithInstance
ClassWithParameter classWithParameter(angularVelocity (displayUnit = "prad/s")= 700)  annotation(
    Placement(transformation(origin = {-10, 10}, extent = {{-10, -10}, {10, 10}})));
end ClassWithInstance;
```

So in this case the actual value changes by 30% just by changing the display unit.

**Comment by abuntrock** [comment]
Another example is this case:
```modelica
model test
  Modelica.Mechanics.Translational.Components.Mass mass(L (displayUnit = "m")= 1.23456789123456)  annotation(
    Placement(transformation(origin = {-10, 14}, extent = {{-10, -10}, {10, 10}})));
annotation(uses(Modelica(version = "4.0.0")));
end test;
```
Changing the display unit to um leads to:
```modelica
model test
  Modelica.Mechanics.Translational.Components.Mass mass(L (displayUnit = "um")= 5)  annotation(
    Placement(transformation(origin = {-10, 14}, extent = {{-10, -10}, {10, 10}})));

annotation(uses(Modelica(version = "4.0.0")));
end test;
```

It seems that numbers with a lot of significant digits, which I need to display values with long conversion numbers (like rpm) in good fashion cannot be correctly converted to a unit which requires  scientific notation.

**Comment by casella** [comment]
I figured out what the problem is, my bad. I'll fix this ASAP.

**Comment by casella** [comment]
Should be fixed by OpenModelica/OMCompiler-3rdParty#157

**Comment by casella** [comment]
@abuntrock please check with the next nightly build.

**Comment by casella** [comment]
Mission accomplished 😃 

I also had some fun writing old-fashioned C code...

**Comment by phannebohm** [comment]
Did any of these MWEs make it to the testsuite?

**Comment by casella** [comment]
> Did any of these MWEs make it to the testsuite?

Good question. It's mostly interactive GUI stuff, so I'm not sure how to do that. Maybe we could make it into a script by exploiting the omcommunication log, not sure.
