### ISSUE TITLE
Bug in CMAKE leads to FMU export with missing dependency

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#12065]
From the discussion in #11604, it seems that there is a CMAKE bug that leads to missing dependencies in FMUs if using clang (not if using gcc). 

@bilderbuchi [notes](https://github.com/OpenModelica/OpenModelica/issues/11604#issuecomment-1975883356):

> [This comment](https://gitlab.kitware.com/cmake/cmake/-/issues/20753#note_1377270) in the cmake issue tracker sounds quite relevant, and could be the root cause, and an easy fix (tabs vs spaces). I guess that should be tracked a separate cmake issue, but I don't have an account there. Anybody?
> Can we work around that somehow in the meantime, e.g. with some sed invocation in-between, or somesuch?

I would suggest to implement his proposed workarund and, if possible, to open a ticket on the CMAKE tracker addressing this issue.

**Comment by adrpo** [comment]
For now I have fixed this in our OMDev repos via:
https://gitlab.liu.se/OpenModelica/OMDev/-/commit/e1bb0576bfb1ebb4c63fbbcc6e37fb825da16ac9
and this:
https://gitlab.liu.se/OpenModelica/OMDevUCRT/-/commit/1c8bc4a63fddecee1860961381b1c731e4acd991

I will try to make a PR for CMake.

**Comment by adrpo** [comment]
This fix will end up in v1.22.3 and of course the nightly.

**Comment by adrpo** [comment]
Opened a PR with cmake: https://gitlab.kitware.com/cmake/cmake/-/merge_requests/9325

**Comment by casella** [comment]
@adrpo shall we close this?

**Comment by adrpo** [comment]
Yes, my PR to cmake was merged:
https://gitlab.kitware.com/cmake/cmake/-/merge_requests/9325

**Comment by BasilioPV** [comment]
On the today (12-3-2024) nightly build I have tested FMU export with clang. Their size is 280 kb, so I suppose that is not working. It is implemented on the current nightly?

**Comment by casella** [comment]
@adrpo maybe something is missing to get the OMDev changes into the nightly? Some submodule update?

**Comment by BasilioPV** [comment]
Update: Using today (15-3-2024) build:
FMU now has 459 KB, so there is a difference between previous versions, but the erorr in third party software is the same when try to simulate (see details in #11604):

<img width="370" alt="image" src="https://github.com/OpenModelica/OpenModelica/assets/93596576/b1dc29f5-0d4e-4810-aa8f-49b7608e90c4">

**Comment by BasilioPV** [comment]
Thanks for pointing to Dependencies tool!!

FMU, with clang and CVODE and explicit Euler :

<img width="369" alt="image" src="https://github.com/OpenModelica/OpenModelica/assets/93596576/fbc1bad6-d799-40a4-9cab-86495d9fcb73">

**Comment by AnHeuermann** [comment]
That's looking good. Please open an issue with the FMU importing tool you use so that they'll add `SetDllDirectoryA` before loading the DLL. As far as I know there is no Windows equivalent to setting RPATH on Unix, so we can't tell Windows where to look for libwinpthread-1.dll.

**Comment by AnHeuermann** [comment]
Ah sorry, I misread the output from your image. Did you copy `Test_FMU.dll` out of `FMU/binaries/win64`? The location matters and there should be `libwinpthread-1.dll` in the same directory.

**Comment by BasilioPV** [comment]
There are only these two files in the directory:

<img width="219" alt="image" src="https://github.com/OpenModelica/OpenModelica/assets/93596576/a1e1f998-d4b1-4fde-b44e-a54901d0860f">

Tested with both in the same directory, with the same result:


<img width="157" alt="image" src="https://github.com/OpenModelica/OpenModelica/assets/93596576/56d5a4cb-3650-479d-85a3-344e972bec7d">

**Comment by AnHeuermann** [comment]
Can't reproduce with OpenModelica v1.23.0-dev-416-g0f1ee9aef5 (64-bit) on my Windows 11 or a clean Windows 11 virtual machine. libwinpthread-1.dll is in the binaries directory and Dependencies reports no load errors.

**Comment by casella** [comment]
@BasilioPV do you also see libwinphtread-1.dll in the binaries directory?

**Comment by BasilioPV** [comment]
I have installed the today's OMedit (v1.23.0-dev-420-g1cb1c69e62) (64-bit)
On Simulation, this is configured:

<img width="897" alt="image" src="https://github.com/OpenModelica/OpenModelica/assets/93596576/d3316992-c316-4fb9-a506-118faac55a1f">

On FMI:
<img width="704" alt="image" src="https://github.com/OpenModelica/OpenModelica/assets/93596576/84e310bb-42af-470d-8624-2781ac3d9cd7">

And the Modelica model to export is:

`model Test_FMU
  parameter Real A=2;
  output Real B;
equation
  B=A*time;
end Test_FMU;`

And there is no  libwinphtread-1.dll in the binaries:

<img width="90" alt="image" src="https://github.com/OpenModelica/OpenModelica/assets/93596576/ec9bdd3e-774b-4ec7-bfd8-76e6f4e60812">

My computer is Windows 10 Pro.

**Comment by AnHeuermann** [comment]
I tried again with the settings from your screenshot and here's the resulting FMU:
[Test_FMU.zip](https://github.com/OpenModelica/OpenModelica/files/14883179/Test_FMU.zip)

The only things I can think of are some settings in OMEdit we aren't aware of or some difference between the software on Windows 10 and Windows 11. I don't have access to a Windows 10 VM, so I can't try that.

**Comment by casella** [comment]
@BasilioPV I have Windows 10, I tried to export your MWE and this is the content of binaries/win64
![immagine](https://github.com/OpenModelica/OpenModelica/assets/4233148/fd30fedd-2536-4eca-b668-827d468ed8a7)
I would suggest you to reset the OMEdit options. Maybe there is some setting you made somewhere that break this.

**Comment by BasilioPV** [comment]
Thanks @casella , there are settings that persist after an uninstall + install a new version? How to remove them?

**Comment by BasilioPV** [comment]
Ok, after reset, the MSL 4.0.0 is loaded by default. 

Now this translation error is shown:

[3] 07:58:53 Translation Error
[Test_FMU: 2:3-2:19]: [Parameter A has neither value nor start value, and is fixed during initialization (fixed=true).](omeditmessagesbrowser:///Test_FMU?lineNumber=2)

That I solve by putting the value:

parameter Real A=0;

But the result remains the same:

<img width="712" alt="image" src="https://github.com/OpenModelica/OpenModelica/assets/93596576/8cec9dde-77cb-4e07-ac46-4919ea6d14a6">

**Comment by BasilioPV** [comment]
I have tried now with a clean W10 on a virtual machine (virtualbox). After install the latest nightly build and change only:

<img width="348" alt="image" src="https://github.com/OpenModelica/OpenModelica/assets/93596576/d081b7ae-cecb-4dda-96b4-cd0f09adcca8">
<img width="246" alt="image" src="https://github.com/OpenModelica/OpenModelica/assets/93596576/54275c2f-f136-41f9-9b1a-204fa6269df1">

The result still the same:

<img width="600" alt="image" src="https://github.com/OpenModelica/OpenModelica/assets/93596576/28dfb5c6-adc7-4c23-87cc-c632f82c00a5">

**Comment by casella** [comment]
@AnHeuermann where is the `libwinpthread-1.dll` fetched from? Maybe it's missing on @BasilioPV's computer?

**Comment by BasilioPV** [comment]
On a clean W10 virtual machine, after installing OM nightly build, it is placed at:
<img width="912" alt="image" src="https://github.com/OpenModelica/OpenModelica/assets/93596576/967bf063-02ec-4cd9-85b4-d5ae850369fb">

On my pc is at:

<img width="455" alt="image" src="https://github.com/OpenModelica/OpenModelica/assets/93596576/d93729e7-1117-4f68-ae5d-ab8550669609">

**Comment by AnHeuermann** [comment]
As @BasilioPV showed it's installed together with OpenModelica in `C:\Program Files\OpenModelica1.23.0-dev-64bit\tools\msys\ucrt64\bin`.

You habe OMDev installed. Maybe that's the issue somehow? It also has pthreads and CMake available. But it seems to be the correct ucrt version. Also the git directory is in you PATH. That can lead to incompatibilities between UCRT and MINGW.

**Comment by casella** [comment]
In fact, I don't have OMDev installed, and it works for me.

**Comment by BasilioPV** [comment]
I will start again the process. On a clean W10 VM:

Before install, I don't have the file in the PC:

<img width="117" alt="image" src="https://github.com/OpenModelica/OpenModelica/assets/93596576/4f55cf48-2397-4e7d-a9d7-c169c5dbc6c8">

After Install OM nightly build (of today):

<img width="373" alt="image" src="https://github.com/OpenModelica/OpenModelica/assets/93596576/3a803421-8430-4fb9-a15e-52da09c33a3d">

Now I opne OMedit, load Test_FMU:

<img width="115" alt="image" src="https://github.com/OpenModelica/OpenModelica/assets/93596576/755de2cd-82b5-450b-9374-aa14021d1035">

And directly right click and export to FMU:

<img width="141" alt="image" src="https://github.com/OpenModelica/OpenModelica/assets/93596576/11ef1196-d304-4e49-8954-7b29e47f4055">

Now I test changing only "Explicit Euler" to "CVODE" on FMU export settings:

<img width="244" alt="image" src="https://github.com/OpenModelica/OpenModelica/assets/93596576/8e4648c0-d2cb-4fcb-99cf-2f058b924589">

Still the same. What I'm doing wrong?

**Comment by mahge** [comment]
@AnHeuermann maybe exporting to source code FMU and manually building it can give some idea? 

This is a very odd.

**Comment by mahge** [comment]
> Now I test changing only "Explicit Euler" to "CVODE" on FMU export settings:

@BasilioPV do you mean it works if you export with Euler?

**Comment by BasilioPV** [comment]
No, libwinpthread-1.dll is missing in both Euler and CVODE and none works.

**Comment by BasilioPV** [comment]
> @AnHeuermann maybe exporting to source code FMU and manually building it can give some idea?
> 
> This is a very odd.

How to do this?

**Comment by AnHeuermann** [comment]
Good news everyone. I was finally able to reproduce the issue on a Windows 10 VM 🎉 

The issue:

You can build a source-code FMU by enabling `Include Source Code` in the FMI options:
![grafik](https://github.com/OpenModelica/OpenModelica/assets/38031952/f73a78e7-5b03-46d7-94ea-1649a393da56)

You can re-build the FMU with gcc by doing the following steps:

  - Unzip the fmu to `Test_FMU/`
  - Start a cmd from OMEdit: Tools->OpenModelica command prompt and run:
    ```cmd
    C:\Users\User\AppData\Local\Temp\OpenModelica\OMEdit>cd C:\Users\User\Desktop\Test_FMU\sources

    C:\Users\User\Desktop\Test_FMU\sources>cmake -S. -B build_cmake -G "MSYS Makefiles"
    -- The C compiler identification is GNU 13.2.0
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Check for working C compiler: C:/Program Files/OpenModelica1.23.0-dev-64bit/tools/msys/ucrt64/bin/cc.exe - skipped
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- FMI2 include directory: C:/Program Files/OpenModelica1.23.0-dev-64bit/include/omc/c/fmi
    -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
    -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
    -- Found Threads: TRUE
    -- Building for FMI platform win64
    -- Install directory: C:/Users/User/Desktop/Test_FMU/sources/../binaries/win64
    -- CVODE_DIRECTORY: C:/Program Files/OpenModelica1.23.0-dev-64bit/lib//omc
    -- SUNDIALS_CVODE_LIBRARY: C:/Program Files/OpenModelica1.23.0-dev-64bit/lib/omc/libsundials_cvode.a
    -- SUNDIALS_NVECSERIAL_LIBRARY: C:/Program Files/OpenModelica1.23.0-dev-64bit/lib/omc/libsundials_nvecserial.a
    -- CVODE: C:/Program Files/OpenModelica1.23.0-dev-64bit/lib/omc/libsundials_nvecserial.a C:/Program Files/OpenModelica1.23.0-dev-64bit/lib/omc/libsundials_cvode.a
    -- Not using FMI2_FUNCTION_PREFIX
    -- Installing dynamic dependencies from list: C:/Program Files/OpenModelica1.23.0-dev-64bit/lib/omc/libsundials_cvode.a;C:/Program Files/OpenModelica1.23.0-dev-64bit/lib/omc/libsundials_nvecserial.a
    -- Configuring done (1.6s)
    -- Generating done (0.0s)
    -- Build files have been written to: C:/Users/User/Desktop/Test_FMU/sources/build_cmake

    C:\Users\User\Desktop\Test_FMU\sources>cmake --build build_cmake --target install
    [...]
    Install the project...
    -- Install configuration: ""
    -- Installing: C:/Users/User/Desktop/Test_FMU/sources/../binaries/win64/libTest_FMU.dll.a
    -- Installing: C:/Users/User/Desktop/Test_FMU/sources/../binaries/win64/Test_FMU.dll
    -- Installing: C:/Users/User/Desktop/Test_FMU/sources/../binaries/win64/libwinpthread-1.dll
    ```


If we start again but this time use clang to compile this will not work:

```bash
C:\Users\User\Desktop\Test_FMU\sources>rm -rf ../binaries build_cmake
C:\Users\User\Desktop\Test_FMU\sources>cmake -S. -B build_cmake -G "MSYS Makefiles" -D CMAKE_C_COMPILER=clang
-- The C compiler identification is Clang 17.0.6
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/OpenModelica1.23.0-dev-64bit/tools/msys/ucrt64/bin/clang.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- FMI2 include directory: C:/Program Files/OpenModelica1.23.0-dev-64bit/include/omc/c/fmi
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Building for FMI platform win64
-- Install directory: C:/Users/User/Desktop/Test_FMU/sources/../binaries/win64
-- CVODE_DIRECTORY: C:/Program Files/OpenModelica1.23.0-dev-64bit/lib//omc
-- SUNDIALS_CVODE_LIBRARY: C:/Program Files/OpenModelica1.23.0-dev-64bit/lib/omc/libsundials_cvode.a
-- SUNDIALS_NVECSERIAL_LIBRARY: C:/Program Files/OpenModelica1.23.0-dev-64bit/lib/omc/libsundials_nvecserial.a
-- CVODE: C:/Program Files/OpenModelica1.23.0-dev-64bit/lib/omc/libsundials_nvecserial.a C:/Program Files/OpenModelica1.23.0-dev-64bit/lib/omc/libsundials_cvode.a
-- Not using FMI2_FUNCTION_PREFIX
-- Installing dynamic dependencies from list: C:/Program Files/OpenModelica1.23.0-dev-64bit/lib/omc/libsundials_cvode.a;C:/Program Files/OpenModelica1.23.0-dev-64bit/lib/omc/libsundials_nvecserial.a
-- Configuring done (2.9s)
-- Generating done (0.0s)
-- Build files have been written to: C:/Users/User/Desktop/Test_FMU/sources/build_cmake

C:\Users\User\Desktop\Test_FMU\sources>cmake --build build_cmake --target install
Install the project...
-- Install configuration: ""
-- Installing: C:/Users/User/Desktop/Test_FMU/sources/../binaries/win64/libTest_FMU.dll.a
-- Installing: C:/Users/User/Desktop/Test_FMU/sources/../binaries/win64/Test_FMU.dll
```

So now threads is missing. As far as I know @adrpo fixed that issue with clang in cmake from OMDev in https://gitlab.liu.se/OpenModelica/OMDev/-/commit/e1bb0576bfb1ebb4c63fbbcc6e37fb825da16ac9

**Comment by AnHeuermann** [comment]
I checked C:\Program Files\OpenModelica1.23.0-dev-64bit\tools\msys\ucrt64\share\cmake\Modules
and found an additional `\`.

@adrpo is there a typo in https://gitlab.liu.se/OpenModelica/OMDevUCRT/-/commit/1c8bc4a63fddecee1860961381b1c731e4acd991?
```diff
  elseif(gp_tool MATCHES "objdump(\\.exe)?$")
    set(gp_cmd_args "-p")
-   set(gp_regex "^\[[:blank:]]*DLL Name: (.*\\.[Dd][Ll][Ll])${eol_char}$")
+   set(gp_regex "^[[:blank:]]*DLL Name: (.*\\.[Dd][Ll][Ll])${eol_char}$")
```

**Comment by AnHeuermann** [comment]
@BasilioPV thanks for being persistent so we finally found the issue. You can simply switch your C compiler to gcc/g++ and the FMU export should work for you.

![grafik](https://github.com/OpenModelica/OpenModelica/assets/38031952/6bf36fb1-de96-4d08-8444-a4d82534f3ef)

**Comment by BasilioPV** [comment]
@AnHeuermann Thanks for your work, I hope that this additional `\` will solve this issue. Regarding the switch to gcc/g++ compilers, I know this solution and is used corrently. Thanks again !!

**Comment by mahge** [comment]
So @AnHeuermann and @casella were both using `gcc` and you were using `clang`. In that case, I think it all makes sense. 

_Sorry about the closing and reopening. It was a misclick._

**Comment by casella** [comment]
> So @AnHeuermann and @casella were both using `gcc` and you were using `clang`. 

Not really. These are my OMEdit settings
![immagine](https://github.com/OpenModelica/OpenModelica/assets/4233148/3615198a-b467-4b66-85fc-6108251659bf)

**Comment by mahge** [comment]
Then there is more to this, right? Why does it work for you but not for @AnHeuermann or @BasilioPV?

**Comment by casella** [comment]
I don't have OMDev installed. Maybe we should first fix that typo?

**Comment by AnHeuermann** [comment]
> I don't have OMDev installed. Maybe we should first fix that typo?

On the Windows 10VM I don't have OMDev either.
I tried that, but it doesn't affect this bug. Maybe one needs to re-compile CMake as well?

@casella are you on Windows 10 and if so what OS build? I'm on 21H2 (19044.1288)

**Comment by casella** [comment]
Version 10.0.19045 Build 19045

**Comment by AnHeuermann** [comment]
Then I'm all out of ideas.

**Comment by casella** [comment]
We could install a new version of CMAKE, if available, and put it in 1.23.0-beta

**Comment by BasilioPV** [comment]
I have an update of this issue. After installing VS C++ and mingw-w64 on the pc, now the FMU has  libwinpthread-1.dll inside.

I observe the following: When I select clang on "Simulation" option window on the PC that WORKS FINE, this is in black text:

<img width="918" alt="image" src="https://github.com/OpenModelica/OpenModelica/assets/93596576/b6243925-a19e-4ac2-ac7a-3d364f1784fd">

**Comment by BasilioPV** [comment]
Any news on this?

**Comment by casella** [comment]
@adrpo can you please comment on that

**Comment by bilderbuchi** [comment]
It looks to me like an issue for compiling OM from source could have the same root cause as this here (https://github.com/OpenModelica/OpenModelica/discussions/12965#discussioncomment-10958596), which @adrpo helped me hunt down.

It shows quite similar symptoms:
* Compilation on Windows (10)
* dlls do not get copied to their destination. In this case, `omc.exe` is missing `libopenblas.dll` and `libstdc++-6.dll` filesthat do not get copied to `build_cmake\install_cmake\bin` when building the CMake `install` target. I'm assuming that the FMU collection/packaging also happens during CMake `install`
* Problem only happens when compiling with clang 17.0.6, disappears when using gcc 13.2.0
* OMDev is (necessarily) installed

AFAICT, the [patched cmake](https://gitlab.liu.se/OpenModelica/OMDev/-/commit/e1bb0576bfb1ebb4c63fbbcc6e37fb825da16ac9) is present and used. I'm not sure why the patch does not seem effective. Note that the patch is slightly different from [what got merged ](https://gitlab.kitware.com/cmake/cmake/-/merge_requests/9325/diffs) to CMake upstream.

I'm wondering if the (hard to reproduce) #12640 could also have the same root cause?

**Comment by bilderbuchi** [comment]
One (hopefully) easy attempt to reduce the number of potential problem sources could be to update the CMake in **both** OMDev and OpenModelica to at least CMake 3.29.0. This is where @adrpo's upstream PR got released in AFAICT.
Is that quickly accomplishable?

**Comment by bilderbuchi** [comment]
Also, I'm wondering if https://cmake.org/cmake/help/latest/manual/cmake-generator-expressions.7.html#genex:TARGET_RUNTIME_DLLS could help here to ensure we get all required dlls where they should go, but this is beyond my competence regarding CMake intricacies?

**Comment by BasilioPV** [comment]
Dear all,
Latest version:

OpenModelica v1.25.0-dev-106-g982563026f (64-bit)

Stop working.  libwinpthread-1.dll  is NOT inside FMU even if I select gcc/g++ and Include Source code.

Now, I cannot find a way to export a valid FMU from OMedit. I need to add manually  libwinpthread-1.dll into FMU to work.

Question: It is possible to automaticaly check with "dependencies x64" (command line version) when generating a FMU to check if it's anything missing?

**Comment by arun3688** [comment]
@BasilioPV Can you try the latest nightly builds from yesterday(31-11-2024), because @adrpo made some fixes to the new OMDev to update with latest cmake see https://github.com/OpenModelica/OpenModelica/issues/13053 and this should solve the issue by default i guess

**Comment by BasilioPV** [comment]
The nightly build shows this error:

```
CMake Error at cmake_install.cmake:71 (file):
  file Could not resolve runtime dependencies:

    zlib.dll


make: *** [Makefile:100: install] Error 1
Post compilation process failed. Exited with code 0x00000002.
```

**Comment by arun3688** [comment]
@BasilioPV i guess the dll is missing in your machine, but this should be available from OMDev @adrpo can you comment on this

**Comment by arun3688** [comment]
@BasilioPV do you activated this flag `fmuRuntimeDepends` in your OMEdit ?

**Comment by BasilioPV** [comment]
@arun3688 Same result with this option:
![image](https://github.com/user-attachments/assets/94456b5e-c7ae-488c-9607-f36072d71b1f)
Is the right way to activate this option?

**Comment by arun3688** [comment]
can you set it to `--fmuRuntimeDepends=modelica`

**Comment by BasilioPV** [comment]
@arun3688 Same result:
![image](https://github.com/user-attachments/assets/0f4ba1e5-02ad-4ab2-bdae-9cc1178eeafb)

![image](https://github.com/user-attachments/assets/f82a8d6d-5e24-4ce2-92fe-47ed2205dc30)

**Comment by BasilioPV** [comment]
The result seems to be correct on this example:

```
OMShell 1.1 Copyright Open Source Modelica Consortium (OSMC) 2002-2024
Distributed under OMSC-PL and GPL, see www.openmodelica.org

Connected to OpenModelica v1.25.0-dev-121-g3b470d1ae3 (64-bit)
To get help on using OMShell and OpenModelica, type "help()" and press enter.

>> loadModel(Modelica)
true

>> getErrorString()
""

>> buildModelFMU(Modelica.Blocks.Math.Gain)
"C:/Users/basil/AppData/Local/Temp/OpenModelica/Gain.fmu"
"[C:/Users/basil/AppData/Roaming/.openmodelica/libraries/Modelica 4.0.0+maint.om/Blocks/Math.mo:543:5-544:48:writable] Warning: Parameter k has no value, and is fixed during initialization (fixed=true), using available start value (start=1) as default value.
"
>> getErrorString()
""

>> 
```
I find the FMU ok, with the dll inside:

![image](https://github.com/user-attachments/assets/cd9723ba-a458-4790-b1a2-524cf945eeef)

**Comment by BasilioPV** [comment]
Please, consider this MWE:

[lookup tables.zip](https://github.com/user-attachments/files/17727599/lookup.tables.zip)

When export to FMU with gcc/g++/CVODE/include source code/ ME & CS on v1.25.0-dev-112-gb8e50a499d (64-bit), the FMU export fine BUT without libwinpthread-1.dll inside. After manually adding this dll, works fine.

The same export in today (13/Nov/2024) nightly build shows:

**Comment by BasilioPV** [comment]
If I copy and paste the following file:

C:\Program Files\OpenModelica1.25.0-dev-64bit\bin\zlib1.dll

and rename it to "zlib.dll" on the path "C:\Program Files\OpenModelica1.25.0-dev-64bit\bin\"

Now export to FMU ok... why? is really missing the file? has other name?

**Comment by casella** [comment]
@arun3688 you're help would be appreciated, thanks!

**Comment by adrpo** [comment]
I tested this on OpenModelica v1.24.2 (64-bit) on Windows 11 and the fmu contains:

![image](https://github.com/user-attachments/assets/89057cbc-8580-4ba5-8b5d-2e2b6759a2af)

Running the fmu with FMPy works fine.
```
C:\Temp\lookTabled448>python -m fmpy simulate lookTable.fmu
LOG_STDOUT        | info    | ... loading "datos" from "C:\Users\OpenModelica\AppData\Local\Temp\tmp9yz95x_x\resources\C\Users\OpenModelica\Downloads\lookup.tables\externalTables\Resources\tabla.txt"
```

**Comment by adrpo** [comment]
Tested this also with OpenModelica v1.25.0-dev-173-g8979989a63 (64-bit) on Windows 11 and the fmu contains:
![image](https://github.com/user-attachments/assets/d8bef441-06cf-499c-ab78-c70cb388bce9)

The build log gives:
[cmake-build-log.txt](https://github.com/user-attachments/files/17787074/cmake-build-log.txt)

Running the fmu with FMPy works fine
```
C:\Temp>python -m fmpy simulate lookTable.fmu
LOG_STDOUT        | info    | ... loading "datos" from "C:\Users\OpenModelica\AppData\Local\Temp\tmpi76qb7ey\resources\C\Users\OpenModelica\Downloads\lookup.tables\externalTables\Resources\tabla.txt"
```

**Comment by adrpo** [comment]
Same tests using gcc/g++ instead of clang/clang++ give the same results. 
And it seems zlib.dll is not needed.

**Comment by adrpo** [comment]
I will close this as fixed, please add more info like what OS do you use so I can find out what the problem is.

**Comment by adrpo** [comment]
I also tried to run the produced FMUs it with fmuCheck.win64.exe and that works OK as well.

**Comment by BasilioPV** [comment]
@adrpo I just download the latest nighlty build, uninstall older OM (and erase all folders in program files and user data) and intall OM. when I try to export to FMU "lookTable" with these options:


![image](https://github.com/user-attachments/assets/728c7ce8-48a7-4372-b369-1048ad2c943e)

![image](https://github.com/user-attachments/assets/47221e1c-530f-42ac-bb4a-228465e7e392)

![image](https://github.com/user-attachments/assets/f4837d7f-0f70-4ea3-92c1-d10f40793845)

This is the result:

![image](https://github.com/user-attachments/assets/92e630bb-bc60-46c9-bc15-e1110ded7bf3)

Are I doing something wrong?

**Comment by adrpo** [comment]
The only difference I can see is that you are using `--fmuRuntimeDepends=modelica`
I did not use such flags. However, I can test with them as well, you could test without them. Just remove the flags in Tools->Options->Simulation->Additional Flags, restart OMEdit and try again.

**Comment by BasilioPV** [comment]
The result is the same. But I have tested on a fresh install of W10 ...  and It works ok, no eror. It seems that other sofware installed on my PC is producing the issue.
Can the installation of Visual Studio /C++ produce this?

**Comment by BasilioPV** [comment]
> I can reproduce that CMake zlib.dll error with another model on current nightly (OpenModelica v1.25.0-dev-163-g35bca59dc7).

Did you have Visual Studio or other programming software installed?

**Comment by adrpo** [comment]
I only have the Visual Studio Installer that I used to install Visual Studio Build Tools 2017. Not much otherwise. 

We are trying to set the PATH when we build things so we don't run other programs than the ones shipped with OM but maybe we missed something. Can you send us an email to opemodelica@ida.liu.se with you PATH variable? I might be able to spot some conflicting programs. You can just open a `cmd `then type `set > env-omc.txt' and send us that generated file. I suggest to not upload it here as it might contain sensitive information.

**Comment by adrpo** [comment]
Strangely it did not reached us yet. Please send it also to me directly, you can find my email here: https://www.ida.liu.se/~adrpo33/

**Comment by BasilioPV** [comment]
Done! Please inform of you didn't receive the email

**Comment by adrpo** [comment]
Got it now, thanks!

**Comment by adrpo** [comment]
Ouch, there are plenty things in your PATH that could affect things. 

I guess one could try with an OMEdit.bat that sets the PATH before starting OMEdit.
```
set PATH=%OPENMODELICAHOME%\build\bin;%OPENMODELICAHOME%\tools\msys\ucrt64\bin;C:\Windows\system32;C:\Windows;
"%OPENMODELICAHOME%"\bin\OMEdit
```

And see if you can still get the same issue.

**Comment by adrpo** [comment]
In the meantime I will check where we call some executables to build stuff and do not set the environment properly.

**Comment by BasilioPV** [comment]
Ok, I write a .bat with this commands as you indicate:
```
set > env-omc_before.txt
set PATH=%OPENMODELICAHOME%build\bin;%OPENMODELICAHOME%tools\msys\ucrt64\bin;C:\Windows\system32;C:\Windows;
set > env-omc_after.txt
"%OPENMODELICAHOME%"bin\OMEdit
```
Now work fine. Regardind the zlib.dll library, I found that on "configure" tab the zlib.dll is linked to the binaries folder of another software...: 

```
cmake -G MSYS Makefiles -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang -DCMAKE_COLOR_MAKEFILE=OFF ..
-- The C compiler identification is Clang 18.1.8
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/OpenModelica1.25.0-dev-64bit/tools/msys/ucrt64/bin/clang.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- FMI2 include directory: C:/Program Files/OpenModelica1.25.0-dev-64bit/include/omc/c/fmi
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Building for FMI platform win64
-- Install directory: C:/Users/basil/AppData/Local/Temp/OpenModelica/OMEdit/lookTabled448/412.fmutmp/sources/../binaries/win64
-- Linking C:/Program Files/OpenModelica1.25.0-dev-64bit/lib/omc/libModelicaExternalC.a
-- Linking C:/Program Files/OpenModelica1.25.0-dev-64bit/lib/omc/libModelicaStandardTables.a
-- Linking C:/Program Files/OpenModelica1.25.0-dev-64bit/lib/omc/libModelicaIO.a
-- Linking C:/Program Files/OpenModelica1.25.0-dev-64bit/lib/omc/libModelicaMatIO.a


-- Linking C:/Program Files/OTHER_SOFTWARE/zlib.dll


-- CVODE_DIRECTORY: C:/Program Files/OpenModelica1.25.0-dev-64bit/lib//omc
-- SUNDIALS_CVODE_LIBRARY: C:/Program Files/OpenModelica1.25.0-dev-64bit/lib/omc/libsundials_cvode.a
-- SUNDIALS_NVECSERIAL_LIBRARY: C:/Program Files/OpenModelica1.25.0-dev-64bit/lib/omc/libsundials_nvecserial.a
-- CVODE: C:/Program Files/OpenModelica1.25.0-dev-64bit/lib/omc/libsundials_nvecserial.a C:/Program Files/OpenModelica1.25.0-dev-64bit/lib/omc/libsundials_cvode.a
-- Not using FMI2_FUNCTION_PREFIX
-- Installing dynamic dependencies from list: C:/Program Files/OpenModelica1.25.0-dev-64bit/lib/omc/libModelicaExternalC.a;C:/Program Files/OpenModelica1.25.0-dev-64bit/lib/omc/libModelicaStandardTables.a;C:/Program Files/OpenModelica1.25.0-dev-64bit/lib/omc/libModelicaIO.a;C:/Program Files/OpenModelica1.25.0-dev-64bit/lib/omc/libModelicaMatIO.a;C:/Program Files/Simcenter/2021.2/Amesim/win64/zlib.dll;C:/Program Files/OpenModelica1.25.0-dev-64bit/lib/omc/libsundials_cvode.a;C:/Program Files/OpenModelica1.25.0-dev-64bit/lib/omc/libsundials_nvecserial.a
-- Configuring done (3.3s)
-- Generating done (0.1s)
-- Build files have been written to: C:/Users/basil/AppData/Local/Temp/OpenModelica/OMEdit/lookTabled448/412.fmutmp/sources/build_cmake
Generated cmake target files successfully.
```

**Comment by adrpo** [comment]
I haven't checked yet, but my feeling is that when you add the `--fmuRuntimeDepends=modelica` it will also look for dependencies needed for the ModelicaExternalC libraries (which contain the code for Modelica Tables, etc) and those do need zlib.dll 

Anyhow, it looks like we are calling cmake without properly curating the PATH and that means it will find dlls where it shouldn't.
I will continue with the investigation until we find the issue.

**Comment by BasilioPV** [comment]
Not sure, the issue is present also when no "Additional Translation Flags:" are defined.

If I perform this:

> If I copy and paste the following file:
> 
> C:\Program Files\OpenModelica1.25.0-dev-64bit\bin\zlib1.dll
> 
> and rename it to "zlib.dll" on the path "C:\Program Files\OpenModelica1.25.0-dev-64bit\bin"

Then the file is found at OpenModelica/bin path:

```
....
-- Linking C:/Program Files/OpenModelica1.25.0-dev-64bit/lib/omc/libModelicaExternalC.a
-- Linking C:/Program Files/OpenModelica1.25.0-dev-64bit/lib/omc/libModelicaStandardTables.a
-- Linking C:/Program Files/OpenModelica1.25.0-dev-64bit/lib/omc/libModelicaIO.a
-- Linking C:/Program Files/OpenModelica1.25.0-dev-64bit/lib/omc/libModelicaMatIO.a
-- Linking C:/Program Files/OpenModelica1.25.0-dev-64bit/bin/zlib.dll
-- CVODE_DIRECTORY: C:/Program Files/OpenModelica1.25.0-dev-64bit/lib//omc
-- SUNDIALS_CVODE_LIBRARY: C:/Program Files/OpenModelica1.25.0-dev-64bit/lib/omc/libsundials_cvode.a
....
```
And the export works! I hope that this helps.
Thanks!

**Comment by adrpo** [comment]
It helps, I know what to do, will make some changes and play with this.
Usually we compiled the code using `%OPENMODELICAHOME%\share\omc\scripts\Compile.bat` which takes care of setting the PATH in such a way so that only OM dll libraries can be found.

When we changed the FMU compilation from Compile.bat/make to cmake this restriction was not present anymore and whatever cmake finds in the PATH first is taken as a dependency and also it seems that `.dll` are prefered to `.a` files.
I just need to make a change to how we call cmake to only have OM dlls/static libs and tools/msys/ucrt64/bin in the PATH.

**Comment by BasilioPV** [comment]
@adrpo Thanks for the details! Great work!

**Comment by bilderbuchi** [comment]
> > I can reproduce that CMake zlib.dll error with another model on current nightly (OpenModelica v1.25.0-dev-163-g35bca59dc7).
> 
> Did you have Visual Studio or other programming software installed?

Yes, Python for example (including e.g. Fortran and cpp compilers), and another MSys installation, OMDev and Git. And Docker. OM is not the only thing I'm using this computer for ;-) :-P

I'm not using `--fmuRuntimeDepends=modelica`.
> I found that on "configure" tab the zlib.dll is linked to the binaries folder of another software...:

This was a good hint! In my case, in my case it's picking zlib up from my Python installation (which is on my PATH):
> -- Linking C:/Users/my-user/AppData/Local/mambaforge/zlib.dll

Yeah, it seems like making sure that OM is **pre**pended in the path that CMake sees, so that OM's artifacts are found first should fix this.

**Comment by bilderbuchi** [comment]
It seems like OMEdit does something different from the Tools->OpenModelica Command Prompt.
If I export an FMU via the GUI, it tries to (incorrectly) link to the external zlib.dll
If I open said command prompt, go to the `..fmutmp/sources/build_cmake` folder for that FMU, clean it out, and then do the same command for the Configure step that is visible in the GUI, it (correctly) links to C:/OpenModelica1.25.0-dev-64bit/lib/omc/cpp/libzlib.a` 
😕 ??
Maybe that helps you finding the difference causing this problem?

I have confirmed that the cmake that the command prompt uses is the one from the OpenModelica installation.

**Comment by bilderbuchi** [comment]
Any updates on this? I'm still seeing this after the latest round of dll fixes.

**Comment by adrpo** [comment]
Thanks for the reminder, I have a PR that fixes this but I need to test it more. I'll have a look tomorrow.

**Comment by adrpo** [comment]
PR #13369 should fix this.

**Comment by adrpo** [comment]
@bilderbuchi please test with tomorrow's nightly-builds.

**Comment by BasilioPV** [comment]
@adrpo For me, both zlib.dll and original  libwinphtread-1.dll issues are solved. Thanks!!

**Comment by bilderbuchi** [comment]
> @bilderbuchi please test with tomorrow's nightly-builds.

Apparently the windows nightly did not get built in the night. With yesterday's v1.25.0-dev-233-gb52eb46d5b, which seems to contain your commit b52eb4 as per the changelog, I am still seeing the problem as before(https://github.com/OpenModelica/OpenModelica/issues/12065#issuecomment-2482137550) that it picks up the `zlib.dll` from my Python installation during CMake configure:
> -- Linking C:/Users/myuser/AppData/Local/mambaforge/zlib.dll

**Comment by bilderbuchi** [comment]
Interestingly, if I open the Tools->"OpenModelica Command Prompt", `echo %path%` only lists `C:\OpenModelica1.25.0-dev-64bit\..` paths, but Tools-> Open Terminal has my ususal PATH, which contains that mambaforge path _after_ the OM-related entries.
I don't know in which of those two environments the Export->FMU function operates in, or if this is related to your fix.

**Comment by adrpo** [comment]
I only restrict the PATH when calling cmake and make from OMC. I think the path should remain full on command prompt.

**Comment by adrpo** [comment]
I have to check if some restrictions are needed also in OMEdit as OMEdit calls these itself so it can show the progress.

**Comment by adrpo** [comment]
OMEdit fixes are needed as well. I'll fix this today. If you build the FMU from omc using scripting, should work but OMEdit calls cmake itself. Needs some restrictions there as well.

**Comment by adrpo** [comment]
Thank you for the testing, I will check what's going on.

**Comment by adrpo** [comment]
Can you upload your CMakeLists.txt from the generated FMU?

**Comment by adrpo** [comment]
The search for dlls is restricted to the EXTERNAL_DIRECTORIES that is defined in the CMakeLists.txt

**Comment by bilderbuchi** [comment]
> Can you upload your CMakeLists.txt from the generated FMU?

Sure, here it is (sanitized for private info). [CMakeLists.txt](https://github.com/user-attachments/files/18075248/CMakeLists.txt)

I suspect the critical point is that
```cmake
find_library(zlib
             NAMES zlib
             PATHS ${EXTERNAL_LIBDIRECTORIES})
```
gives the wrong result.

Probably diagnosing that with https://cmake.org/cmake/help/latest/variable/CMAKE_FIND_DEBUG_MODE.html could yield some insight. If you can point me to the CMakeLists template used by the OMEdit Export FMU function (if such a thing exists), I can try inserting that in the file and we might learn more.

**Comment by bilderbuchi** [comment]
> Argh, that is very weird. I found the following SO question, do the various answers help? https://stackoverflow.com/questions/58347250/how-to-find-static-version-of-zlib-in-cmake I'm not sure because I don't know if CMake (implicitly) ends up using FindZLIB.cmake in the end, which could explain why CMake prefers the dynamic version even if it finds the static one first.

Or maybe we should use the flag that seems to be intended for this, as I linked to above ^: `set(ZLIB_USE_STATIC_LIBS "ON")`?

**Comment by adrpo** [comment]
Very strange that it picks something out of the PATH instead of the given EXTERNAL_DIRECTORIES. It just shouldn't. I'll debug a bit.

**Comment by adrpo** [comment]
I can do the `set(ZLIB_USE_STATIC_LIBS "ON")? (from cmake 3.24)` but we should find the actual issue.
The template for cmake: is actually an algorithm in the code:
https://github.com/OpenModelica/OpenModelica/blob/master/OMCompiler/Compiler/Script/CevalScriptBackend.mo#L3725
I hate this, we should have like text templates in the OM installation that we read and replace variables in them. 
This approach would let ppl fix their installation without the need to recompile or getting another version. 
I will open a ticket about this so we can move this kind of generation to some file-based templates.

**Comment by adrpo** [comment]
I have been talking rubbish, we have such a template.

The `CMakeLists.txt.in`:
https://github.com/OpenModelica/OpenModelica/blob/master/OMCompiler/SimulationRuntime/fmi/export/buildproject/CMakeLists.txt.in
is the text file template that we configure via cmake into `CMakeLists.txt` and we copy it to the FMU here:
https://github.com/OpenModelica/OpenModelica/blob/master/OMCompiler/Compiler/SimCode/SimCodeMain.mo#L948
In the OM installation you can find the template file here: `%OPENMODELICAHOME%/share/omc/runtime/c/fmi/buildproject/`

**Comment by bilderbuchi** [comment]
> I have been talking rubbish, we have such a template.
> 
> The `CMakeLists.txt.in`: https://github.com/OpenModelica/OpenModelica/blob/master/OMCompiler/SimulationRuntime/fmi/export/buildproject/CMakeLists.txt.in is the text file template that we configure via cmake into `CMakeLists.txt` and we copy it to the FMU here: https://github.com/OpenModelica/OpenModelica/blob/master/OMCompiler/Compiler/SimCode/SimCodeMain.mo#L948 In the OM installation you can find the template file here: `%OPENMODELICAHOME%/share/omc/runtime/c/fmi/buildproject/`

Thanks, this is a pointer in the right direction. Unfortunately, the part we are interested in gets manually patched into that template's content at https://github.com/OpenModelica/OpenModelica/blob/57820e794bfcd08cd2c0e86591979007008e2f11/OMCompiler/Compiler/SimCode/SimCodeMain.mo#L994, as the result of calling `SimCodeUtil.getCmakeLinkLibrariesCode(simCode.makefileParams.libs)`.

That function seems to be defined at https://github.com/OpenModelica/OpenModelica/blob/57820e794bfcd08cd2c0e86591979007008e2f11/OMCompiler/Compiler/SimCode/SimCodeUtil.mo#L15885
[This comment](https://github.com/OpenModelica/OpenModelica/blob/57820e794bfcd08cd2c0e86591979007008e2f11/OMCompiler/Compiler/SimCode/SimCodeUtil.mo#L15900) seems to suggest that we somehow circumvent the `find_library` functionality of CMake?
And indeed, setting `set(ZLIB_USE_STATIC_LIBS "ON")` does not seem to have an effect.


Btw I noticed there is a typo in the generated CMakeLists file: 
`"${DOCKER_VOL_DIR}C:/OpenModelica1.25.0-dev-64bit/lib//omc"`, and this is where the zlib library resides -- coudl that be the reason?

**Comment by bilderbuchi** [comment]
> Btw I noticed there is a typo in the generated CMakeLists file:
> `"${DOCKER_VOL_DIR}C:/OpenModelica1.25.0-dev-64bit/lib//omc"`, and this is where the zlib library resides -- coudl that be the reason?

Ultimately, there seems to be a malformed entry in `simCode.makefileParams.libs` [here](https://github.com/OpenModelica/OpenModelica/blob/57820e794bfcd08cd2c0e86591979007008e2f11/OMCompiler/Compiler/SimCode/SimCodeMain.mo#L994), but again, no idea where that comes from.. too much indirection for the webinterface at least :-(

**Comment by adrpo** [comment]
Hi, can you try this, change your cmake to add `NO_DEFAULT_PATH`?

```
find_library(zlib
     NAMES zlib
     PATHS ${EXTERNAL_LIBDIRECTORIES} NO_DEFAULT_PATH)
```

and then configure and build again so we can see if it still finds the `zlib.dll` outside the `EXTERNAL_LIBDIRECTORIES`.

**Comment by bilderbuchi** [comment]
Ha, I overlooked that I could easily wrap the debugging `set(CMAKE_FIND_DEBUG_MODE TRUE)` around all the libs, that's the zlib output (with the cmake file as-is): 
```
CMake Debug Log at CMakeLists.txt:197 (find_library):
  find_library called with the following settings:

    VAR: zlib
    NAMES: "zlib"
    Documentation: Path to a library.
    Framework
      Only Search Frameworks: 0
      Search Frameworks Last: 0
      Search Frameworks First: 0
    AppBundle
      Only Search AppBundle: 0
      Search AppBundle Last: 0
      Search AppBundle First: 0
    CMAKE_FIND_USE_CMAKE_PATH: 1
    CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: 1
    CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: 1
    CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: 1
    CMAKE_FIND_USE_INSTALL_PREFIX: 1

  find_library considered the following locations:

    C:/OpenModelica1.25.0-dev-64bit/bin/(lib|)zlib(\.lib|\.dll|\.a)
    C:/OpenModelica1.25.0-dev-64bit/lib/(lib|)zlib(\.lib|\.dll|\.a)
    C:/OpenModelica1.25.0-dev-64bit/tools/msys/ucrt64/bin/(lib|)zlib(\.lib|\.dll|\.a)
    C:/OpenModelica1.25.0-dev-64bit/tools/msys/usr/bin/(lib|)zlib(\.lib|\.dll|\.a)
    C:/Windows/System32/(lib|)zlib(\.lib|\.dll|\.a)
    C:/Windows/(lib|)zlib(\.lib|\.dll|\.a)
    C:/Windows/System32/wbem/(lib|)zlib(\.lib|\.dll|\.a)
    C:/Windows/System32/WindowsPowerShell/v1.0/(lib|)zlib(\.lib|\.dll|\.a)
    C:/Windows/System32/OpenSSH/(lib|)zlib(\.lib|\.dll|\.a)
    C:/Windows/System32/config/systemprofile/AppData/Local/Microsoft/WindowsApps/(lib|)zlib(\.lib|\.dll|\.a)
    <snip-internal>
    C:/Program Files/dotnet/(lib|)zlib(\.lib|\.dll|\.a)
    C:/Program Files/Docker/Docker/resources/bin/(lib|)zlib(\.lib|\.dll|\.a)
    C:/Program Files/Microsoft VS Code/bin/(lib|)zlib(\.lib|\.dll|\.a)
    C:/Program Files/Meld/(lib|)zlib(\.lib|\.dll|\.a)
    C:/texlive/2021/bin/win32/(lib|)zlib(\.lib|\.dll|\.a)

  The item was found at

    C:/Users/myuser/AppData/Local/mambaforge/zlib.dll
```
I make the following observations: 
1. the static `zlib` is at "C:\OpenModelica1.25.0-dev-64bit\lib\omc\libzlib.a", but this is NOT on this list of locations
2. The second entry C:/OpenModelica1.25.0-dev-64bit/lib/ does not contain any libraries at all, those are all in subfolders `omc` and `python`, respectively. I don't know if cmake recurses into subfolders.
3. The location where the item is found is not in that list at all? 😅

**Comment by bilderbuchi** [comment]
> Hi, can you try this, change your cmake to add `NO_DEFAULT_PATH`?
> 
> ```
> find_library(zlib
>      NAMES zlib
>      PATHS ${EXTERNAL_LIBDIRECTORIES} NO_DEFAULT_PATH)
> ```
> 
> and then configure and build again so we can see if it still finds the `zlib.dll` outside the `EXTERNAL_LIBDIRECTORIES`.

OK. To prepare, I export FMU once in OMEdit (to get the fmutmp filled), then I
* empty the `build_cmake` in the fmutmp/sources directory, 
* open Tools -> Terminal and in `build_cmake` 
* run `cmake -G "MSYS Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang -DCMAKE_COLOR_MAKEFILE=OFF ..` (same as the GUI export does)

I get the same list of locations as above, with an additional entry at the start: `C:/Users/myuser/AppData/Local/mambaforge/condabin/(lib|)zlib(\.lib|\.dll|\.a)`, which makes sense -- it picks the dynamic lib from there.

If I add `NO_DEFAULT_PATH` to the generated Cmake file as you suggest, then redo the bullet list, I get the correct choice:

```
-- Linking C:/OpenModelica1.25.0-dev-64bit/lib/omc/libModelicaMatIO.a
CMake Debug Log at CMakeLists.txt:197 (find_library):
  find_library called with the following settings:

    VAR: zlib
    NAMES: "zlib"
    Documentation: Path to a library.
    Framework
      Only Search Frameworks: 0
      Search Frameworks Last: 0
      Search Frameworks First: 0
    AppBundle
      Only Search AppBundle: 0
      Search AppBundle Last: 0
      Search AppBundle First: 0
    NO_DEFAULT_PATH Enabled

  find_library considered the following locations:

    C:/OpenModelica1.25.0-dev-64bit/bin/(lib|)zlib(\.lib|\.dll|\.a)

  The item was found at

    C:/OpenModelica1.25.0-dev-64bit/lib/omc/libzlib.a
```
Note:  it seems Cmake _does indeed_ recurse into subdirectories

Note2: _Instead of this_ fixing the `EXTERNAL_LIBDIRECTORIES` path with the double slash does _not_ make CMake find the correct library

**Comment by adrpo** [comment]
Thank you for the testing. I will fix the paths and add the NO_DEFAULT_PATH. The double / or double \ is not a problem, it will work fine.

**Comment by adrpo** [comment]
Changes done in PR #13401. We will not close this ticket until we get some feedback from the user testing.

I think the previous changes with environment variable PATH restrictions are not really necessary anymore, I will check that and adapt the code if necessary (use again systemCall instead of the new systemCallWithRestrictedEnv).

**Comment by adrpo** [comment]
Keep this open until he user tests on his computer.

**Comment by bilderbuchi** [comment]
Success! I confirmed with today's nightly:
> -- Linking C:/OpenModelica1.25.0-dev-64bit/lib/omc/libzlib.a
🥳 Thank you for your persistence, let's close this!

**Comment by adrpo** [comment]
Yeee 😀
One down ... 2k to go.

**Comment by bilderbuchi** [comment]
> 2k to go.

There's always more where those came from. :-)
"Der Weg ist das Ziel", or "Det är väget som är mödan värd" 😁

**Comment by BasilioPV** [comment]
Congratulations 🎉🎉🎉! Great work!

**Comment by casella** [comment]
> "Der Weg ist das Ziel"

There is always one more bug (corollary of Murphy's Law)
