### ISSUE TITLE
translateModelFMU should be properly documented

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#13137]
PR #12891 improved `translateModelFMU()` to be used by OMEdit in order to get visual feedback about the compilation process. The documentation should reflect that. What I see now in the code:

https://github.com/OpenModelica/OpenModelica/blob/4bd69db6a1e9316223736169e8102e928045881e/OMCompiler/Compiler/FrontEnd/ModelicaBuiltin.mo#L2527-L2529

is incorrect, because the function is not deprecated at all (we use it and we just improved it), and it translates a modelica model into C code *for an FMU*.

Last, but not least, the function documentation should show up in the [Scripting API documentation](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/scripting_api.html)

@arun3688 can you please take care of that? Thanks!

**Comment by adeas31** [comment]
It is not documented because it is marked `Deprecated`. I guess @arun3688 forgot to remove the `Deprecated` when he fixed the API with PR #12891.

**Comment by casella** [comment]
@arun3688 please remove the Deprecated attribute for translateModelFMU, so it shows up in the documentation. Thanks!

**Comment by adeas31** [comment]
@arun3688 any update on this?

**Comment by casella** [comment]
@arun3688 please remove the `Deprecated` attribute for `translateModelFMU`, so it shows up in the documentation in time for 1.26.0

Thanks!

**Comment by arun3688** [comment]
@casella the issue is fixed with this 4764017ec8144c3816cd410592ce841420698710

**Comment by casella** [comment]
Great, thanks!

Before closing the ticket, I'll wait until the [API documentation](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/scripting_api.html) is re-generated to see if it shows up there.

**Comment by casella** [comment]
@arun3688 I still don't see it in the [User's Guide](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/scripting_api.html).

@adeas31 is there any other problem behind this?

**Comment by perost** [comment]
> [@arun3688](https://github.com/arun3688) I still don't see it in the [User's Guide](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/scripting_api.html).
> 
> [@adeas31](https://github.com/adeas31) is there any other problem behind this?

@arun3688 only changed the OF ModelicaBuiltin, but it's [NFModelicaBuiltin](https://github.com/OpenModelica/OpenModelica/blob/master/OMCompiler/Compiler/NFFrontEnd/NFModelicaBuiltin.mo) that's used to generate the documentation since it's the one loaded by default.

**Comment by casella** [comment]
@adeas31 will take care of that, as decided during today's devmeeting

**Comment by adeas31** [comment]
https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/scripting_api.html#translatemodelfmu
