### ISSUE TITLE
FMU reference headers issue

### ISSUE THREAD

**Issue by BasilioPV** [OpenModelica/OpenModelica#13213]
@BasilioPV I guess we need to copy the FMI headers directly into sources to avoid this, i will try to fix this

_Originally posted by @arun3688 in https://github.com/OpenModelica/OpenModelica/issues/12568#issuecomment-2474841480_

**Comment by BasilioPV** [comment]
Update: The issue of missing header only occurs in CVODE in both gcc/clang compilers. For Euler Explicit, both gcc/clang works fine (it is possible to recompile the FMU in ARM64, on this case)

**Comment by arun3688** [comment]
@BasilioPV the issue is fixed with this commit 8b1588cac61f5a8f6d6010145bdf6d14776ec65b, please test from the nightly builds tomorrow (07-12-2024)

**Comment by BasilioPV** [comment]
@arun3688 Tested with today build and still the same original issue as result:

I can't find also "omc_config.h" anywhere inside the FMU. 

> ### Description
> When export any model to FMU under Solver CVODE and using gcc/g++ as compiler: example:
> 
> ```
> model eee "Description of eee"
>   Modelica.Units.SI.TemperatureDifference Tdiff;
>   Modelica.Thermal.HeatTransfer.Components.HeatCapacitor heatCapacitor(C = 10000, T(start = 473.15, fixed = false))  annotation(
>     Placement(transformation(origin = {-10, 38}, extent = {{-10, -10}, {10, 10}})));
>   Modelica.Thermal.HeatTransfer.Components.ThermalConductor thermalConductor(G = 10)  annotation(
>     Placement(transformation(origin = {10, 8}, extent = {{-10, -10}, {10, 10}})));
>   Modelica.Thermal.HeatTransfer.Sources.FixedTemperature fixedTemperature(T = 303.15)  annotation(
>     Placement(transformation(origin = {46, 8}, extent = {{10, -10}, {-10, 10}}, rotation = -0)));
> equation
>   connect(heatCapacitor.port, thermalConductor.port_a) annotation(
>     Line(points = {{-10, 28}, {-10, 8}, {0, 8}}, color = {191, 0, 0}));
>   connect(thermalConductor.port_b, fixedTemperature.port) annotation(
>     Line(points = {{20, 8}, {36, 8}}, color = {191, 0, 0}));
>   Tdiff=thermalConductor.port_a.T-thermalConductor.port_b.T;
>   
> 
> annotation(version="1.0",
>     uses(Modelica(version = "4.0.0")),
>     Documentation(info = "<html><head></head><body>Text editor sample</body></html>", revisions = "<html><head></head><body>Revision text</body></html>", __OpenModelica_infoHeader = "<html><head></head><body>Header Text sample</body></html>"));
> 
> end eee;
> ```
> 
> Then I put the FMU into a raspberry Pi to compile it with FMPy (FMPY compile xxx.fmu), the following error appears:
> 
> <img alt="image" width="401" src="https://private-user-images.githubusercontent.com/93596576/339024774-2c581ba7-a11a-4aa6-ab17-d68598fe97c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM2NDAwNTMsIm5iZiI6MTczMzYzOTc1MywicGF0aCI6Ii85MzU5NjU3Ni8zMzkwMjQ3NzQtMmM1ODFiYTctYTExYS00YWE2LWFiMTctZDY4NTk4ZmU5N2MzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA4VDA2MzU1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmZjBiYThjNGVkMTU5YzA3ZWVhZWM2Zjg2OWYwZjBhOWZkYWQ1MjQ5NjZjYTY0ZTc5OTVmNDYxYTBkNzgxZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PLLda_IixlhUP22u3_knRyuaBz3FLH_WPsACitXtg3A">
> This error does not occur using "Euler explicit" as solver, which compiles and works fine.
>

**Comment by arun3688** [comment]
@BasilioPV this issue is related with https://github.com/OpenModelica/OpenModelica/issues/13260, Fmpy compiles with visual studio and i need to investigate this, it works fine from mingw

**Comment by BasilioPV** [comment]
@arun3688 Thanks for the response but  how can compile if "omc_config.h" is not inside the FMU? It is possible?

**Comment by arun3688** [comment]
@BasilioPV the issue should be fixed with this commit fbfa0ae502fae59dcb45ae44fa97c033fcee128f, i tested the above model and compile with fmpy and it works fine, Please test it from the latest nightly build and it should work

**Comment by arun3688** [comment]
@BasilioPV I am closing this issue since i have tested the complilation in fmpy, please reopen if you face issues

**Comment by BasilioPV** [comment]
@arun3688 Thanks, I will test it ASAP.

**Comment by arun3688** [comment]
can you attach your exported fmu, so i can check whether i can reproduce the issue, i tested for the above model

**Comment by BasilioPV** [comment]
[eee.zip](https://github.com/user-attachments/files/20106687/eee.zip)

**Comment by arun3688** [comment]
@BasilioPV i checked your fmu and the source files are not exported and you cannot compile the sources from fmpy, make sure in OMEdit , include source code options is checked 

![Image](https://github.com/user-attachments/assets/7903c6f3-1c99-438f-93fd-af73ed13df3e)

And then export the fmu and it should work fine

**Comment by BasilioPV** [comment]
@arun3688 I have exported with these settings and the result is:

<img width="953" alt="Image" src="https://github.com/user-attachments/assets/74da7337-e900-40ce-bb84-d7f80f93b143" />

in fact, "omc_config.h" file is not present into the FMU/sources

**Comment by BasilioPV** [comment]
Please find attached FMU:
[eee.zip](https://github.com/user-attachments/files/20109364/eee.zip)

**Comment by arun3688** [comment]
@BasilioPV After some debugging i found that certain files like "omc_config.h", "revision.h" which are needed for source code compilation are run time generated files and those are not required i guesss, but if you remove these two sources from `modeldescription.xml `

```
 <File name="simulation/solver/cvode_solver.c" />
 <File name="simulation/solver/sundials_error.c" />
```
fmpy source code compilation should work

**Comment by BasilioPV** [comment]
@arun3688 Now it compiles, but when executing:

<img width="1100" alt="Image" src="https://github.com/user-attachments/assets/4f4338e5-f74f-4878-8c76-35c2f7211085" />

**Comment by arun3688** [comment]
@BasilioPV It will not work because the cvode sources are not compiled and as of now it is not possible to export full source code of cvode as they have so many dependencies and also the headers files location in source code makes it difficult to place in appropriate places aligned with simulation, So source code compilation of covde solvers are not supported and they are statically linked in the cmake

**Comment by BasilioPV** [comment]
@arun3688 I understand. It will be planned to support CVODE compilation in the future?
