### ISSUE TITLE
Variables tab in plotting section with generic issues during re-simulations

### ISSUE THREAD

**Issue by MarcoRizz** [OpenModelica/OpenModelica#13338]
### Description
The Variables tab in plotting section don't work properly:

- When I change a parameter value and re-simulate, the results do not update as expected.
- Additionally, a variable has the editable square usually reserved for parameters.

### Steps to reproduce

1. Open OMedit and simulate model `test_index`:
```modelica
model test_index
  parameter Integer index(min = 1, max = 4) = 9;
  model internal_model
    parameter Integer index;
    constant Real array[4] = {2, 4, 6, 8};
    Real result;
  equation
    result = array[index];
  end internal_model;
  
  internal_model Model1(index = index);

end test_index;
```

2. Change the value of index to any other value.
3. Re-simulate the model without recompiling.

The value of Model1.result does not change based on the new index value.
If index violates its min and max constraints, only a warning is displayed, and the simulation continues.
Model1.result incorrectly shows an editable square, which is typically reserved for parameters.

### Expected behavior
1. The Model1.result value should update correctly when index is changed and the model is re-simulated.
2. An error should occur if index exceeds its min or max constraints.
3. The Model1.result field should not have an editable square.

### Screenshots
![image](https://github.com/user-attachments/assets/20685a06-a473-423e-9521-fed686fb7b92)

### Version and OS
 - OpenModelica v1.24.0-dev-168-g907b8bd1e8
 - OS: Windows 10

**Comment by casella** [comment]
@MarcoRizz mind trying with 1.24.2 or with the latest nightly build? This may have been fixed in the meantime.

**Comment by BasilioPV** [comment]
I have tested it on latest nightly build and the issue persists. In the meantime:

@MarcoRizz  "If index violates its min and max constraints, only a warning is displayed, and the simulation continues." This is the correct behaviour for "min/max", according to Modelica Specification. For error, you need to write an "assert"

**Comment by adeas31** [comment]
This is more of an issue of compiler than GUI. OMEdit is correctly reading the information. I don't know who is the right person to look into this issue, perhaps @kabdelhak 

> Model1.result incorrectly shows an editable square, which is typically reserved for parameters.

The variable is marked with `isValueChangeable = "true"` in the model_init.xml.

```XML
<ScalarVariable
    name = "Model1.result"
    valueReference = "1000"
    variability = "continuous" isDiscrete = "false"
    causality = "local" isValueChangeable = "true"
    alias = "noAlias"
    classIndex = "0" classType = "rAlg"
    isProtected = "false" hideResult = "" isEncrypted = "false" initNonlinear = "false"
    fileName = "M" startLine = "6" startColumn = "5" endLine = "6" endColumn = "16" fileWritable = "true">
    <Real fixed="true" useNominal="false" />
  </ScalarVariable>
```

**Comment by daveberto90** [comment]
I found a similar issue in 1.25 that was not present in 1.23. When I define a model with some Real variables (ex. X) and in the equation block I write some trivial equation of the type X=1 or other numbers, the variable value is no visibile in the variable window of the simulation Tab. The value is replaced by the editable square usually reserved for parameters.

**Comment by casella** [comment]
@adeas31 this should really be fixed:
```modelica
model TestX
  Real x = 1;
end TestX;
```
gives:

![Image](https://github.com/user-attachments/assets/42ce4745-332e-4eff-b5d7-a513ea757149)

You can even type values in the editable field, though this has obviously no consequences on the re-simulation

**Comment by adeas31** [comment]
@casella see https://github.com/OpenModelica/OpenModelica/issues/13338#issuecomment-2545782589

Unfortunately, I can't do anything about it in OMEdit.

**Comment by adrpo** [comment]
> [@casella](https://github.com/casella) see [#13338 (comment)](https://github.com/OpenModelica/OpenModelica/issues/13338#issuecomment-2545782589)
> 
> Unfortunately, I can't do anything about it in OMEdit.

I guess you could, but you would need to also look at the variability. If it is continuous then don't display the box.

**Comment by adeas31** [comment]
> > [@casella](https://github.com/casella) see [#13338 (comment)](https://github.com/OpenModelica/OpenModelica/issues/13338#issuecomment-2545782589)
> > Unfortunately, I can't do anything about it in OMEdit.
> 
> I guess you could, but you would need to also look at the variability. If it is continuous then don't display the box.

We should do this in the compiler and set the attribute `isValueChangeable` properly. As I understand the sole purpose of the attribute `isValueChangeable` is to provide information to OMEdit and it is not used anywhere else.

I believe setting this attribute properly in the compiler is a proper fix for this ticket instead of checking for variability in OMEdit.

**Comment by phannebohm** [comment]
Yes this should be fixed in the backend. There was a discussion in #12272 and I worked on this in #12311. The function `isChangeable` needs to be adapted. I will work on it.

**Comment by phannebohm** [comment]
> [@adeas31](https://github.com/adeas31) this should really be fixed:
> 
> ```modelica
> model TestX
>   Real x = 1;
> end TestX;
> ```
> 
> gives:
> 
> ![Image](https://github.com/user-attachments/assets/42ce4745-332e-4eff-b5d7-a513ea757149)
> 
> You can even type values in the editable field, though this has obviously no consequences on the re-simulation

For some reason the backend sets fixed=true for `x` and by the rules of `isChangeable` this allows changing the value after compilation. I don't really understand how `x` can be fixed because it does not have any start value. Will investigate further...

**Comment by casella** [comment]
Summary: 
- currently, it seems like a backend issue, not OMEdit
- for some reason, x gets fixed = true, but it shouldn't

@phannebohm will investigate after Easter.

**Comment by daveberto90** [comment]
Just an update from my side, because I found the same issue in version v1.23.1 and maybe this can helpful for you.
I reproduce the issue in a simple function and model.
I have a function like this:

![Image](https://github.com/user-attachments/assets/9b97ae17-455d-4a15-be8f-4037c673d98f)

and I built a model like this:

![Image](https://github.com/user-attachments/assets/a068c2fd-dfc9-41c4-84f5-70d203f15a09)

In the plotting tab this is what I have:

![Image](https://github.com/user-attachments/assets/ba9d1e81-0ad6-458b-8e85-c7e278fa09e4)

As a workaround, I make an assignment of x1 and x2 in an algorithm block in place of equation block like this:

![Image](https://github.com/user-attachments/assets/c32b8f20-d293-4173-a9fa-17567cfeb939)

This last seems working and the variable values are all visible in the plotting tab.
I played a little bit with this issue and I also found that using a function with just one output, I can use also the equation block to assign a value at x1 and x2 and make the output value visible.

**Comment by casella** [comment]
> [@phannebohm](https://github.com/phannebohm) will investigate after Easter.

@phannebohm do you think you can sort this out in the short term?

**Comment by casella** [comment]
@phannebohm last call, can we fix this by end of November for 1.26.0?

**Comment by phannebohm** [comment]
I don't know, I'll have a look on Monday.

**Comment by phannebohm** [comment]
I was able to find the cause why omc marks `x` as fixed in this model.

```modelica
model TestX
  Real x = 1;
end TestX;
```

It will be solved with #14691, which impacts about 30 models and I have to check those. Unfortunately Jenkins had a few issues so it's not merged yet.

**Comment by phannebohm** [comment]
For the following model, there are two issues

```modelica
model modeltest
  Real x1,x2,y1,y2;
protected
  function funtest
    input Real x1;
    input Real x2;
    output Real y1;
    output Real y2;
  algorithm
    y1 := x1 + x2;
    y2 := x1*x2;
  end funtest;
equation
  x1 = 2;
  x2 = 3;
  (y1, y2) = funtest(x1, x2);
end modeltest;
```

1. The variables `y1` and `y2` are for some reason made into parameters somewhere in the backend.
2. The equation `(y1, y2) = funtest(x1, x2);` is understood to be a _constant_ binding, so the "parameters" are marked as changeable. (Yes it is not really a binding, but when we see that stuff is constant we replace it everywhere in the model and put the assignment as binding so it can be removed from the system, or something along those lines.)

We can solve 2. by checking if the RHS is actually a literal, so for `modeltest` it would not be and so `y1` and `y2` will not be changeable, solving this issue at least.

I will need to investigate the cause for 1. further.

**Comment by casella** [comment]
>     1. The variables `y1` and `y2` are for some reason made into parameters somewhere in the backend.

That's not a bad idea. There's no point re-computing them at each time step. BTW we've had plans to do that systematically for years, see #8026.

>     2. The equation `(y1, y2) = funtest(x1, x2);` is understood to be a _constant_ binding, so the "parameters" are marked as changeable

I don't get this. `y1` and `y2` are bound to literal constants by equations. Why on Earth should they be changeable?

**Comment by phannebohm** [comment]
> > ```
> > 1. The variables `y1` and `y2` are for some reason made into parameters somewhere in the backend.
> > ```
> 
> That's not a bad idea.

On the contrary, this is a very bad idea if we want to be able to distinguish this model

```modelica
model NonChangeable
  Real y = 1;
end NonChangeable;
```

from this model

```modelica
model Changeable
  parameter Real y = 1;
end Changeable;
```

> There's no point re-computing them at each time step. BTW we've had plans to do that systematically for years, see [#8026](https://github.com/OpenModelica/OpenModelica/issues/8026).

Of course, but not by changing the variable kind to be parameter. We can remove the corresponding equations from the simulation system and only keep them in the initial system, that's enough.

> 
> > ```
> > 2. The equation `(y1, y2) = funtest(x1, x2);` is understood to be a _constant_ binding, so the "parameters" are marked as changeable
> > ```
> 
> I don't get this. `y1` and `y2` are bound to literal constants by equations.

They are not, unless you evaluate the function call.

> Why on Earth should they be changeable?

If they are parameters with constant bindings then our policy says they should. Or should they not?

**Comment by casella** [comment]
> On the contrary, this is a very bad idea if we want to be able to distinguish...

Yes. What I meant was that

```modelica
model NonChangeable
  Real y = 1;
end NonChangeable;
```

should be simulated as 

```modelica
model NonChangeable2
  final parameter Real y = 1;
end NonChangeable2;
```

**Comment by casella** [comment]
> Of course, but not by changing the variable kind to be parameter. We can remove the corresponding equations from the simulation system and only keep them in the initial system, that's enough.

Sounds good. That's the same as having them as final parameters, right?

**Comment by casella** [comment]
> > I don't get this. `y1` and `y2` are bound to literal constants by equations.
> 
> They are not, unless you evaluate the function call.

Sorry, I still don't get it. `y1` and `y2` depend on `x1` and `x2` via a regular equation, that cannot be changed at run time. In turn,  `x1` and `x2` depend on literal constants via regular equations, that cannot be changed at run time. I don't see anything changeable here.

They could be considered as **final** parameters, see above.

Do I miss something?

**Comment by phannebohm** [comment]
> They could be considered as **final** parameters, see above.

Yes indeed that should work nicely. I'm not sure I like that in general, but for the OB it's more than good enough. Thanks!

**Comment by phannebohm** [comment]
> ### Expected behavior
> 
>    1. The Model1.result value should update correctly when index is changed and the model is re-simulated.

I suppose `index` affects array indexing and therefore is marked as structural. I'm not sure if we can support changing `index` after compilation but I did not investigate yet. @casella should we try to do that with the OB?
 
>    2. An error should occur if index exceeds its min or max constraints.

The [MLS section 4.9.2](https://specification.modelica.org/master/MLS.pdf#subsection.4.9.2) states that the type `Integer` does indeed have an assert of this form

```modelica
assert(min <= ⟨value⟩ and ⟨value⟩ <= max, "Variable value out of limit");
```

and [section 8.3.7](https://specification.modelica.org/master/MLS.pdf#subsection.8.3.7) says

```modelica
assert(condition, message); // Uses level = AssertionLevel.error
```

So the default is used, which is `AssertionLevel.error`. Altogether that means an error should indeed occur, right?
 
>    3. The Model1.result field should not have an editable square.

This is fixed now with #14691 at least for `Model1.result`. What should happen for `index`? If it is structural then we should set `isValueChangeable` to `false`, ohterwise we should fix 1. and keep `isValueChangeable = true`.

**Comment by casella** [comment]
> I suppose `index` affects array indexing and therefore is marked as structural. I'm not sure if we can support changing `index` after compilation but I did not investigate yet. [@casella](https://github.com/casella) should we try to do that with the OB?

I'm not sure. It would be nice to have, but I guess this would make structural analysis really, really hard.

**Comment by casella** [comment]
> So the default is used, which is AssertionLevel.error. Altogether that means an error should indeed occur, right?

I guess so. With Integers, this should be safe. With Reals, this could be problematic, see e.g. #10477, so I would stick to a warning.

**Comment by casella** [comment]
Update for the 1.26.0 release:

1. Most of the issues mentioned in this ticket were fixed by PRs #12294, #12311, and #14691 
2. The original issue reported in the ticket (model [`test_index`](https://github.com/OpenModelica/OpenModelica/issues/13338#issue-2715323002)) are resolved, there are no longer any input fields with potentially problematic effects in the variable browser

<img width="418" height="216" alt="Image" src="https://github.com/user-attachments/assets/b0f99406-c896-467e-a74a-04a3d11a24dd" />

3. As [already mentioned](https://github.com/OpenModelica/OpenModelica/issues/13338#issuecomment-3571484443), the issue with model TestX is also fixed now

<img width="404" height="82" alt="Image" src="https://github.com/user-attachments/assets/c432f226-f8e4-4b58-8e8d-3bd1a21dfd3e" />

So, I would consider this issue closed. There are still some [pending issues](https://github.com/OpenModelica/OpenModelica/issues/13338#issuecomment-3571541654) with model [`modeltest`](https://github.com/OpenModelica/OpenModelica/issues/13338#issuecomment-3571541654), regarding variables that are turned into **modifiable** parameters by the backend, instead of **final** parameters. I'll open a separate ticket about that.

@MarcoRizz thanks again for reporting. If you still see some issues with this topic, please open a new specific ticket. Thanks!
