### ISSUE TITLE
Split if-equations conveniently in the NB

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#13380]
Related to #11010.

Consider this MWE
```modelica
model TestCoupledIfEquations
  Real v1, v2, v3, v4, v5;
equation
if time >= 1 then
  v1 = time*3;
  v2 = time^4 -1;
  v3 = 3 - time^3;
  v4^2 + v5^2 = 1 + time;
  v4^3 - v5^3 = 0;
else
  v3 = 6 - time^3;
  v1 = time*3 +2;
  v2 = time^3 + 1;
  v4^2 + v5^2 = 1 + time;
  v4^3 - 2*v5^3 = 0;
end if;
end TestCoupledIfEquations;
```
For the best robustness and efficiency, the equations for v1, v2, and v3 should be matched in a smart way, so they can be solved explicitly:
```modelica
v1 = if time >= 1 then time*3 else time*3+2;
v2 = if time >= 1 then time^4 -1 else time^3+1;
v3 = if time >= 1 then 3 - time^3 else 6 - time^3;
```
Using v1.25.0-dev-233-gb52eb46d5b, which includes PRs #13370 and #13372, with `--newBackend`, I'm getting this weird solution in the Declarative Debugger:
![immagine](https://github.com/user-attachments/assets/696ed6b5-ff77-4bf7-9425-b4bcf6e2d626)
Is it a problem with the debugger rendering, or is there something wrong in the actual backend transformations?

**Comment by phannebohm** [comment]
With `--newBackend` and `-d=dumpSimCode` I can see that the system is transformed into the following (I removed some clutter from the dump to make it more readable):
```modelica
$TEV_0 := time >= 1.0;
if $TEV_0 then
  v1 := 3.0 * time;
else
  v1 := 2.0 + 3.0 * time;
end if;
if $TEV_0 then
  v2 := (-1.0) + time ^ 4.0;
else
  v2 := 1.0 + time ^ 3.0;
end if;
if $TEV_0 then
  v3 := 3.0 - time ^ 3.0;
else
  v3 := 6.0 - time ^ 3.0;
end if;
0 = if $TEV_0 then -(v4 ^ 3.0 - v5 ^ 3.0) else -(v4 ^ 3.0 - 2.0 * v5 ^ 3.0);
0 = if $TEV_0 then 1.0 + time - (v4 ^ 2.0 + v5 ^ 2.0) else 1.0 + time - (v4 ^ 2.0 + v5 ^ 2.0);
```

I suppose the generated C code would be simpler and also the debugger would get it right, if the if-equations were simple equations with if-expressions, like you suggest. I'll implement that next.

Unfortunately for some other reason simulation execution fails for this model. A segfault occurs while evaluating the residual function at initialization. I will have to look into that.

**Comment by casella** [comment]
But they why do you get that weird representation in the declarative debugger?

**Comment by phannebohm** [comment]
The if-equation is an equation, but the bodies of each branch of that if-equation are also equations. So
```modelica
if b then
  x = 1;
else
  x = 2;
end if;
```
is 3 equations internally. Perhaps that has something to do with the weird representation. But I don't know how the debugger works so I don't yet know how to fix that.

I know eventually we need to fix it, but these things are low priority at the moment.

**Comment by casella** [comment]
OK.

What is really weird is that the two alternative assignment show up as if they are both executed. This is very confusing and should be improved.

@sjoelund, @adrpo, maybe you could have a look and give some hints to @phannebohm as to how to improve the debugger's output?

**Comment by phannebohm** [comment]
With #13419 the NB now tries to simplify if-equations
```modelica
if b then
  x = 1;
else
  x = 2;
end if;
```
to plain equations with if expressions
```modelica
x = if b then 1 else 2;
```
This works iff the lhs is always identical. This should solve the displaying issue with the debugger.

**Comment by casella** [comment]
Good feature, but the unclear display issue remain in the case there is no identical lhs

**Comment by phannebohm** [comment]
True, but I think in that case the if-equation is always part of an algebraic loop and those equations are always brought into residual form and ultimately become plain equations with if-expressions, as seen in the [example I wrote earlier](https://github.com/OpenModelica/OpenModelica/issues/13380#issuecomment-2536170086).

**Comment by casella** [comment]
The important point (possibly also for #11010?) if there is no common LHS is that the if-equations are split for the sake of the BLT decomposition, avoiding one big strong component encompassing all of them.

Here is an MWE for that:
```modelica
model TestCoupledIfEquationsImplicit
  Real v1, v2, v3, v4, v5;
equation
if time >= 1 then
  v1  = time*3;
  v2 = time^4 -1;
  v3 = 3 - time^3;
  v4^2 + v5^2 = 1 + time;
  v4^3 - v5^3 = 0;
else
  v3 + 1e-6*sin(v3) = 6 - time^3;
  v1 + 1e-6*sin(v1) = time*3 +2;
  v2 + 1e-6*sin(v2) = time^3 + 1;
  v4^2 + v5^2 = 1 + time;
  v4^3 - 2*v5^3 = 0;
end if;
end TestCoupledIfEquationsImplicit;
```
As I can see, the NB still gives you
![immagine](https://github.com/user-attachments/assets/1cecc624-b6cf-4cba-a30b-9d18fb6ab528)

**Comment by phannebohm** [comment]
> Unfortunately for some other reason simulation execution fails for this model. A segfault occurs while evaluating the residual function at initialization. I will have to look into that.

@linuslangenkamp is working on that now.

**Comment by phannebohm** [comment]
Splitting if-equations with arbitrary expressions optimally is a different story. That should be done after BLT on individual SCCs, perhaps best as a first step of Tearing. We would need to make sure the number of analysis steps doesn't blow up when we have many if-equations in one SCC. I guess this gives an opportunity for an interesting paper.

**Comment by casella** [comment]
Now we get the expected behaviour with the TestCoupledIfEquations:

![Image](https://github.com/user-attachments/assets/8c62117d-3660-4aa1-b4c2-e93c8c9728cb)

@linuslangenkamp, you may want to add that to the testsuite, just in case.

I'll open a follow-up ticket for the implicit case.

**Comment by casella** [comment]
Follow-up ticket: #13487.
