### ISSUE TITLE
OMSens has issues with some characters in paths

### ISSUE THREAD

**Issue by adrpo** [OpenModelica/OpenModelica#13451]
### Description

Spaces or & in path cause issues.

### Steps to Reproduce

See: https://stackoverflow.com/questions/79345565/performing-sensitivity-analysis-of-model

**Comment by adrpo** [comment]
I guess we need to escape `&` in the path.

**Comment by TobiasR42** [comment]
Even with changing the folder name to be without & I get an error in the current version of OMEdit.
Attached the error file.

[omc_run_log.txt](https://github.com/user-attachments/files/18395606/omc_run_log.txt)

**Comment by adrpo** [comment]
I need more info. It seems the model you are trying to run the sensitivity on is not loaded correctly.
How do you do the sensitivity analysis? In OMEdit with the model opened you click on the top menu?

**Comment by TobiasR42** [comment]
Yes, i usded the OMEdit application. Here is my model:

`model Reactor_Jacketed_IHC_V3_sensitivity_Analysis
 
  // REAKTORPARAMETER
  Real Vreactor = ri_reactor^2*3.142*h_reactor "Reaktorvolumen";
  parameter Real Vfluid = 6.5e-3 "Inneres Flüssigkeitsfüllvolumen";
  Real level = Vfluid/Vreactor "reactor level";
  parameter Real N = 200/60 "Rührerdrehzahl";
  Real Vdeckel = 3.142*ri_jacket^2*ddeckel;
  parameter Real d_reactor = 8.5e-3 "Wandstärke Reaktorwand";
  parameter Real ddeckel = 4.5e-2 "Wandstärke Reaktordeckel";
  parameter Real dboden = 4e-2 "Wandstärke Reaktorboden";
  parameter Real d_jacket = 2e-3 "Dicke Blech Heizmantel";
  parameter Real ri_reactor = 101e-3 "Rührkessel Innenradius";
  parameter Real ra_reactor = 125e-3 "Außenradius Reaktor insgesamt";
  parameter Real h_reactor = 0.38 "Rührkessel Höhe";
  parameter Real NumberofSpiralsJacket = 7;
  Real VJacket = h_reactor*(ra_reactor^2 - ri_jacket^2)*3.142 "Reactor Jacket volume";
  parameter Real lPipes = 6.5 "pipe lenght Jacket";
  parameter Real diPipes = 3e-2 "inner diameter Jacket Pipes";
  parameter Real dPipes = 3e-3 "thickness pipe wall Jacket";
  Real VPipes = (diPipes/2)^2*3.142*lPipes "Volumen Leitungen Jacket";
  Real rhoSS = 7800 "Dichte Stainless Steel";
  Real epsilonSS = 0.8 "Näherungsweiser Emissionsgrad Edelstahl";
  // Parameter Heizmantel
  parameter Real QdotIHC = 0 "Leistung IHC";
  parameter Real QdotHeating = 1000 "Maximale Heizleistung Jacket";
  parameter Real QdotCooling = 0 "Maximale Kühlleistung Jacket";
  Real Qdot(start = 0, fixed = false);
  Real QdotDeckel(start = 0, fixed = false) "Wärmestrom in DEkcel hinein";
  Real QdotVerlustDeckel(start = 0, fixed = false);
  Real QdotVerlustBoden(start = 0, fixed = false);
  Real QdotVerlustPipes(start = 0, fixed = false) "Heatloss through pipes of heating circut";
  Real QdotVerlustJacket(start = 0, fixed = false) "Heatloss through jacket of heating circut";
  parameter Real Vdotjacket = 50/60/1000 "Förderstrom der Pumpe im Mantelkreislauf";
  // TEMPERATURPARAMETER
  parameter Real Tamb = 273.15 + 20 "Umgebungstemperatur";
  Real Treactor(start = Tamb, fixed = false);
  Real Tdeckel(start = Tamb, fixed = false);
  Real Tjacket(start = Tamb, fixed = false);
  // dimensionslose Zahlen
  Real NuJacket = if (ReJacket < 40000) then 0.193*ReJacket^0.618*PrJacket^0.31 else 0.027*ReJacket^0.805*PrJacket^0.31;
  Real ReJacket = ((Vdotjacket/CrosssectionJacket)*(4*CrosssectionJacket/2*CrosssectionHightJacket + 2*CrosssectionWidthJacket)*rhoJacketMedium)/etaJacketMedium "approximate Reynoldsnumber needed for good heat transfer= 50000";
  Real PrJacket = etaJacketMedium/rhoJacketMedium/aJacketMedium;
  Real Nu = C*Re^m*Pr^n "Nusseltzahl, zur Berechnung von alphaFlüssigphase in Rührkesseln";
  Real Re = N*Dblatt^2/(etaFluessigphase/rhoFluessigphase) "Reynoldszahl, Gültigkeit: 300< Re <750000";
  Real Pr = etaFluessigphase/rhoFluessigphase/aFluessigphase "Prandtlzahl, Gültigkeit: 2,2<Pr<2500";
  /* Modelica.Blocks.Interfaces.RealInput stirrer_rotations annotation(
                      Placement(visible = true, transformation(origin = {10, 82}, extent = {{-20, -20}, {20, 20}}, rotation = -90), iconTransformation(origin = {2, 84}, extent = {{-20, -20}, {20, 20}}, rotation = -90)));
                    Modelica.Fluid.Interfaces.HeatPorts_a heatPorts_a annotation(
                      Placement(visible = true, transformation(origin = {60, -10}, extent = {{-10, -10}, {10, 10}}, rotation = 0), iconTransformation(origin = {60, -4}, extent = {{-40, -10}, {40, 10}}, rotation = -90)));
                    */
protected
  // ZWISCHENBERECHNUNGEN, nicht im Plot Fenster zu sehen
  //Maße
  parameter Real ri_jacket = ri_reactor + d_reactor "Innenradius Jacket";
  Real Dblatt = 2*ri_reactor*0.8;
  Real CrosssectionWidthJacket = ra_reactor - ri_jacket "width of space for coolant flow";
  Real CrosssectionHightJacket = h_reactor/NumberofSpiralsJacket;
  Real CrosssectionJacket = CrosssectionWidthJacket*CrosssectionHightJacket "Crosssection of coolant flow";
  //Dimensionslose Zahlen
  Real C = 0.36;
  Real m = 0.66;
  Real n = 0.33;
  // STOFFPARAMETER
  Real etaFluessigphase = -2e-6*(Treactor - Tamb) + 3.12e-4 "dynamische Viskosität Flüssigkeit (Hexan)";
  Real rhoFluessigphase = 660 - ((Treactor - Tamb)*0.85) "Dichte Hexan";
  parameter Real cfluidphase = 2400 "Wärmekapazität Flüssigkeit (Hexan)";
  Real cSS = 470 "Wäremkapazität Stainless Steel";
  Real lambdaSS = 12.5/3600*4184 "Wärmeleitfähigkeit Stainless steel";
  parameter Real lambdaGasphase = 0.0239/3600*4184 "Wärmeleitfähigkeit Gasphase (Stickstoff)";
  parameter Real lambdaFluessigphase = 0.143 "Wärmeleitfähigkeit Flüssigphase (Hexan)";
  parameter Real lambdaJacket = 600 "Wärmeleitfähigkeit Wasser";
  Real aFluessigphase = lambdaFluessigphase/rhoFluessigphase/cfluidphase "Temperaturleitzahl Flüssigphase (Hexan)";
  parameter Real rhoJacketMedium = 1001 "Wasser";
  parameter Real etaJacketMedium = 0.5e-3 "Wasser";
  parameter Real aJacketMedium = 0.13e-6 "Wasser";
  parameter Real cJacketMedium = 4186 "Wasser";
  // Wäremströme
  Real Q(start = 0, fixed = false);
  Real QDeckel(start = 0, fixed = false);
  Real QHeating(start = 0, fixed = false);
  Real QCooling(start = 0, fixed = false);
  Real QIHC(start = 0, fixed = false);
  Real QVerlustDeckel(start = 0, fixed = false);
  Real QVerlustBoden(start = 0, fixed = false);
  Real QVerlustPipes(start = 0, fixed = false);
  Real QVerlustJacket(start = 0, fixed = false);
  Real alphaFluessigphase = Nu*lambdaFluessigphase/(2*ri_reactor);
  Real alphaJacket = NuJacket*lambdaJacket/(h_reactor/NumberofSpiralsJacket);
  Real alphaGasphase = lambdaGasphase/20e-6 "Schätzwert für Grenzschichtdicke eingesetzt; Formel:[S. 202 Brötz]";
equation
  if time > 0 then
    assert(Re > 300 and Re < 750000, "Reynolds number inside reactor out of range", level = AssertionLevel.warning);
    assert(Pr > 2.2 and Pr < 2500, "Prandtls number inside reactor out of range", level = AssertionLevel.warning);
    assert(ReJacket > 50000, "Reynoldsnumber in Jacket too low", level = AssertionLevel.warning);
  end if;
  assert(Tjacket < 100 + 273 and Tjacket > 253, "Heating Circiut Temperature is out of range", level = AssertionLevel.error);
// Wärmememengen
  der(Q) = Qdot;
  der(QDeckel) = QdotDeckel;
  der(QVerlustDeckel) = QdotVerlustDeckel;
  der(QVerlustBoden) = QdotVerlustBoden;
  der(QIHC) = QdotIHC;
  der(QHeating) = QdotHeating;
  der(QCooling) = QdotCooling;
  der(QVerlustPipes) = QdotVerlustPipes;
  der(QVerlustJacket) = QdotVerlustJacket;
// Temperatures
  der(Tjacket) = der(QHeating - QVerlustPipes - QVerlustJacket - QCooling - Q)/(cJacketMedium*rhoJacketMedium*(VJacket + VPipes));
  der(Treactor) = der(Q + QIHC - QDeckel - QVerlustBoden)/(cfluidphase*Vfluid*rhoFluessigphase);
  der(Tdeckel) = der(QDeckel - QVerlustDeckel)/(cSS*Vdeckel*rhoSS);
// Wärmeströme;	Doppelmantelwärmestrom von Außen nach Innen
//  der(Q) = -PRT.Functions.HeatingCircuitToHeatFlow(rho = rhoJacketMedium, eta = etaJacketMedium, a = aJacketMedium, alphari = alphaFluessigphase, Ti = Treactor, Ta = Tjacket, VJacket = VJacket + VPipes, lPipes = lPipes, diPipes = diPipes, tPipes = dPipes, lambda = lambdaSS, Re = ReJacket);
  der(Q) = -Functions.DoppelmantelWaermestrom(Ti = Treactor, Ta = Tjacket, l = h_reactor, ra = ri_jacket, ri = ri_reactor, lambda = lambdaSS, alphari = alphaFluessigphase, alphara = alphaJacket);
// Wärmestrom in den Deckel
  der(QDeckel) = Functions.AxialerWaermestrom(lambda = lambdaSS, alpha = alphaGasphase, d = ddeckel, ra = ri_reactor, Ti = Treactor, Ta = Tdeckel);
// Verlustwärmestrom aus dem Deckel
  der(QVerlustDeckel) = Functions.FreeConvectionToAirLaminar(A = ra_reactor^2*3.142, T = Tdeckel, Tamb = Tamb, l = ddeckel) + Functions.Heatradiation(A = ra_reactor^2*3.142, T = Tdeckel, Tamb = Tamb, epsilon = epsilonSS);
// Verlustwärmestrom in den Boden
  der(QVerlustBoden) = Functions.FreeConvectionToAirLaminar(A = ra_reactor^2*3.142, T = Treactor, Tamb = Tamb, l = dboden) + Functions.Heatradiation(A = ra_reactor^2*3.142, T = Treactor, Tamb = Tamb, epsilon = epsilonSS);
// Verlust Wärmestrom Piping:
  der(QVerlustPipes) = +Functions.FreeConvectionToAirLaminar(A = diPipes*3.142*lPipes, T = Tjacket, Tamb = Tamb, l = diPipes) + Functions.Heatradiation(A = diPipes*3.142*lPipes, T = Tjacket, Tamb = Tamb, epsilon = epsilonSS);
// Verlustwärmestrom Jacket
  der(QVerlustJacket) = Functions.FreeConvectionToAirLaminar(A = 2*ra_reactor*h_reactor*3.142, T = Tjacket, Tamb = Tamb, l = ddeckel) + Functions.Heatradiation(A = 2*ra_reactor*h_reactor*3.142, T = Tjacket, Tamb = Tamb, epsilon = epsilonSS);
  annotation(
    experiment(StartTime = 0, StopTime = 3000, Tolerance = 1e-6),
    Diagram,
    Documentation(info = "<html><head></head><body><p><span style=\"font-family: 'MS Shell Dlg 2';\">Dieses Modell ermöglicht die Temperatursimulation in einem Rührbehälter mit einer Flüssigkeit.</span></p><div class=\"htmlDoc\" style=\"font-family: 'MS Shell Dlg 2';\"><div>Die Temperatur des Mantelmediums wird mithilfe der Heiz- und Kühlleistung berechnet.</div><div>Damit werden die Wärmeströme und die resultierenden Temperaturen ausgerechnet.</div><div><br></div><div><span style=\"font-size: 12px;\">Zusätzlich ist die Möglichkeit gegeben, eine IHC- Leistung vorzugeben, die resultierende Temperaturdifferenz zwischen Mantel und Innentemperatur kann mit dieser Simulation gezeigt werden.</span></div><div><br></div><div>Der Einfluss durch Wärmespeicherung im Deckel ist ebenfalls eingerechnet.</div></div><div class=\"textDoc\"><p style=\"font-family: 'Courier New'; font-size: 12px;\"></p></div><p style=\"font-size: 12px;\"><br></p></body></html>", revisions = "<html><head></head><body><p style=\"font-size: 12px;\"><b style=\"font-family: 'MS Shell Dlg 2';\">V2:&nbsp;</b></p><div class=\"htmlDoc\" style=\"font-family: 'MS Shell Dlg 2';\"><div><div>- Vereinfachung der Bezeichnung</div></div></div><span style=\"font-family: 'MS Shell Dlg 2';\">- Reduzierung der Parameteranzahl</span><div><span style=\"font-family: 'MS Shell Dlg 2';\"><br></span></div><div><span style=\"font-family: 'MS Shell Dlg 2';\"><b>V3:</b></span></div><div><span style=\"font-family: 'MS Shell Dlg 2';\"><br></span></div><div><span style=\"font-family: 'MS Shell Dlg 2';\">- Wärmeverlustrechnungen verbessert</span></div><div><span style=\"font-family: 'MS Shell Dlg 2';\">- Protected Variables und Parameter eingeführt</span></div></body></html>"),
    Icon);
end Reactor_Jacketed_IHC_V3_sensitivity_Analysis;
`

**Comment by adrpo** [comment]
Thank you for the model but is missing some parts such as Functions. 
Is the model split in several files and packages? I am a bit unsure if we support such a scenario, I think we only load one file with the top level model. If you have dependencies then you need to provide them as libraries and add them to the model as uses annotations.

Do you open this model: "Reactor_Jacketed_IHC_V3_sensitivity_Analysis" in the Modeling view and then you go to Sensitivity Analysis? 

Does the model simulates in OMEdit otherwise? 

Can you attach here a zip of the directory:
%TEMP%\OpenModelica\OMEdit\omsens_results\indiv_results\

**Comment by TobiasR42** [comment]
You are right ofc. It silumates in OMedit. Its a model with seperated functions. It silumates in OMedit though. Here is the directory of the last run:
[2025-01-13.zip](https://github.com/user-attachments/files/18455367/2025-01-13.zip)

full functions code (its organized into packages but i think i can upload that file format here): 
`package Functions
  function DoppelmantelWaermestrom "Describes the Heatflow through a pipe wall with given Temperatures"
    input Real lambda "Thermal conductivity coefficient";
    input Real alphari "inner radius Heat transfer coefficient";
    input Real alphara "outer radius Heat transfer coefficient";
    input Real Ti;
    input Real Ta;
    input Real ra;
    input Real ri;
    input Real l;
    output Real Q_dot;
  protected
  
  algorithm
    Q_dot := 1/(1/(alphari*2*3.142*ri*l) + log(ra/ri)/(lambda*2*3.142*l) + 1/(alphara*2*3.142*ra*l))*(Ti - Ta);
  end DoppelmantelWaermestrom;

  function AxialerWaermestrom
    input Real lambda;
    input Real alpha;
    input Real Ti;
    input Real Ta;
    input Real ra;
    input Real d;
    output Real Q_dot;
  protected
    Real A = ra^2*0.5*3.142;
  algorithm
    Q_dot := 1/(1/(alpha*A) + d/(lambda*A) + 1/(alpha*A))*(Ti - Ta);
  end AxialerWaermestrom;

  function Heatradiation
    import Modelica.Constants;
    input Real A "Fläche Körper";
    input Real T "Temperatur Körper";
    input Real Tamb "Temperatur Umgebung";
    input Real epsilon "Emmisionsgrad";
    output Real Qdot "Waermestrom";
  protected
    constant Real sigma(final unit = "W/(m2.K4)") = 5.670367e-8 "Stefan Boltzmann Konstante";
  algorithm
    Qdot := epsilon*sigma*A*(T^4 - Tamb^4);
  end Heatradiation;

  function ReynoldszahlAllgemein
    input Real rho "Dichte Fluid";
    input Real v "Fließgeschwindigkeit Fluid";
    input Real l "Characteristische Länge";
    input Real eta "Dynamische Viskosität";
    output Real Re;
  algorithm
    Re := rho*v*l/eta;
  end ReynoldszahlAllgemein;

  function ReynoldszahVierkantrohr
    input Real rho "Dichte Fluid";
    input Real v "Fließgeschwindigkeit Fluid";
    input Real l "Characteristische Länge";
    input Real eta "Dynamische Viskosität";
    output Real Re;
  algorithm
    Re := rho*v*l/eta;
  end ReynoldszahVierkantrohr;

  function FreeConvectionToAirLaminar
    input Real T "Higher Temperature";
    input Real Tamb;
    input Real A "Area thats convecting";
    input Real l "charakteristische Länge";
    output Real QdotFreeConvection "Free Convection Heatflow";
  protected
    /// Free convection to air Quelle: Brötz Seite 207
    Real Pr = 15e-6/20.3e-6 "Prandtlnumber";
    Real Gr = l^3*9.81*3.67e-3*(T - Tamb + 0.01)/(15e-6)^2;
    Real Nu = 0.55*(Gr*Pr)^0.25 "Nusseltnumber for Gr*Pr 10000 - 500000";
    Real alpha = Nu/l*0.0262 "Heat transition number air";
  algorithm
    assert(Nu > 1000 and Nu < 3.5e7, "Nusselt Number Convection out of range", level = AssertionLevel.warning);
    QdotFreeConvection := alpha*A*(T - Tamb);
  end FreeConvectionToAirLaminar;

  function HeatCapacity
  
  input Real V "Volumen des Materials";
  input Real cp "Specific Heat Capacity";
  input Real rho "density of Material";
  output Real Cp "Heat capacity";
  
  algorithm

  Cp := V * rho * cp;
  
  end HeatCapacity;
end Functions;
`

**Comment by adrpo** [comment]
Thanks, I will see if I can reproduce the issue on my computer.

**Comment by adrpo** [comment]
Sorry for the slow reply, I have been busy with a lot of other stuff.

As we have the stupid limitation to have just one file, I merged your Function package with the model and then you can run some analysis: [Reactor_Jacketed_IHC_V3_sensitivity_Analysis.zip](https://github.com/user-attachments/files/18610041/Reactor_Jacketed_IHC_V3_sensitivity_Analysis.zip)

It seem OMSens is currently quite a bit stupid so it lists all the parameters (even those which cannot be changed) and variables (even those protected) which will make the analysis fail if you keep them selected when running the sweep.

What we need to do is to build the executable, see which parameters have isValueChangeable and only list those.
We should also see which functions and parameters are protected and remove them from the list.

If you are careful which parameters to perturb and which variables to watch, the analysis will work, but do not keep all of them selected as that will fail! I will try to fix the issues in the near future to make OMSens more usable.

See in this python log which variable should not be selected:
[python_log.txt](https://github.com/user-attachments/files/18610068/python_log.txt)
Also, see in this xml file which parameter should not be selected (isValueChangeable="false"):
[Reactor_Jacketed_IHC_V3_sensitivity_Analysis_init.zip](https://github.com/user-attachments/files/18610085/Reactor_Jacketed_IHC_V3_sensitivity_Analysis_init.zip)
Currently only:

```xml
<ScalarVariable name = "ri_jacket" causality = "calculatedParameter" isValueChangeable = "false" />
```

**Comment by TobiasR42** [comment]
I still cannot replicate the result your getting. I did what you described though. Hree is my error file:

![Image](https://github.com/user-attachments/assets/a8236fe6-5e58-49f1-8765-f22c859541e7)

**Comment by casella** [comment]
@linuslangenkamp has restarted work on optimization and optimal control in OMC. Stay tuned.
