### ISSUE TITLE
[NF] operator is DIV() instead of DIV_EW()

### ISSUE THREAD

**Issue by kabdelhak** [OpenModelica/OpenModelica#13618]
### Description

When creating an element wise division, the operator used is still the `DIV()` operator instead of the `DIV_EW()`.

### Steps to Reproduce
Consider following MWE:
```
model Mix
  Real[2] y, x;
equation
  x = y*time;
  y = x./{1.0,2.0};
end Mix;
```
running this with `--newBackend` leads to 
```
Error: Internal error NFCeval.evalBinaryPow failed to evaluate ‘{1.0, 2.0} ^ 2.0‘
```
This happens due to this being an algebraic loop, which is differentiated for solvability analysis. The operator `^` should be element-wise too, but the backend uses the kind from the one differentiated, which is the division and therefore does not create the correct element-wise power operator.

### Expected Behavior

The operator should be element wise.

**Comment by kabdelhak** [comment]
I do have a workaround for this specific case, but it could lead to errors in other places. If there is nothing speaking against it i would rather have the correct operator.

**Comment by perost** [comment]
This is done for the sake of simplicity since `/` is also element-wise, the only difference is that `/` only accept scalars as the second operand. But I guess using `/` is actually wrong, it should be `./` if we want to use a single operator since all `/` can be represented as `./` but not the opposite.

But using `./` everywhere feels a bit weird, so maybe we should just keep the element-wiseness for division. It's not really a big deal.

**Comment by kabdelhak** [comment]
> This is done for the sake of simplicity since `/` is also element-wise, the only difference is that `/` only accept scalars as the second operand. 

In this case the second operand is an array though. So that enforces `./`?

> But using `./` everywhere feels a bit weird, so maybe we should just keep the element-wiseness for division. It's not really a big deal.

I agree we should keep `/` for scalar operations.

**Comment by perost** [comment]
Fixed with #13620. We now keep `./` for the `array ./ array` case, but `scalar ./ scalar` is still changed to `scalar / scalar` since it doesn't really matter. The `scalar ./ array` and `array ./ scalar` cases use special operators just like before.

**Comment by kabdelhak** [comment]
Thanks for the quick fix! it seems like the backend still does not parse it correctly but i will fix that :)

**Comment by perost** [comment]
#13620 caused a lot of regressions, so for now I decided to revert it (#13631).

I looked into what the NB is doing and noticed that the issue isn't just with `DIV` but more general. `NFOperator.classify` will classify `ADD`, `SUB`, etc, as `SCALAR`, but these operators are also used for array operations so the classification strips some information.

A possible fix would be to add an `ARRAY` classification and check the type of the operator to decide which one to use. Then we can generate the correct operators for the `scalar op array` and `array op scalar` cases.

Another possibility would be to rework the operators completely as we briefly discusses on Slack and get rid of all the special operators, but that would of course be a lot more work.

**Comment by phannebohm** [comment]
The original MWE `Mix` simulates successfully now because the division is converted to multiplication:

```modelica
y = x./{1.0,2.0}  -->  0 = {1.0, 0.5} * x .- y
```

However there seem to be other cases where the NB still fails, see [this model](https://libraries.openmodelica.org/branches/newInst-newBackend/PowerSystems_latest/files/PowerSystems_latest_PowerSystems.Examples.Wind.WindFarm.err):

```
[/path/to/OpenModelica/OMCompiler/Compiler/NFFrontEnd/NFCeval.mo:1294:9-1294:67:writable]
Error: Internal error NFCeval.evalBinaryPow failed to evaluate ‘{690.0, 15000.0} ^ 2.0‘
```

I will investigate where that comes from.
