### ISSUE TITLE
Error while running FMU exporte from OpenModelica: Attempt to allocate an unusually large memory.

### ISSUE THREAD

**Issue by tinoetzold** [OpenModelica/OpenModelica#13905]
## Description

When exporting Buildings.Fluid.Geothermal.Borefields.Examples.RectangularBorefield as FMU, the FMU fails when calling it. The following error message occurs: **"Attempt to allocate an unusually large memory. The memory management does not seem to be working as intended. Please create an issue on https://github.com/OpenModelica/OpenModelica/issues."**

In the past, this issue could not be detected since the FMU-export was not working due to missing Lapack-Library dependencies in OpenModelica. This bug regarding failing FMU-Export has been solved by the OpenModelica-Team. The BugFix is available in the OpenModelica Nightly Builds later than 2025-04-30. Please see the folloiwing Issue-Report for more details:

https://github.com/OpenModelica/OpenModelica/issues/13639

## Steps to Reproduce

1. Install OpenModelica Nigthly Build (later than 2025-04-30)

2. Create mos-file for FMU

```
getVersion(); getErrorString();
loadModel(Modelica,{"4.0"}); getErrorString();
loadModel(Buildings,{"12.0"}); getErrorString();
buildModelFMU(Buildings.Fluid.Geothermal.Borefields.Examples.RectangularBorefield,
                version="2.0",
                fmuType="me_cs",
                fileNamePrefix="RectangularBorefield_1.26dev");getErrorString();
```

3. Create FMU from mos-file with omc from nightly build:

```
PS C:\Users\ETZOLD\git\Modelica_Waermenetze\test\create_fmu> C:\Users\ETZOLD\Programs\OpenModelica_1.26.0dev\bin\omc.exe .\Script_CompileFMU.mos
"OpenModelica v1.26.0-dev-98-gb32172a97f (64-bit)"
""
true
""
true
""
"C:/Users/ETZOLD/git/Modelica_Waermenetze/test/create_fmu/RectangularBorefield_1.26dev.fmu"
"[C:/Users/ETZOLD/AppData/Roaming/.openmodelica/libraries/Modelica 4.0.0+maint.om/Math/Random.mo:1057:5-1146:31:writable] Warning: Pure function 'Modelica.Math.Random.Utilities.initializeImpureRandom' contains a call to impure function 'Modelica.Math.Random.Utilities.initializeImpureRandom.setInternalState'.
[C:/Users/ETZOLD/AppData/Roaming/.openmodelica/libraries/Buildings 12.0.0/Utilities/Clustering/KMeans.mo:96:7-96:35:writable] Warning: inertia was used before it was defined (given a value). Additional such uses may exist for the variable, but some messages were suppressed.
Warning: The model contains alias variables with redundant start and/or conflicting nominal values. It is recommended to resolve the conflicts, because otherwise the system could be hard to solve. To print the conflicting alias sets and the chosen candidates please use -d=aliasConflicts.
"
```

4. Run the FMU with OMSimulator of the nightly build

```
PS C:\Users\ETZOLD\git\Modelica_Waermenetze\test\create_fmu> C:\Users\ETZOLD\Programs\OpenModelica_1.26.0dev\bin\OMSimulator.exe --tempDir=tmp --startTime=0  --stopTime=2.6784e+06 --stepSize=145.938 --timeout=800 --tolerance=1e-06 .\RectangularBorefield_1.26dev.fmu

LOG_ASSERT        | debug   | C:/Users/ETZOLD/git/Modelica_Waermenetze/test/create_fmu/875.fmutmp/sources/gc/memory_pool.c:100: pool_expand: Assertion `0 && "Attempt to allocate an unusually large memory. The memory management does not seem to be working as intended. Please create an issue on https://github.com/OpenModelica/OpenModelica/issues."` failed.
error:   [fmi2logger] C:/Users/ETZOLD/git/Modelica_Waermenetze/test/create_fmu/tmp/model-le4nemmd/temp/0001_fmu (logFmi2Call): fmi2ExitInitializationMode: terminated by an assertion.
error:   [initialize] fmi2_import_exit_initialization_mode failed for FMU "model.root.fmu"
error:   [initialize] Initialization of system "model.root" failed
error:   [simulate] Model "model" is in wrong model state
info:    0 warnings
info:    4 errors
```

## Expected Behavior

It is expected to successfully run the FMU.

## Version and OS

 - OpenModelica Version (nightly build required):  v1.26.0-dev-98-gb32172a97f (64-bit)
 - OS: Windows 11, 64 Bit
 - Modelica Buildings Library: 12.0.0

## Additional Info

The issue also appears under Ubuntu Linux 24.04 with the same error message.

**Comment by arun3688** [comment]
@tinoetzold I debugged the fmu with valgrind and the problem is related to initilization problem with `uninnitialized values` and it leads to memory issues, The problem happens exactly in this line `#2240`, if you unzip the fmu and go to sources folder and then look for file `RectangularBorefield_functions.c` 

```
  /*#modelicaLine [/home/arun/.openmodelica/libraries/Buildings 10.0.0/Fluid/Geothermal/Borefields/BaseClasses/HeatTransfer/ThermalResponseFactors/clusterBoreholes.mo:58:3-63:25]*/
  omc_Buildings_Utilities_Clustering_KMeans(threadData, _TBor, _N, _nBor, ((modelica_integer) 1), 1e-5, ((modelica_integer) 500), ((modelica_integer) 10), _nClu ,&_labels ,&_cluSiz);
 
```
one of the above parameters are uninitialized, see the trace from valgrind 

```
arun@win00085:/mnt/c/OPENMODELICAGIT/OMSimulator$ valgrind --track-origins=yes -s ./install/bin/OMSimulator ../OMEditDir/RectangularBorefield/Re
ctangularBorefield.fmu
==35176== Memcheck, a memory error detector
==35176== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==35176== Using Valgrind-3.18.1 and LibVEX; rerun with -h for copyright info
==35176== Command: ./install/bin/OMSimulator ../OMEditDir/RectangularBorefield/RectangularBorefield.fmu
==35176==
info:    Set temp directory to    "/mnt/c/OPENMODELICAGIT/OMSimulator"
info:    Set working directory to "/mnt/c/OPENMODELICAGIT/OMSimulator"
info:    New model "model" with corresponding temp directory "/mnt/c/OPENMODELICAGIT/OMSimulator/model-kwtkso79"
warning: could not load the FMI schema file: /mnt/c/OPENMODELICAGIT/OMSimulator/install/bin/schema/fmi2/fmi2ModelDescription.xsd, hence validation of "modeldescription.xml" with FMI 2.0 standard will not be performed
info:    Set working directory to "/mnt/c/OPENMODELICAGIT/OMSimulator"
info:    *** FMU Simulation Info ***
          - model:     model (model-exchange)
          - path:      ../OMEditDir/RectangularBorefield/RectangularBorefield.fmu
          - startTime: 0.000000
          - stopTime:  2678400.000000
          - tolerance: 0.000001
          - stepSize:  5356.800000
==35176== Thread 2:
==35176== Conditional jump or move depends on uninitialised value(s)
==35176==    at 0xC4D9362: omc_Buildings_Utilities_Clustering_KMeans (in /mnt/c/OPENMODELICAGIT/OMSimulator/model-kwtkso79/temp/0001_RectangularBorefield/binaries/linux64/RectangularBorefield.so)
==35176==    by 0xC4DA6CE: omc_Buildings_Fluid_Geothermal_Borefields_BaseClasses_HeatTransfer_ThermalResponseFactors_clusterBoreholes (in /mnt/c/OPENMODELICAGIT/OMSimulator/model-kwtkso79/temp/0001_RectangularBorefield/binaries/linux64/RectangularBorefield.so)
==35176==    by 0xC4DBC7D: omc_Buildings_Fluid_Geothermal_Borefields_BaseClasses_HeatTransfer_LoadAggregation_temperatureResponseMatrix (in /mnt/c/OPENMODELICAGIT/OMSimulator/model-kwtkso79/temp/0001_RectangularBorefield/binaries/linux64/RectangularBorefield.so)
==35176==    by 0xC2B0F24: RectangularBorefield_eqFunction_625 (in /mnt/c/OPENMODELICAGIT/OMSimulator/model-kwtkso79/temp/0001_RectangularBorefield/binaries/linux64/RectangularBorefield.so)
==35176==    by 0xC2AEC03: RectangularBorefield_functionInitialEquations_1 (in /mnt/c/OPENMODELICAGIT/OMSimulator/model-kwtkso79/temp/0001_RectangularBorefield/binaries/linux64/RectangularBorefield.so)
==35176==    by 0xC29F43B: RectangularBorefield_functionInitialEquations (in /mnt/c/OPENMODELICAGIT/OMSimulator/model-kwtkso79/temp/0001_RectangularBorefield/binaries/linux64/RectangularBorefield.so)
==35176==    by 0xC242DCB: symbolic_initialization (in /mnt/c/OPENMODELICAGIT/OMSimulator/model-kwtkso79/temp/0001_RectangularBorefield/binaries/linux64/RectangularBorefield.so)
==35176==    by 0xC2437E4: initialization (in /mnt/c/OPENMODELICAGIT/OMSimulator/model-kwtkso79/temp/0001_RectangularBorefield/binaries/linux64/RectangularBorefield.so)
==35176==    by 0xC4B158E: fmi2ExitInitializationMode (in /mnt/c/OPENMODELICAGIT/OMSimulator/model-kwtkso79/temp/0001_RectangularBorefield/binaries/linux64/RectangularBorefield.so)
==35176==    by 0x3506C7: fmi2_exitInitializationMode (in /mnt/c/OPENMODELICAGIT/OMSimulator/install/bin/OMSimulator)
==35176==    by 0x29F564: oms::ComponentFMUME::initialize() (in /mnt/c/OPENMODELICAGIT/OMSimulator/install/bin/OMSimulator)
==35176==    by 0x20BC2B: oms::SystemSC::initialize() (in /mnt/c/OPENMODELICAGIT/OMSimulator/install/bin/OMSimulator)
==35176==  Uninitialised value was created by a stack allocation
==35176==    at 0xC4D8A5D: omc_Buildings_Utilities_Clustering_KMeans (in /mnt/c/OPENMODELICAGIT/OMSimulator/model-kwtkso79/temp/0001_RectangularBorefield/binaries/linux64/RectangularBorefield.so)
==35176==
==35176== Warning: set address range perms: large range [0x2e526040, 0x3fd26040) (defined)
==35176== Warning: set address range perms: large range [0x59c87040, 0x74087040) (defined)
==35176== Warning: set address range perms: large range [0x74088040, 0x9b688040) (defined)
==35176== Warning: set address range perms: large range [0x9b689040, 0xd6889040) (defined)
LOG_ASSERT        | debug   | /home/arun/OpenModelica/367.fmutmp/sources/gc/memory_pool.c:100: pool_expand: Assertion `0 && "Attempt to allocate an unusually large memory. The memory management does not seem to be working as intended. Please create an issue on https://github.com/OpenModelica/OpenModelica/issues."` failed.
error:   [fmi2logger] [fmi2Error] RectangularBorefield/logFmi2Call: fmi2ExitInitializationMode: terminated by an assertion.
error:   [initialize] fmi2_import_exit_initialization_mode failed for FMU "model.root.RectangularBorefield"
==35176== Warning: set address range perms: large range [0x9b689028, 0xd6889058) (noaccess)
==35176== Warning: set address range perms: large range [0x74088028, 0x9b688058) (noaccess)
==35176== Warning: set address range perms: large range [0x59c87028, 0x74087058) (noaccess)
==35176== Warning: set address range perms: large range [0x2e526028, 0x3fd26058) (noaccess)
error:   [initialize] Initialization of system "model.root" failed
error:   [SimulateSingleFMU] oms_initialize failed
info:    1 warnings
info:    4 errors
==35176==
==35176== HEAP SUMMARY:
==35176==     in use at exit: 2,132 bytes in 52 blocks
==35176==   total heap usage: 3,012,224 allocs, 3,012,172 frees, 6,524,857,646 bytes allocated
==35176==
==35176== LEAK SUMMARY:
==35176==    definitely lost: 2,132 bytes in 52 blocks
==35176==    indirectly lost: 0 bytes in 0 blocks
==35176==      possibly lost: 0 bytes in 0 blocks
==35176==    still reachable: 0 bytes in 0 blocks
==35176==         suppressed: 0 bytes in 0 blocks
==35176== Rerun with --leak-check=full to see details of leaked memory
==35176==
==35176== ERROR SUMMARY: 10 errors from 1 contexts (suppressed: 0 from 0)
==35176==
==35176== 10 errors in context 1 of 1:
==35176== Conditional jump or move depends on uninitialised value(s)
==35176==    at 0xC4D9362: ???
==35176==    by 0xC4DA6CE: ???
==35176==    by 0xC4DBC7D: ???
==35176==    by 0xC2B0F24: ???
==35176==    by 0xC2AEC03: ???
==35176==    by 0xC29F43B: ???
==35176==    by 0xC242DCB: ???
==35176==    by 0xC2437E4: ???
==35176==    by 0xC4B158E: ???
==35176==    by 0x3506C7: fmi2_exitInitializationMode (in /mnt/c/OPENMODELICAGIT/OMSimulator/install/bin/OMSimulator)
==35176==    by 0x29F564: oms::ComponentFMUME::initialize() (in /mnt/c/OPENMODELICAGIT/OMSimulator/install/bin/OMSimulator)
==35176==    by 0x20BC2B: oms::SystemSC::initialize() (in /mnt/c/OPENMODELICAGIT/OMSimulator/install/bin/OMSimulator)
==35176==  Uninitialised value was created by a stack allocation
==35176==    at 0xC4D8A5D: ???
==35176==
==35176== ERROR SUMMARY: 10 errors from 1 contexts (suppressed: 0 from 0)
```

**Comment by adrpo** [comment]
Trying this in the gdb always crashes in different places so it looks like a bug in some external functions, maybe something that was newly added by @arun3688 to the FMI runtime (new lapack functions to support more of that).

```
(gdb) run
Starting program: /home/adrpo/om/build/bin/OMSimulator --tempDir=tmp --startTime=0  --stopTime=2.6784e+06 --stepSize=145.938 --timeout=800 --tolerance=1e-06 ./RectangularBorefield_1.26dev.fmu
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff4c33640 (LWP 1438391)]
[Detaching after vfork from child process 1438392]

Thread 1 "OMSimulator" received signal SIGSEGV, Segmentation fault.
0x00007ffff3f38200 in s_cat () from /tmp/fmi4c_AcjCbG/binaries/linux64/RectangularBorefield_1_26dev.so
(gdb) bt
#0  0x00007ffff3f38200 in s_cat () from /tmp/fmi4c_AcjCbG/binaries/linux64/RectangularBorefield_1_26dev.so
#1  0x00007ffff3f31f45 in dtrtri_ () from /tmp/fmi4c_AcjCbG/binaries/linux64/RectangularBorefield_1_26dev.so
#2  0x00007ffff3f2810c in dgetri_ () from /tmp/fmi4c_AcjCbG/binaries/linux64/RectangularBorefield_1_26dev.so
#3  0x00007ffff41c19dd in omc_Modelica_Math_Matrices_LAPACK_dgetri () from /tmp/fmi4c_AcjCbG/binaries/linux64/RectangularBorefield_1_26dev.so
#4  0x00007ffff41ad29c in omc_Modelica_Math_Matrices_inv () from /tmp/fmi4c_AcjCbG/binaries/linux64/RectangularBorefield_1_26dev.so
#5  0x00007ffff41a6eea in omc_Buildings_Fluid_Geothermal_Borefields_BaseClasses_Boreholes_BaseClasses_Functions_multipoleThermalResistances ()
   from /tmp/fmi4c_AcjCbG/binaries/linux64/RectangularBorefield_1_26dev.so
#6  0x00007ffff41a60c1 in omc_Buildings_Fluid_Geothermal_Borefields_BaseClasses_Boreholes_BaseClasses_Functions_internalResistancesOneUTube ()
   from /tmp/fmi4c_AcjCbG/binaries/linux64/RectangularBorefield_1_26dev.so
#7  0x00007ffff3fa7301 in RectangularBorefield_1_26dev_eqFunction_86 () from /tmp/fmi4c_AcjCbG/binaries/linux64/RectangularBorefield_1_26dev.so
#8  0x00007ffff3faccc0 in RectangularBorefield_1_26dev_functionInitialEquations_0 () from /tmp/fmi4c_AcjCbG/binaries/linux64/RectangularBorefield_1_26dev.so
#9  0x00007ffff3f9da5a in RectangularBorefield_1_26dev_functionInitialEquations () from /tmp/fmi4c_AcjCbG/binaries/linux64/RectangularBorefield_1_26dev.so
#10 0x00007ffff3f3e23b in initialization () from /tmp/fmi4c_AcjCbG/binaries/linux64/RectangularBorefield_1_26dev.so
#11 0x00007ffff41960b9 in fmi2ExitInitializationMode () from /tmp/fmi4c_AcjCbG/binaries/linux64/RectangularBorefield_1_26dev.so
#12 0x0000555555719eb4 in fmi2_exitInitializationMode (fmu=0x555555c42da0) at /home/adrpo/om/OMSimulator/3rdParty/fmi4c/src/fmi4c.c:2603
#13 0x000055555569812c in oms::ComponentFMUME::initialize (this=0x555555a7ffa0) at /home/adrpo/om/OMSimulator/src/OMSimulatorLib/ComponentFMUME.cpp:869
#14 0x0000555555621d3a in oms::SystemSC::initialize (this=0x555555a7f230) at /home/adrpo/om/OMSimulator/src/OMSimulatorLib/SystemSC.cpp:296
#15 0x00005555556d75cb in oms::Model::initialize (this=0x555555a7eba0) at /home/adrpo/om/OMSimulator/src/OMSimulatorLib/Model.cpp:1240
#16 0x00005555555ab04c in oms_initialize (cref_=<optimized out>) at /home/adrpo/om/OMSimulator/src/OMSimulatorLib/OMSimulator.cpp:1091
#17 0x00005555555b08d2 in do_simulation (model="model", timeout=...) at /home/adrpo/om/OMSimulator/src/OMSimulatorLib/OMSimulator.cpp:1160
#18 0x00005555555ad1bc in oms_RunFile (filename=<optimized out>) at /home/adrpo/om/OMSimulator/src/OMSimulatorLib/OMSimulator.cpp:1223
#19 0x00005555556bf678 in oms::Flags::SetCommandLineOption (cmd=...) at /home/adrpo/om/OMSimulator/src/OMSimulatorLib/Flags.cpp:181
#20 0x000055555559ddc2 in oms_setCommandLineOption (
    cmd=0x555555a78380 "--tempDir=tmp --startTime=0 --stopTime=2.6784e+06 --stepSize=145.938 --timeout=800 --tolerance=1e-06 ./RectangularBorefield_1.26dev.fmu")
    at /home/adrpo/om/OMSimulator/src/OMSimulatorLib/OMSimulator.cpp:493
#21 0x00005555555921d0 in main (argc=<optimized out>, argv=<optimized out>) at /home/adrpo/om/OMSimulator/src/OMSimulator/main.cpp:45
```

**Comment by adrpo** [comment]
If I compile the FMU with debug information, then I get this one:

```
Thread 1 "OMSimulator" received signal SIGSEGV, Segmentation fault.
0x00007ffff586ae00 in ?? () from /lib/x86_64-linux-gnu/libcrypto.so.3
(gdb) bt
#0  0x00007ffff586ae00 in ?? () from /lib/x86_64-linux-gnu/libcrypto.so.3
#1  0x00007ffff5770ec8 in SHA1_Update () from /lib/x86_64-linux-gnu/libcrypto.so.3
#2  0x00007ffff56ed7e6 in EVP_Digest () from /lib/x86_64-linux-gnu/libcrypto.so.3
#3  0x00007ffff56ed871 in EVP_Q_digest () from /lib/x86_64-linux-gnu/libcrypto.so.3
#4  0x00007ffff57725b6 in SHA1 () from /lib/x86_64-linux-gnu/libcrypto.so.3
#5  0x00007ffff4030f82 in cryptographicsHash (str=0x7ffff3ace820 "2.100e+01")
    at /home/adrpo/.openmodelica/libraries/Buildings 12.0.1-master/Resources/C-Sources/cryptographicsHash.c:304
#6  0x00007ffff404dbc9 in omc_Buildings_Utilities_Cryptographics_sha (threadData=0x555555ab8ab0, _str=0x7ffff3ace81b)
    at /home/adrpo/test/bugs/13905/fmu/sources/RectangularBorefield_1_26dev_functions.c:5792
#7  0x00007ffff404d7dd in omc_Buildings_Fluid_Geothermal_Borefields_BaseClasses_HeatTransfer_ThermalResponseFactors_shaGFunction (threadData=0x555555ab8ab0, _nBor=21, 
    _cooBor=..., _hBor=100, _dBor=1, _rBor=0.20000000000000001, _aSoi=1.1574074074074074e-06, _nSeg=12, _nClu=5, _nTimSho=26, _nTimLon=50, _ttsMax=148.4131591025766)
    at /home/adrpo/test/bugs/13905/fmu/sources/RectangularBorefield_1_26dev_functions.c:3525
#8  0x00007ffff3e7ed12 in RectangularBorefield_1_26dev_eqFunction_8498 (data=0x555555a7fd80, threadData=0x555555ab8ab0)
    at /home/adrpo/test/bugs/13905/fmu/sources/RectangularBorefield_1_26dev_08bnd_part5.c:3432
#9  0x00007ffff3e78050 in RectangularBorefield_1_26dev_updateBoundParameters_1 (data=0x555555a7fd80, threadData=0x555555ab8ab0)
    at /home/adrpo/test/bugs/13905/fmu/sources/RectangularBorefield_1_26dev_08bnd_part5.c:4180
#10 0x00007ffff3e6a59f in RectangularBorefield_1_26dev_updateBoundParameters (data=0x555555a7fd80, threadData=0x555555ab8ab0)
    at /home/adrpo/test/bugs/13905/fmu/sources/RectangularBorefield_1_26dev_08bnd.c:7938
#11 0x00007ffff3d86c43 in initialization (data=0x555555a7fd80, threadData=0x555555ab8ab0, pInitMethod=0x7ffff42d88d0 "fmi", pInitFile=0x7ffff42dbca3 "", initTime=0)
    at /home/adrpo/test/bugs/13905/fmu/sources/simulation/solver/initialization/initialization.c:756
#12 0x00007ffff4012cb4 in fmi2ExitInitializationMode (c=0x555555a7ca80) at /home/adrpo/test/bugs/13905/fmu/sources/fmi-export/fmu2_model_interface.c.inc:891
#13 0x0000555555719eb4 in fmi2_exitInitializationMode (fmu=0x555555c42da0) at /home/adrpo/om/OMSimulator/3rdParty/fmi4c/src/fmi4c.c:2603
#14 0x000055555569812c in oms::ComponentFMUME::initialize (this=0x555555a7ffa0) at /home/adrpo/om/OMSimulator/src/OMSimulatorLib/ComponentFMUME.cpp:869
#15 0x0000555555621d3a in oms::SystemSC::initialize (this=0x555555a7f230) at /home/adrpo/om/OMSimulator/src/OMSimulatorLib/SystemSC.cpp:296
#16 0x00005555556d75cb in oms::Model::initialize (this=0x555555a7eba0) at /home/adrpo/om/OMSimulator/src/OMSimulatorLib/Model.cpp:1240
#17 0x00005555555ab04c in oms_initialize (cref_=<optimized out>) at /home/adrpo/om/OMSimulator/src/OMSimulatorLib/OMSimulator.cpp:1091
#18 0x00005555555b08d2 in do_simulation (model="model", timeout=...) at /home/adrpo/om/OMSimulator/src/OMSimulatorLib/OMSimulator.cpp:1160
#19 0x00005555555ad1bc in oms_RunFile (filename=<optimized out>) at /home/adrpo/om/OMSimulator/src/OMSimulatorLib/OMSimulator.cpp:1223
#20 0x00005555556bf678 in oms::Flags::SetCommandLineOption (cmd=...) at /home/adrpo/om/OMSimulator/src/OMSimulatorLib/Flags.cpp:181
#21 0x000055555559ddc2 in oms_setCommandLineOption (
    cmd=0x555555a78380 "--tempDir=tmp --startTime=0 --stopTime=2.6784e+06 --stepSize=145.938 --timeout=800 --tolerance=1e-06 ./RectangularBorefield_1.26dev.fmu")
    at /home/adrpo/om/OMSimulator/src/OMSimulatorLib/OMSimulator.cpp:493
#22 0x00005555555921d0 in main (argc=<optimized out>, argv=<optimized out>) at /home/adrpo/om/OMSimulator/src/OMSimulator/main.cpp:45
```

**Comment by adrpo** [comment]
This is last one is even more controversial, it says it dies in SHA1 and so on that are from libcrypto.so.3 but that cannot be true as SHA1 and all the others are *implemented* inside cryptographicsHash.c:
https://github.com/lbl-srg/modelica-buildings/blob/master/Buildings/Resources/C-Sources/cryptographicsHash.c#L283

```
#0  0x00007ffff586ae00 in ?? () from /lib/x86_64-linux-gnu/libcrypto.so.3
#1  0x00007ffff5770ec8 in SHA1_Update () from /lib/x86_64-linux-gnu/libcrypto.so.3
#2  0x00007ffff56ed7e6 in EVP_Digest () from /lib/x86_64-linux-gnu/libcrypto.so.3
#3  0x00007ffff56ed871 in EVP_Q_digest () from /lib/x86_64-linux-gnu/libcrypto.so.3
#4  0x00007ffff57725b6 in SHA1 () from /lib/x86_64-linux-gnu/libcrypto.so.3
#5  0x00007ffff4030f82 in cryptographicsHash (str=0x7ffff3ace820 "2.100e+01")
    at /home/adrpo/.openmodelica/libraries/Buildings 12.0.1-master/Resources/C-Sources/cryptographicsHash.c:304
```

**Comment by bilderbuchi** [comment]
Name collision on `SHA1` + linking order or something like that? 
Does the compilation warn about multiple definitions of `SHA1`, or is the one-definition-rule a CPP-only thing?

**Comment by adrpo** [comment]
@bilderbuchi could be, but I need to make cmake show me more of the compilation steps. I will do a verbose compilation to see what's going on.

**Comment by arun3688** [comment]
> Trying this in the gdb always crashes in different places so it looks like a bug in some external functions, maybe something that was newly added by [@arun3688](https://github.com/arun3688) to the FMI runtime (new lapack functions to support more of that).

@adrpo i tried to statically link the `libopenblass` to check whether the problems are related to recent lapack sources, but it is not the main problem i guess if you add following lines to to `CmakeLists.txt` somewhere after `line number #318`

```
find_library(openblas
             NAMES openblas
             PATHS ${EXTERNAL_LIBDIRECTORIES} NO_DEFAULT_PATH)
message(STATUS "Linking ${openblas}")
target_link_libraries(${FMU_NAME_HASH} PRIVATE ${openblas})
list(APPEND RUNTIME_DEPENDS ${openblas})
```
This should do static linking

**Comment by tinoetzold** [comment]
Hi everyone, is this issue here also fixed with this https://github.com/OpenModelica/OpenModelica/issues/13336#issuecomment-2963858925 and the referenced commit https://github.com/OpenModelica/OpenModelica/commit/ad7298edc8cb8c1267bf18e7159aceb678cce01c?

Thanks!
Tino

**Comment by arun3688** [comment]
@tinoetzold No this issue is not fixed, here the problem is related to initialization

**Comment by tinoetzold** [comment]
Just noticed that the integration test for the FMUs built from the Buildings Library are now passing:

https://libraries.openmodelica.org/branches/master-fmi/Buildings_latest/files/Buildings_latest_Buildings.Fluid.Geothermal.Borefields.Examples.RectangularBorefield.sim

I tried to reproduce this, but unfortunately it didn't work with the nightly builds (using Ubuntu 24.04).

**Comment by casella** [comment]
@arun3688 is there any relationship between this issue and the one that was fixed by #15363? Even if there isn't a direct relation, could that fix inspire a fix for this problem?

**Comment by arun3688** [comment]
@casella #15363 should fix this issue

**Comment by casella** [comment]
> [@casella](https://github.com/casella) [#15363](https://github.com/OpenModelica/OpenModelica/pull/15363) should fix this issue

Good to hear! 🔝 

@tinoetzold please try with the next nightly build made once PR #15363 is merged on master.

**Comment by jschueller** [comment]
The memory pool in `memory_pool.c` has a hard limit `OMC_ERROR_AT_EXPAND_REQUEST`
(= 1 GB). When pool blocks need to grow beyond this threshold, `pool_expand`
fires an assertion. This occurs during `fmi2ExitInitializationMode` for models
whose initialization makes many large temporary allocations (e.g. borefield
heat-transfer matrices), causing the pool to expand repeatedly until it hits
the 1 GB limit.

Pool growth sequence from 2 MB initial block (1.5× each expansion):
  2 → 3 → 4.5 → 6.75 → 10.1 → 15.2 → 22.8 → 34.2 → 51.3 → 76.9 →
  115.3 → 173.0 → 259.5 → 389.3 → 583.9 → 875.8 → 1313.7 MB ← ASSERT

The pool state IS restored after fmi2ExitInitializationMode completes
(via omc_util_restore_pool_state), so the memory is not permanently
leaked. But the peak allocation during initialization exceeds 1 GB,
triggering the assertion.

Reproduction attempts:
- Models with large initial equations (n=1000+) compiled but did not
  trigger pool expansion because simple initial equations don't create
  enough temporary allocations.
- The specific Buildings.RectangularBorefield model triggers this
  through dense matrix operations in its borefield heat-transfer
  initialization (could not reproduce without Buildings library).

Possible fixes:
1. Increase OMC_ERROR_AT_EXPAND_REQUEST (e.g. to 4 GB) to accommodate
   models with large initialization memory footprints.
2. Save/restore pool state around each major solver iteration during
   initialization so temporary allocations don't accumulate.
3. In pool_expand, instead of asserting, allow the allocation but log
   a warning — the OOM will still happen if actual memory runs out.

**Comment by adrpo** [comment]
Not closed yet by #16082, we need also #16227.
