### ISSUE TITLE
Duplicate wrongly complains about name

### ISSUE THREAD

**Issue by ceraolo** [OpenModelica/OpenModelica#14103]
### Description
Duplicate feature of OM sometimes wrongly complains about names.

### Steps to Reproduce
1. Load package.mo from: 
[PowerGridsMC.zip](https://github.com/user-attachments/files/21327063/PowerGridsMC.zip)

2. Try to duplicate Electrical.BaseClasses.OnePortAC into OnePortAC2.

The following message appears:

<img width="502" height="190" alt="Image" src="https://github.com/user-attachments/assets/94c687f7-845d-4b12-9d50-5e7eec1f2962" />

that seems to me wrong.

### Expected Behavior
Duplication should occur in this case without issues

### Version and OS
OM 1.25.1 WIn 11

 - OpenModelica Version: [e.g. `omc --version` or `Help->About OMEdit` from OMEdit]
 - OS: [e.g. Windows 10, 64 bit]
 - Versions of used Modelica libraries if applicable

**Comment by casella** [comment]
In fact, it is not possible to duplicate Electrical.BaseClasses.OnePortAC into the same sub-package no matter what name is picked.

**Comment by perost** [comment]
`copyClass(PowerGridsMC.Electrical.BaseClasses.OnePortAC,"OnePortAC2",PowerGridsMC.Electrical.BaseClasses)` fails without error, which it shouldn't.

**Comment by perost** [comment]
Fixed with #14222. But I'll keep the issue open until I add a test case for it, I tried modifying our existing test case but it seems I'm missing something since I couldn't reproduce the issue there.

**Comment by ceraolo** [comment]
Up to today's Ubuntu nightly (dev 232), the fix is not available yet.
I will check the next days.

BTW, do you think this fix can be included in the upcoming 1.25.2 release?

**Comment by perost** [comment]
> Up to today's Ubuntu nightly (dev 232), the fix is not available yet. I will check the next days.
> 
> BTW, do you think this fix can be included in the upcoming 1.25.2 release?

@adrpo is working on fixing the Linux builds and will make a 1.25.2 as part of that, and I just cherry picked this fix to be included in it.

**Comment by perost** [comment]
I forgot that I hadn't added a test case for this yet, but when trying to make one I realized that I pushed in my previous fix with the fix disabled (I disabled it to be able to recreate the issue, then forgot to enable it again when pushing it in). I good demonstration of why test cases are so important I guess.

#14261 fixes the issue properly and also adds a test case. I will also port it to the 1.25 maintenance branch, but unfortunately I think it might be too late for it to be included in 1.25.2.

**Comment by casella** [comment]
Version [1.25.2](https://github.com/OpenModelica/OpenModelica/releases/tag/v1.25.2) was tagged last week, so it's too late to get #14261 in there. But we can still have a 1.25.3 release in September with this fix, no need to wait until the 1.26.0 release. @perost please cherry pick the PR to the 1.25 maintenance branch.

@ceraolo any requirement about the release date?

**Comment by perost** [comment]
Fixed with #14261 and ported to 1.25 maintenance with #14263.

**Comment by ceraolo** [comment]
>@ceraolo any requirement about the release date?

You know, I'm normally asked (by the people in charge of installing next academic year's SW in the lab) on Julies. Last July I answered: 1.25.1, the latest release available. 

Later, I discovered that this version is probably less reliable than last year's 1.23.1...
A few issues have been solved since then, AFAIK, hopefully also some strange behaviour on units of measures on plots and prefixes

So, I just would like to make an attempt to ask the teaching lab staff for a last-minute update.
If 1.25.2 comes out before the end of this month, I will try, otherwise, for this year, I'll stick with 1.25.1.
In case it shows too "worse" (for my needs) than 1.23.1, I will try to go back to that one.

According to my impressions, there is in 1.25.1 a strong regression regarding output loading times after some time of usage. After something like half an hour of usage, last week, I had to restart OMEdit to avoid waiting much more for the output to be loaded than for my simulations to be carried out.

**Comment by casella** [comment]
> You know, I'm normally asked (by the people in charge of installing next academic year's SW in the lab) on Julies. Last July I answered: 1.25.1, the latest release available.
> Later, I discovered that this version is probably less reliable than last year's 1.23.1...

I am a bit taken aback by this statement. What makes you think so?

We fixed almost [three hundred issues](https://github.com/OpenModelica/OpenModelica/issues?q=is%3Aissue%20%20closed%3A2024-07-04..2025-06-15%20-reason%3Anot-planned%20-reason%3Aduplicate) between 1.23.1 and 1.25.1. We identified [9 regressions](https://github.com/OpenModelica/OpenModelica/issues?q=is%3Aissue%20created%3A2024-07-04..2025-06-15%20-reason%3Anot-planned%20-reason%3Aduplicate%20label%3Aregression) during that period, all but [one](https://github.com/OpenModelica/OpenModelica/issues/13292) were fixed already in released versions.

> A few issues, have been solved since then, AFAIK, hopefully some strange behaviour on units of measures on plots and prefixes

Are these fixes all included in [1.25.2](https://github.com/OpenModelica/OpenModelica/milestone/63?closed=1), or do you refer to fixes that are only on master and planned for 1.26.0? In the latter case, we could back-port them to 1.25.3.

> So, I just would like to make an attempt to ask the teaching lab staff for a last-minute update. If 1.25.2 comes out before the end of this month, I will try, otherwise, for this year, I'll stick with 1.25.1. In case it shows too "worse" (for my needs) than 1.23.1, I will try to go back to that one.

Version 1.25.2 was tagged five days ago, with [these additional fixes](https://github.com/OpenModelica/OpenModelica/milestone/63?closed=1). @adrpo has already built it for Linux, the Window build is on its way, we should be able to release it today or tomorrow at the latest.

We could tag another patch release 1.25.3 with more fixes by the end of this week. At the moment, 1.25.3 only contains the fix to #14254, @perost can quickly back-port the fixt for this issue #14103, but it's still probably not worth it. If there are any other fixes on master (milestone 1.26.0) that you'd like to have in 1.25.3, please let us know.

You may also consider using 1.24.2 instead of 1.23.1, in case 1.25.x has some regressions that we can't fix in time for you lab personnel.

> According to my impressions, there is in 1.25.1 a strong regression regarding output loading times after some time of usage. After something like half an hour of usage, last week, I had to restart OMEdit to avoid waiting much more for the output to be loaded than for my simulations to be carried out.

This may be related to #14192. I'll ask @adeas31 to look into that with high priority. As usual, we need to be able to reproduce the issue, otherwise it's hard to fix it.

In general, I would recommend you to open tickets ASAP if you notice regressions of any kind in released versions or nightly builds. That's a necessary, albeit not sufficient, condition to get them fixed 😃

**Comment by ceraolo** [comment]
> 
> I am a bit taken aback by this statement. What makes you think so?
> 

I cannot demonstrate this in detail., However, the following ones matter significantly:
- issue #14192 
- issue #14101 (luckily now fixed)

Not sure, but I think I experienced other minor problems, but I had no time to analyse them explicitly (and to try to create corresponding tickets).

> We fixed almost [three hundred issues]

I know that OM has improved a lot during the years, even recent years. What I said referred just _to the way I use OM in my lessons_.  You know, software is like this: you add many useful features, but in doing so you inevitably break something previously functioning, so you have to recover...
I really appreciate OM a lot and I've been using it for more than ten years so far (my first ticket is #1553). I use it for teaching, research, recommend  it to colleagues...
Please do not consider my words as a criticism!

> 
> You may also consider using 1.24.2 instead of 1.23.1, in case 1.25.x has some regressions that we can't fix in time for you lab personnel.

There is a big difference in my personal and teaching choices of OM.
On My PC I tend to use the latest release or, when important tickets are just solved, even nightly builds. That's all.

For teaching, I have constraints:
- lab personnel ask me the following academic year's version on Julys. I may try to force them to accept updating near the end of Augusts (as I did just today with 1.25.2), but I have to ask this as a favour
- it is very impractical to change versions during the academic year, because:
   .> when I prepare exam assignments, I must check the solutions against the recommended OM version. In case my students have multiple versions, this may become a nightmare
   .> when students have issues they share their mo files with me. I must be able to reproduce their issues, without having to ask every time which OM version they refer to
  .> students must be able to cross-compare their results and, again, this is impractical if they do not share the same OM version
.> in classroom, if a student experiences some strange behaviour, I must be able to reproduce it on my PC, which must therefore have exactly the same OM version as theirs

These constraints imposed me to recommend a.a. 24-25 rel 1.23.1, and for a.a. 25-26 1.25.1 (now I'm trying to change into 1.25.2, as I said). No room for 1.24.x (the latest seems to be 1.24.4).

**Comment by casella** [comment]
> Please do not consider my words as a criticism!

Of course not 😃 

My point is that we are striving to continuosly improve the software on all fronts. Ideally, there should neve be a case where one is forced to stick to an old version of OMC because of (_insert the specific reason here_). If there are regressions, it is essential that we are informed ASAP, so we can fix them.

Tickets should ideally contain a minimal example to reproduce the issue. However, if you experience something fishy in new versions but don't have time to do that, please open a short ticket where you just alert us of the issue. That's already quite useful.

**Comment by casella** [comment]
1.25.2 is out.
