### ISSUE TITLE
Profiling option blocks+html does not work on Windows

### ISSUE THREAD

**Issue by cbu-hw** [OpenModelica/OpenModelica#14374]
Opening `Modelica.Blocks.Examples.PID_Controller`, then opening simulation setup-simulation flags-profiling-`blocks+html` fails with 

>'DOSKEY' is not recognized as an internal or external command, operable program or batch file. The system cannot find the path specified. 'DOSKEY' is not recognized as an internal or external command, operable program or batch file. The system cannot find the path specified. 

and no html file is generated in the model folder.  Other `_prof`-suffixed files are generated, though, so I suspect that only the html generation fails.

Using the `blocks` option, the simulation concludes successfully, some `_prof`-suffixed files are generated, but the Transformational debugger that pops up does not show profiling information (as expected).

Windows 11, OMEdit v1.26.0-dev-266-g1db406ac0c

**Comment by adeas31** [comment]
I think this is not an issue with OMEdit. There is something wrong in interactive environment.
What happens if you run the following script,

```
loadModel(Modelica);
getErrorString();
setCommandLineOptions("+profiling=blocks");
getErrorString();
simulate(Modelica.Blocks.Examples.PID_Controller);
getErrorString();
```

**Comment by adeas31** [comment]
Turns out we removed some needed files from the installation like `gnuplot` and `xsltproc` when we shifted to UCRT.
I already talked with @adrpo about it. He will add back the needed files.

**Comment by adrpo** [comment]
This should be fixed, but please check with the next nightly-build.

**Comment by casella** [comment]
If #14414 did it, we should probably port it to 1.25.5 as well. @adrpo is that OK?

**Comment by cbu-hw** [comment]
> This should be fixed, but please check with the next nightly-build.

sno, sorry, error is still happening with v1.26.0-dev-361-gbb9556c53f

**Comment by adeas31** [comment]
> > This should be fixed, but please check with the next nightly-build.
> 
> sno, sorry, error is still happening with v1.26.0-dev-361-gbb9556c53f

Yes, because the fix had a typo. I fixed it now in #14432

**Comment by cbu-hw** [comment]
OK, now an HTML report gets created! At least I find it if I look in the model's folder in the OMEdit working directory, it does not automatically open in the browser.

Interestingly, the error message 
> 'DOSKEY' is not recognized as an internal or external command, operable program or batch file. 'DOSKEY' is not recognized as an internal or external command, operable program or batch file. 

is still present.

**Comment by adeas31** [comment]
> OK, now an HTML report gets created! 

Good!

> it does not automatically open in the browser.

OMEdit does not try to open it. We never added a code that tries to open the html report automatically.

> 
> Interestingly, the error message
> 
> > 'DOSKEY' is not recognized as an internal or external command, operable program or batch file. 'DOSKEY' is not recognized as an internal or external command, operable program or batch file.
> 
> is still present.

I can't reproduce it on a fresh installation. Is the error shown as simulation output or just a normal error message?

**Comment by cbu-hw** [comment]
> I can't reproduce it on a fresh installation. Is the error shown as simulation output or just a normal error message?

OK, then I'd say we can close this, it's not that important...
It's a red stdout | error line in the Output tab, after the "Time measurements are stored in.." line.

**Comment by adeas31** [comment]
> It's a red stdout | error line in the Output tab, after the "Time measurements are stored in.." line.

Weird. This is how it looks like for me,

<img width="2694" height="1922" alt="Image" src="https://github.com/user-attachments/assets/8fa2dd02-c210-4311-86fb-9fef9fca83dc" />

@adrpo any idea?

**Comment by adeas31** [comment]
Regarding opening the html file automatically. I can make OMEdit look for the html report and open it in the browser.

**Comment by cbu-hw** [comment]
> Regarding opening the html file automatically. I can make OMEdit look for the html report and open it in the browser.

Na, don't bother. I just (wrongly) assumed that that is what's breaking, as the html file gets generated.

**Comment by casella** [comment]
@cbu-hw can we close this ticket?

**Comment by cbu-hw** [comment]
> [@cbu-hw](https://github.com/cbu-hw) can we close this ticket?

Yeah, I suggested this above already...

> OK, then I'd say we can close this, it's not that important...
