### ISSUE TITLE
Simple CS model fails to simulate on Linux

### ISSUE THREAD

**Issue by mquinson** [OpenModelica/OpenModelica#14422]
### Description

The simulation of a CS FMU fails with the following error:

```
[Info] fmi2_library.cpp:46: [FMI callback logger] status=Error, instanceName=sinus, category=logStatusError, message=fmi2GetContinuousStates: Invalid argument states[] = NULL.
```

### Steps to Reproduce

I use this simple simulation model:

```
model sinus

output Real x;
output Integer positive;

equation
  x = sin(time);
  if(x >= 0) then
    positive = 1;
  else
    positive = 0;
  end if; 

end sinus;
```

and I export it with this line of script: `buildModelFMU(sinus, version="2.0", fmuType="cs");` on Linux with omc version 1.23.1-1 from the Debian package at https://build.openmodelica.org/apt bullseye/release amd64.

It fails to simulate with both FMpy and FMI4cpp on my Linux system, as detailed in https://github.com/NTNU-IHB/FMI4cpp/issues/162
If I activate the logs in FMI4cpp, here are the last lines:

```
t=3.141
[Info] fmi2_library.cpp:46: [FMI callback logger] status=OK, instanceName=sinus, category=logFmi2Call, message=fmi2GetInteger: #i0# = 1
[Info] fmi2_library.cpp:46: [FMI callback logger] status=OK, instanceName=sinus, category=logFmi2Call, message=internalEventUpdate: Start Event Update! Next Sample Event 0
[Info] fmi2_library.cpp:46: [FMI callback logger] status=OK, instanceName=sinus, category=logFmi2Call, message=internalEventUpdate: newDiscreteStatesNeeded false
[Info] fmi2_library.cpp:46: [FMI callback logger] status=OK, instanceName=sinus, category=logFmi2Call, message=internalEventUpdate: Checked for Sample Events! Next Sample Event 0
[Info] fmi2_library.cpp:46: [FMI callback logger] status=OK, instanceName=sinus, category=logFmi2Call, message=fmi2GetEventIndicators: z0 = 1
[Info] fmi2_library.cpp:46: [FMI callback logger] status=OK, instanceName=sinus, category=logFmi2Call, message=fmi2CompletedIntegratorStep
[Info] fmi2_library.cpp:46: [FMI callback logger] status=OK, instanceName=sinus, category=logFmi2Call, message=fmi2GetEventIndicators: z0 = -1
[Info] fmi2_library.cpp:46: [FMI callback logger] status=OK, instanceName=sinus, category=logFmi2Call, message=internalEventUpdate: Start Event Update! Next Sample Event 0
[Info] fmi2_library.cpp:46: [FMI callback logger] status=OK, instanceName=sinus, category=logFmi2Call, message=internalEventUpdate: newDiscreteStatesNeeded false
[Info] fmi2_library.cpp:46: [FMI callback logger] status=OK, instanceName=sinus, category=logFmi2Call, message=internalEventUpdate: Checked for Sample Events! Next Sample Event 0
[Info] fmi2_library.cpp:46: [FMI callback logger] status=Error, instanceName=sinus, category=logStatusError, message=fmi2GetContinuousStates: Invalid argument states[] = NULL.
Error in step() at t=3.141
```

As you can see, the bug occurs when crossing the zero, at `t=3.14159` for the function `sin(t)`. My understanding is that my CS FMU is complaining that the ME interface was not correctly initialized, but as a user I never intended to use ME. This explanation may well be off, as I'm really a newbie with FMUs.

This bug seems somewhat related to https://github.com/OpenModelica/OpenModelica/issues/13750 At least, it raises the same error message on the same operating system, but I 'm not sure I understand whether their model relates to mine.

### Expected Behavior

I'm not sure whether I'm expected to get an event when the value of positive changes (I would love to), but at least the simulation should not fail.

### Version and OS

```
$ omc --version
OpenModelica 1.23.1
```

Debian stable bullseye, from the official Docker image.

CI job installing OpenModelica, using it to generate the FMU and simulating it for a while: https://framagit.org/simgrid/simgrid-FMI/-/jobs/3082234 

Corresponding build script: https://framagit.org/simgrid/simgrid-FMI/-/blob/0fd75c9684c4bcc70bc3b4edc5891f7b6f46f352/.gitlab-ci.yml  (this is the exact version that generated the above logs, even if the git file changes in between)

**Comment by cbu-hw** [comment]
I reproduce on Windows 11 with OM nightly OpenModelica v1.26.0-dev-344-g81f39f4f0e (FMU exported from OMEdit), so we can probably exclude both the OS and the old OM version as a source of the problem.

```
> fmpy simulate .\OM_14422.fmu --show-plot --stop-time 4 --debug-logging --fmi-logging
[...]
[OK] fmi2GetReal: #r3# = 0.001592652916486828
[FMI] fmi2GetReal(component=0x2ca6062a830, vr=[3], nvr=1, value=[0.0015926529164868282]) -> OK
[OK] fmi2GetInteger: #i0# = 1
[FMI] fmi2GetInteger(component=0x2ca6062a830, vr=[0], nvr=1, value=[1]) -> OK
[OK] internalEventUpdate: Start Event Update! Next Sample Event 0
[OK] internalEventUpdate: newDiscreteStatesNeeded false
[OK] internalEventUpdate: Checked for Sample Events! Next Sample Event 0
[OK] fmi2GetEventIndicators: z0 = 1
[OK] fmi2CompletedIntegratorStep
[OK] fmi2GetEventIndicators: z0 = -1
[OK] internalEventUpdate: Start Event Update! Next Sample Event 0
[OK] internalEventUpdate: newDiscreteStatesNeeded false
[OK] internalEventUpdate: Checked for Sample Events! Next Sample Event 0
[ERROR] fmi2GetContinuousStates: Invalid argument states[] = NULL.
[FMI] fmi2DoStep(component=0x2ca6062a830, currentCommunicationPoint=3.14, communicationStepSize=0.004, noSetFMUStatePriorToCurrentPoint=1) -> ERROR
[...]
```

**Comment by casella** [comment]
@arun3688 can you please have a look?

**Comment by arun3688** [comment]
@mquinson @cbu-hw I can reproduce the issue and did some debugging and found the problem, I will fix it tomorrow

**Comment by arun3688** [comment]
@mquinson @cbu-hw the issue is fixed with this commit 35d5fc75f3c2e63a88303cd98827508e35184eb7, please test it from the nightly builds tomorrow

**Comment by mquinson** [comment]
Hello,
my bug remains with version OpenModelica 1.24.0~dev-213-ge41d2be from the debian nightly package. Here is a CI build log demonstrating it: https://framagit.org/simgrid/simgrid-FMI/-/jobs/3086381

Is it because the fix did not propagate to those debian package yet?

**Comment by arun3688** [comment]
@mquinson no the fix got propogated to nightly builds, but i guess the latest nightly build version should be `1.26.0~dev-365-gf18f904`  see here https://openmodelica.org/download/download-linux/

**Comment by mquinson** [comment]
Ok, my problem is that I tried to pull nightly for the bullseye distribution, which is so ancien that OM nighlty are not generated for it anymore. It would be less error prone if the nightly were completely removed for this distro rather than simply outdated, but that's another issue.

I confirm that my bug is gone with version 1.26.0~dev-369-g063cb48 Thanks a lot for your time and your patience.
