### ISSUE TITLE
Compiler internal error in Pantelides index reduction triggered solely by component declaration order (OM 1.24.2, MSL 3.2.3/4.0.0)

### ISSUE THREAD

**Issue by htywaa** [OpenModelica/OpenModelica#14731]
[brayton.txt](https://github.com/user-attachments/files/23882226/brayton.txt)

# ### Description

In **OpenModelica 1.24.2 (64-bit)**, compiling a ThermoPower-based Brayton-cycle model produces **internal compiler errors** during Pantelides index reduction and SimCode generation.

A critical and unexpected behavior was found:

---

## **➡ Merely changing the *declaration order* of component instances inside the same model causes the compiler to either succeed or fail.**

* **Code 1 (fails)** → internal compiler errors
* **Code 2 (works)** → identical model except for reordering of component declarations

This is not compliant with Modelica semantics, where declaration ordering must not change the mathematical meaning of a model.

---

### **1. The issue appears in both Modelica Standard Library 3.2.3 and 4.0.0.**

So this is **not library-version specific** and seems to be a compiler frontend/DAE-indexing bug.

### **2. The provided model cannot simulate yet (parameters incomplete).**

The error occurs **purely at compile-time**, *before* any actual initialization or simulation.
Thus the issue is strictly about **the compiler’s symbolic processing**, not about runtime behavior.

---

The failing model produces errors such as:

```
Internal error IndexReduction.pantelidesIndexReduction failed!
System is structurally singular and cannot be handled because the number of unassigned equations is larger than the number of states.

Internal error Transformation Module PFPlusExt index Reduction Method Pantelides failed!

Internal error function createStateSetsSets failed.
Internal error function createSimCode failed.
```

These are internal compiler faults rather than modeling errors.

---

# ### Additional files

Please attach:

* `brayton_failing.mo`including (Code 1:test1) (Code 2:test2)

---

# ### Version and OS

* **OpenModelica 1.24.2 (64-bit)**
* Modelica Standard Library **3.2.3 and 4.0.0** (both tested, both exhibit the issue)
* ThermoPower version bundled with OM 1.24.2
* **Windows 10 64-bit**

---
# ### Additional context

Since .mo is not supported, upload in .txt format

---
Given that only reordering component declarations changes the outcome, this strongly suggests an underlying compiler bug.

A fix or guidance from the compiler team would be highly appreciated.

---

**Comment by phannebohm** [comment]
Indeed this also happens with the latest master (1.26.0-dev-521-gcb670bd818-cmake) on Linux. And the only difference between `test1` and `test2` is that the declaration of `sourceMassFlow1` is moved from the bottom to the top.

The model is quite large. Can you build an MWE from it so we can find the problem more easily?

**Comment by htywaa** [comment]
@phannebohm 
Indeed, the only difference between these two tests is a very small one: whether the component declaration is placed at the top or at the bottom, and this alone determines whether the compilation succeeds. Based on my testing, this phenomenon is widespread across multiple versions on both Windows and Linux (ranging broadly from 1.18 up to 1.26).

Unfortunately, I cannot provide a simpler model version (this already seems to be the minimal one, originally extracted from a complex baryton system), because any further simplification causes the phenomenon to disappear. It appears to be a bug triggered by specific code and its ordering—if the order or the number of components is changed, the bug cannot be reproduced.

One point I would like to add: the bug is not limited to version 3.2.3 or the ThermoPower library. My colleagues have reported encountering similar issues in the standard library or in custom libraries (based on 4.0.0). If there is any commonality among these cases, it is that they all involve fluid loop systems, though I am not certain whether the fluid loop itself is the cause.

From my limited perspective, this seems to be an error in the compiler’s front-end flattening process, or possibly related to heuristic algorithms used in the causality analysis.

**Comment by cbu-hw** [comment]
> My colleagues have reported encountering similar issues in the standard library

Maybe in that case those colleagues can furnish you with a small MWE? 🤔

**Comment by htywaa** [comment]
@phannebohm @cbu-hw 
Unfortunately, we tried to build some MWEs, but we couldn't reproduce the results, which seems to be related to the feature code order. My colleague reported an important finding that using the old frontend on 1.18.1 compiles but not with the new frontend. I think this is a key watershed.

**Comment by perost** [comment]
> [@phannebohm](https://github.com/phannebohm) [@cbu-hw](https://github.com/cbu-hw) Unfortunately, we tried to build some MWEs, but we couldn't reproduce the results, which seems to be related to the feature code order. My colleague reported an important finding that using the old frontend on 1.18.1 compiles but not with the new frontend. I think this is a key watershed.

I checked the output from the new frontend and pretty much the only difference between `test1` and `test2` is as expected the declaration order. The warning about the missing inner system points to a different place and one of the equations generated from the equations is reversed, but that's also expected and shouldn't matter. So it doesn't look like a frontend issue to me.

**Comment by Alix-DFS** [comment]
I'm just commenting to let you know that we're also experiencing this issue.

Context and details: This is part of an internal project for my company, so I'm unable to provide an example and haven't had time to build a Minimum Working Example (MWE) (which would also "anonymize" the project).

We're working with @audrey-jardin's team (EDF) on large scale industrial applications.

Software: omEdit Connected to OpenModelica v1.23.1 (64-bit) on Windows

Regards

**Comment by casella** [comment]
@htywaa have you tried with 1.26.3 and with the latest nightly build? Maybe the problem is fixed already.

**Comment by Alix-DFS** [comment]
> [@htywaa](https://github.com/htywaa) have you tried with 1.26.3 and with the latest nightly build? Maybe the problem is fixed already.

For our usecase, we tried with my colleague's computer on 1.26.3 and the problem is still there
