### ISSUE TITLE
Error NFCeval.evalBuiltinCosTitle with final complex parameters

### ISSUE THREAD

**Issue by tinrabuzin** [OpenModelica/OpenModelica#7204]
### Description
I am not sure what this error exactly means nor what it implies, but I realized it happens when I define final complex parameters as in the example and when the parameter phi is defined using initial equation.
I haven't noticed anything strange in the simulations, i.e. it seems like the simulation results are correct regardless of the error message.

Specifically, I get the following error message:
```
[1] Translation Error
[C:/OM116/OM64bit/OMCompiler/Compiler/NFFrontEnd/NFCeval.mo: 2124:20-2124:79]: Internal error NFCeval.evalBuiltinCos got invalid arguments (phi)
```

The error can be recreated with the following example:
```
model test
  parameter Modelica.SIunits.Angle phi(fixed=false);
  final parameter Complex X = Complex(cos(phi), sin(phi));
initial equation
  phi = Modelica.Constants.pi/4;
end test;
```

This happens on OpenModelica 1.16.2 (64 bit), Windows 10.

**Comment by perost** [comment]
This was fixed by the fix for your previous issue (#7156). I would recommend trying out the latest nightly build of OpenModelica and see if it solves your issues.

**Comment by tinrabuzin** [comment]
@perost I am now at  v1.18.0-dev-66-gcf3a725b80 and as you say the problem from my previous issue and the test model from above is fixed.

However, in my larger model I am still getting the `NFCeval.evalBuiltinCos` error related to the Complex parameters. It is appearing regardless of the `final` keyword. I am trying to recreate the problem in a simpler model but I'm unsuccessful so far. I will report here if I manage to figure it out.

**Comment by tinrabuzin** [comment]
Here is the example that recreates the issue:
```
model test
    parameter Real phi(fixed=false);
    final parameter Complex x = Complex(cos(phi),sin(phi));
    final parameter Complex y = x;
initial equation
    phi = Modelica.Constants.pi/4;
end test;
```
It seems like the introduction of another `final parameter Complex` dependent on the first one causes the error message.

**Comment by sjoelund** [comment]
That might be because X.re and X.im are used for something structural. If you have an initial equation, parameters cannot be used in for example array dimensions. I'd recommend creating a new ticket with a model that has this problem.

Does it work if you use fixed=true and a binding instead of the initial equation?

**Comment by tinrabuzin** [comment]
> That might be because X.re and X.im are used for something structural. If you have an initial equation, parameters cannot be used in for example array dimensions. I'd recommend creating a new ticket with a model that has this problem.

I think it was nothing structural. I was just using these parameters to compute start values for other variables.

> Does it work if you use fixed=true and a binding instead of the initial equation?

I do not get an error message with a binding equation. I also get correct results with the example from my last comment, but I get this error message that worries me. Do you have any idea if it could eventually cause issues in more complex models?

**Comment by sjoelund** [comment]
OK, I'm not sure why it would need to print the error here since final parameters are not required to be evaluated. @perost ?

**Comment by perost** [comment]
The error in this case could safely be ignored. The logic in the flattening was wrong, so the compiler would try to evaluate the binding, fail, and then succeed in splitting the binding anyway. I've fixed this in #7208, but it will likely still happen in some cases when the bindings are more complicated.

We really need to redesign this part, the compiler shouldn't evaluate complex bindings. Unfortunately I don't have much time to work on this right now. One workaround is as mentioned to use initial equations with non-fixed parameters.
