### ISSUE TITLE
NFCeval.evalBinarySub failed to evaluate

### ISSUE THREAD

**Issue by dariomangoni** [OpenModelica/OpenModelica#7385]
### Description
The error is really close to #7384 but I'm not sure if it is exactly the same.
```
[C:/OM117/OM64bit/OMCompiler/Compiler/NFFrontEnd/NFCeval.mo: 1037:9-1037:67]: Internal error NFCeval.evalBinarySub failed to evaluate ‘{1.0, 0.0, 0.0}[pt_sel + 1] - {1.0, 0.0, 0.0}[pt_sel]‘
```

In this case I was able to reduce the minimal example to very few lines of code:
```
model PolyBeamShape2
  parameter Real r_shape[3,:] = {{1.0,0,0}, {0,1.0,0}, {0,0,1.0}};
protected
  parameter Integer ptsCount = size(r_shape,2);
  parameter Real length[ptsCount-1] = {Modelica.Math.Vectors.norm(r_shape[:, pt_sel+1]-r_shape[:, pt_sel]) for pt_sel in 1:ptsCount-1};
end PolyBeamShape2;
```

### Version and OS

 - OpenModelica Version: v1.17.0 (64-bit)
 - OS: Windows 10, 64 bit
 - MSL 3.2.3

**Comment by perost** [comment]
This does seem to be the same issue as #7384, which I've already fixed locally and which works with this example too. I need to test it a bit more before I commit it though. But your previous ticket was actually quite helpful, I was already working on a similar issue and taking both issues into account led me to a better solution.

**Comment by dariomangoni** [comment]
@perost, I'm at v1.18.0-dev-233-g07fe8a249c (64-bit) generated at 2021-04-22 03:57 but this issue is still present.
Is this expected? Should I wait more to have the fix integrated in the nightly build?

**Comment by sjoelund** [comment]
That version should have the fix from #7387

**Comment by dariomangoni** [comment]
All my tests that were hitting that issue are still failing though

**Comment by perost** [comment]
Do you have some other test than the one you posted above? That one is definitely working for me at least.

**Comment by dariomangoni** [comment]
Am I doing something wrong or have I bad settings?

https://user-images.githubusercontent.com/8025529/115697971-67e43c00-a364-11eb-8f0a-c9b670bc588e.mp4

I have other examples but I cannot share them easily

**Comment by perost** [comment]
There aren't any settings that would influence this issue, so the only thing I can think of is that you're still using an old version of omc somehow. Do you have multiple versions of OpenModelica installed? Maybe it's using the wrong omc in that case.

**Comment by perost** [comment]
Actually, now that I think about it there is one flag that would cause the same issue: `-d=evaluateAllParameters`. I can't see from your video whether you have it set or not since it's not a simulation flag.

**Comment by perost** [comment]
I fixed the issue with using `-d=evaluateAllParameters`, but it seems we have some issues with our CI that's preventing me from merging it at the moment.

**Comment by dariomangoni** [comment]
> 
> 
> Actually, now that I think about it there is one flag that would cause the same issue: `-d=evaluateAllParameters`. I can't see from your video whether you have it set or not since it's not a simulation flag.

Hi @perost, I usually have `-d=evaluateAllParameters` enabled, but I got rid of them whenever I have to check issues.
I removed them also from Options>Simulation. Is there any other place that I should check?

**Comment by perost** [comment]
> > Actually, now that I think about it there is one flag that would cause the same issue: `-d=evaluateAllParameters`. I can't see from your video whether you have it set or not since it's not a simulation flag.
> 
> Hi @perost, I usually have `-d=evaluateAllParameters` enabled, but I got rid of them whenever I have to check issues.
> I removed them also from Options>Simulation. Is there any other place that I should check?

There's a checkbox in Options->Simulation too, and it's also possible to manually add the flag there. Anyway, it should work now whether you have that flag enabled or not. Let us know if this fixes the issue for you, otherwise we'll have to investigate more.

**Comment by dariomangoni** [comment]
Oh you are right, without the checkbox it works. But thanks to have it fixed also for the "evaluateAllParameters=true" case.
