### ISSUE TITLE
Replaceable record with choices are not displayed in parameter dialog correctly

### ISSUE THREAD

**Issue by sbaetzing** [OpenModelica/OpenModelica#7487]
### Description
A definition like 
`replaceable record Valve =
        Rexroth_Valves.Internal.Database.DB_43.Rexroth_4WREE10E75_2X
annotation (choices(
choice( redeclare record Valve =
              Rexroth_Valves.Internal.Database.DB_43.Rexroth_4WREE10E75_2X                    "4WREE10E75-2X"),
choice( redeclare record Valve =
              Rexroth_Valves.Internal.Database.DB_43.Rexroth_4WREE10E25_2X                    "4WREE10E25-2X"),
choice( redeclare record Valve =
              Rexroth_Valves.Internal.Database.DB_43.Rexroth_4WREE10E50_2X                    "4WREE10E50-2X")));`

should end in a parameter dialog with a drop down menue with the entries 
"4WREE10E75-2X"
"4WREE10E25-2X"
"4WREE10E50-2X"

but only shows 
![grafik](https://user-images.githubusercontent.com/84787397/119620418-4106a300-be05-11eb-8a89-921ae7609f32.png)

### Steps to Reproduce

Instantiate a model from the Bosch Rexroth Simulation Library e.g.
Rexroth_Valves.ProportionalValves.Rexroth_4WREE_2X

### Version and OS

OpenModelica v1.18.0-dev-280-g0b76908279 (64-bit)
OMSimulator v2.1.1.post70-gdf73447-mingw
OS: Windows 10, 64 bit
 - Versions of used Modelica libraries if applicable: MSL 3.2.3, Bosch Rexroth Simulation Libraries (1.4)

### Additional Context

You should already have the Bosch Rexroth Simulation Libraries (1.4)
aswell as all the correpsonding test libraries. If not Niklas Worchesch can upload it again.

Best wishes

Sven Bätzing

**Comment by casella** [comment]
I guess the `choicesAllMatching` annotation was implemented, but not the `choices` annotation. @adrpo, can you comment on that?

**Comment by adrpo** [comment]
Should be fixed via #7652.
@niklwors and @sbaetzing can you please check with the latest nightly if this works fine for you?

**Comment by niklwors** [comment]
@adrpo thank you very much for the fix. 
I noticed that the redeclare term is included in the dialogue. e.g. 
```redeclare record Valve = Rexroth_Valves.Internal.Database.DB_43.Rexroth_4WREE10E75_2X "4WREE10E75-2X"```
and in the icon the changed parameter is not displayed. It still shows ```paramterset.OrderingCode``` in the icon instead of ```Rexroth_4WREE10E75_2X``` But this is maybe not related to the original problem.
And if I load a model with an redeclared parameter, the parameter dialog shows not the current parameter value but ```redclare recorde Valve=ValveParams```

**Comment by casella** [comment]
@niklwors, see @adrpo's comment in [#7488](https://github.com/OpenModelica/OpenModelica/issues/7488#issuecomment-1005089983). My suggestion is to only show the text in the comment (if there is one), otherwise show the redeclare clause.

Would that be OK for you? If so, I can open a ticket for that.

**Comment by niklwors** [comment]
@casella @adrpo  yes, this would be fine.

**Comment by casella** [comment]
See reopened #7488
