### ISSUE TITLE
Instance-based mechanism to handle parameters, replaceable classe, conditional connectors, and parameter-dependent dialogs

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#8425]
The current mechanism that OMEdit uses for parameter editing and to display component icons in diagrams has OMEdit figure out what are the relevant classes ad inquire _their definitions_ in the used libraries. In this way, local modifications, inheritance, etc. need to be handled ad-hoc by OMEdit, which is clumsy and unnecessarily complicated. See discussion [here](https://github.com/OpenModelica/OpenModelica/issues/2081#issuecomment-965855258).

We need to transition to a new mechanism, whereby OMEdit enquires _an instance_ of the model, relying on the new front end to carry out all the complicated work. The NF is very fast, so this is now doable.

This development will be carried out in Q1 2022.

Doing this will address the root cause of numerous issues that have popped up over the years, and have remained unresolved to date, because fixing the old mechanism is really not an option. These issues are collected here for reference:
- #2081 
- #4236 
- #6111 
- #7826
- #8066 
- #8086 
- #8210 

While designing this new mechanism, we should also keep in mind that we need to support hierarchical editing of parameters and replaceable stuff in models, a.k.a. "Show component" in Dymola:
- #2891

This feature also requires to instantiate models and work on the instance to change modifiers

**Comment by casella** [comment]
@AHaumer, @max-privato, @sbaetzing, @niklwors, @dietmarw, please follow this ticket to see the progress, instead of #2081, which is only a part of the story.

**Comment by adrpo** [comment]
# Design

When queried, OMC will return a JSON of the instantiated tree including:
- parameter, constants and replaceable components 
- replaceable classes
- unevaluated graphical and dialog annotations
- inherited class hierarchy (?)

## Retrieving a model instance: getModelInstance(Path.To.Model): JSON
Calling this API will return the instance tree of the model.
Possible optimization:
- do partial instantiation of only needed things (no equ/alg sections)
- request just part of the tree via some filters
- compress the data

## Sending back modifications: setModelInstance(JSON): Boolean
Calling this API will apply the modifications from the JSON to the top level Modelica model in the AST.
Possible optimization:  
- send only the changes, not the entire model with the changes back

## Evaluating expressions on a model instance: evaluateExpressionOnModelInstance(Expression, Path.To.Model): JSON
Calling this API will return the evaluated expression.
Possible optimization: 
- return the both the unevaluated and evaluated expression as part of the instance tree

## GUI <-> OMC communication

The usual workflow:
1. GUI: asks for an model instance via getModelInstance
2. OMC: responds with a JSON tree
3. GUI: parses the JSON and populates its internal structures
4. GUI: generates the Diagrams and Dialogs
5. GUI: The user changes data in Dialogs
   - if possible (no function calls) GUI evaluates *locally* the expressions needed for Diagrams and Dialogs dependent of the changed data
   - if not possible (there are function calls) GUI asks OMC to evaluate the expressions needed on on the model instance
5. GUI: go to step 4 and maybe also do in parallel steps 6-7
6. GUI: sends the changes back to OMC as a JSON file with only the differences
7. OMC: applies the changes on the top level Modelica model in the internal AST

##Notes

Some things to think about:
- how to encode Modelica expressions JSON tree (quite large) or just string (compact) which we can parse with OMParser?
- how should we provide the choices (in choicesAllMatching/choice) and their respective trees so that they can be edited?

**Comment by adrpo** [comment]
@adeas31, @perost, @casella: please read and give feedback on the Design above.

**Comment by sjoelund** [comment]
There is JSON.mo file that could be used and passed to OMEdit that it could possibly transform to QVariant or work with directly. I would avoid passing large strings

**Comment by perost** [comment]
> There is JSON.mo file that could be used and passed to OMEdit that it could possibly transform to QVariant or work with directly. I would avoid passing large strings

Yeah, I'm using the existing JSON structures, but dumping it to a string to pass to OMEdit. We'll see how well that works, but dumping the JSON to a string is trivial anyway and something we likely need for OMWebEdit anyway.

**Comment by sjoelund** [comment]
Sure, dumping to string is fine for the scripting API. But for OMEdit there's a potentially faster way. And you'd get the same data types if you parse JSON to QVariant so you could just add the shortcut later and prototype this way.

**Comment by adeas31** [comment]
> inherited class hierarchy (?)

This is needed in order to draw the complete elements.

> request just part of the tree via some filters

We don't need to worry about that part. Since in a normal work flow OMEdit will only ask the JSON once in the beginning and then send back the edited parts to OMC. The only other case when the whole JSON is needed is when user edits the Modelica text manually.

> Evaluating expressions on a model instance:

I didn't get that part. Maybe you can elaborate more with some examples.

**Comment by adeas31** [comment]
> There is JSON.mo file that could be used and passed to OMEdit that it could possibly transform to QVariant or work with directly. I would avoid passing large strings

Even if we transform to Qt data structures we still have to somehow pass them to OMEdit.

**Comment by sjoelund** [comment]
By MetaModelica `void*` :)

**Comment by casella** [comment]
I have one comment, based on our past discussion. When editing a model with modifiers, OMC should not only return the actually modified values, but also the default values those parameters would have, in case one deletes the modifed value and wants to see the underlying default. I'm not sure if this feature is already included in @adrpo's proposal.

**Comment by adrpo** [comment]
> I have one comment, based on our past discussion. When editing a model with modifiers, OMC should not only return the actually modified values, but also the default values those parameters would have, in case one deletes the modified value and wants to see the underlying default. I'm not sure if this feature is already included in @adrpo's proposal.

This is not part of my proposal yet. But it should be easy to have.

```modelica
model Test
  model M
     parameter Real a=10;
   end M;
   
   M m(a=20);
end Test;
```

Then one could have a JSON looking like:
```json
{
     "name": "Test"
     "elements": [
       {
          "name": "M",
          "elements": [ 
            {
              "name": "m",
               "type": "Real",
               "value": "10"
             }
           ]
       },
       {
          "name": "m"
          "type": "M",
          "modifiers": [
            {
               "name": "a",
               "original": "10", // we could also have a modifier chain if there are several levels of modifications [10, 20]
               "value": "20",
               "each": "none" // to finally support each!
            }
          ]
       }
   ]     
}
```

**Comment by adrpo** [comment]
> > There is JSON.mo file that could be used and passed to OMEdit that it could possibly transform to QVariant or work with directly. I would avoid passing large strings
> 
> Even if we transform to Qt data structures we still have to somehow pass them to OMEdit.

What Martin says is that we could write a walker that directly walks MetaModelica structures and gives you a Qt tree in OMEdit. That might be problematic with the instance tree as it has cycles.

**Comment by sjoelund** [comment]
If you have a JSON.mo structure with cycles and try to convert to string, you'll have the same problem.

**Comment by adrpo** [comment]
Maybe we should also make an exercise and see how each existing interactive API would be supported with the new one.

**Comment by perost** [comment]
I've now opened #8676 with a first draft that implements `getModelInstance`, but there are a few issues that we need to solve:
- [ ] Classes instanced by `getModelInstance` are currently not cached, not clear if they need to be. We'll need an instance to evaluate expressions passed from OMEdit, and having to instantiate the class all over again for every expression would not be performant. On the other hand we can't just cache every instance or we'll run out of memory quickly, but just caching the last one is maybe not good either since OMEdit can have multiple classes open.
- [ ] Passing modifiers back in the form of JSON is a bit problematic since there's no connection between the Absyn and the NF (the NF uses SCode), so we somehow need to use the NF information to figure out where to put the modifiers in the Absyn (directly on local elements or on the extends clauses for inherited elements). 
- [ ] Dimensions are evaluated during the typing, so we don't have the original instantiated dimensions easily available.
- [ ] Unclear how to handle dimensions since they can come from both a component's declaration as well as the component's type. Both are needed to determine if something is an array, but only the declaration dimensions can be changed when editing a component.
- [ ] Some expressions are evaluated during typing, notably `fill` (and by extension `ones` and `zeros`). It would be preferable to not evaluate `fill` so early but it's needed right now to avoid type issues, but maybe it's enough to just evaluate the size of the `fill`-call?
- [ ] Evaluating component references overwrites the binding of the component (so we don't have to evaluate it multiple times), so for e.g. component references used to determine dimension we don't have easy access to the instantiated original binding.
- [ ] Component annotations are not instantiated. adrpo added a field to components for holding the instantiated annotation as part of the work on the nfAPI, but it's not actually used at the moment.
- [ ] For constants and structural parameters we return both the evaluated and non-evaluated binding expressions, unclear if we also should do so with non-structural parameters (those that can be evaluated that is).
- [ ] The component prefixes returned include prefixes inherited by the component from its parent, do we want that or only the prefixes from the component declaration itself?
- [ ] Prefixes are currently dumped as an array with the same format as `getComponentInfo` uses since it's reasonably compact, but maybe using a JSON object would be better and only add the prefixes which are different than the default prefixes.
- [ ] Extends nodes are removed already during the second phase of the instantiation. Do we need any information about inherited elements?
- [ ] Need to somehow handle components that couldn't be instantiated/typed. Might be hard to deal with the consequences, like dealing with invalid components during constant evaluation.
- [ ] Equations/algorithms are still instantiated/typed at the moment. Not sure if we actually want to avoid that completely, we have some API functions for equations/algorithm/connections but maybe none that needs them to be instantiated?
- [ ] Replaceable classes was mentioned, do we just need a list of the names of the replaceable classes declared in an instance or something more involved?
- [ ] Do we want some information about imports?

And probably a few more I've forgotten.

**Comment by perost** [comment]
#8683 fixes the issue with EngineV6 that adrpo mentioned in [#8676](https://github.com/OpenModelica/OpenModelica/pull/8676#issuecomment-1064650557). BatchPlant_StandardWater still doesn't work though, for some reason we get some untyped type attributes in it.

**Comment by perost** [comment]
The issue with BatchPlant_StandardWater is that we don't type deleted components since that they'll just be removed anyway, so we get issues when we try to dump them. We might not actually need to type those since we should never need to evaluate a conditional component, but I'll have to look into that.

**Comment by adrpo** [comment]
But i guess OMEdit doesn't need to see them, so e might as well not dump any of them in the JSON.

**Comment by perost** [comment]
> But i guess OMEdit doesn't need to see them, so we might as well not dump any of them in the JSON.

I thought being able to handle conditional connectors was a big part of what we're trying to fix?

**Comment by adrpo** [comment]
Of course but at the level of the Dialog you would modify the condition, send the modification to OMC and get back an activated connector component and annotation in the JSON tree.
I don't think we need a solution where we give back all the different non activated trees in JSON so that OMEdit can activate it without asking OMC for help.

Currently OMEdit does something totally wrong basically gets the classes and components but cannot properly apply the modifications.

**Comment by perost** [comment]
Some meeting notes:

* Dump the components as an inheritance tree instead of as a flat array so OMEdit knows which components are inherited from where. Maybe add `DAE.ElementSource` to components to keep track of the origin of duplicated components?
* For components we need the original dimensions from the declaration as well as the evaluated dimensions. The evaluated dimensions may include dimensions from a component's type, in which case the two lists will be of different size.
* Don't evaluate non-structural parameters, if necessary (and possible) OMEdit can evaluate them itself.
* Use the prefixes on the component declarations and not from the instantiated components, since the prefixes on the instantiated components may have been overwritten by their types and/or parents (though thinking about it I guess parents don't matter if we only allow editing prefixes on the top-level components, but the type may still have prefixes).
* Prefixes should be dumped as a JSON object and not an array like now, but only prefixes deviating from the defaults needs to be dumped.
* Connect equations and their annotations should be dumped.
* Bindings are currently dumped as an array of one or two elements, where the optional second element is the evaluated value of the binding. Maybe it would be better to just dump them as two separate entries instead (like "binding" and "value").
* We need the names and types of all replaceable elements in each instance (or just in the top-level instances I guess?).

**Comment by casella** [comment]
Adding @dzimmer to the loop

**Comment by casella** [comment]
Flag for testing: `OMEdit.exe --NAPI=true`. The implementation is still a bit buggy, but we can start testing it.

**Comment by niklwors** [comment]
I tested out valves library with OMEdit and the flag ```--NAPI=true```. When I try to expand the package  ```Rexroth_Valves.ProportionalValves``` in the package browser OMEdit crashes.

**Comment by adeas31** [comment]
@perost `getModelInstance(Rexroth_Valves.ProportionalValves.Rexroth_2WRCE_4X)` causes the crash.

**Comment by perost** [comment]
@niklwors: The issue with `Rexroth_Valves` should be fixed in #9501.

**Comment by niklwors** [comment]
I was able to start OMEdit with today's version. However, it is not possible to expand a folder in the library browser because it has been trying for half an hour to exapnd the first subfolder of the ```Rexroth_Valves.ProportionalValves``` package. So it is unfortunately not possible to test and use the OMedit with the new API.

**Comment by casella** [comment]
@niklwors we need to check what is going wrong there. In the meantime, maybe you can double-check with other libraries?

**Comment by niklwors** [comment]
@casella The problem occurs with all libraries.

**Comment by perost** [comment]
> @casella The problem occurs with all libraries.

That's really odd, and also that it was hanging at startup previously. We haven't actually changed anything that should affect that for the last couple of days, and I can't reproduce the issue myself.

**Comment by niklwors** [comment]
For example I opened in the library browser the folder ```Rexroth_Pumps_Test.AxialPistonUnits.Components``` and it hangs. When I killed the omedit.exe process after 30 minutes  the last command in ```omeditcommands.mos```  is ```getNamedAnnotation(Rexroth_Generic_Test.Auxiliaries.UnitConversion.TorqueConversionFromSI_TC01`, versionBuild); getErrorString(); ```
It is the 36408 call. 
My colleague tested it on his computer an he has the same issue.

**Comment by adrpo** [comment]
I will try to do something about it this week but I'm currently swamped.

**Comment by perost** [comment]
> I think it is spinning when `getModelInstance(Rexroth_Pumps_Test.AxialPistonUnits.Components.A4VSO40_10_TC01)` is called.

Fixed in #9586 (which also fixes #9533).

**Comment by niklwors** [comment]
> > I think it is spinning when `getModelInstance(Rexroth_Pumps_Test.AxialPistonUnits.Components.A4VSO40_10_TC01)` is called.
> 
> Fixed in #9586 (which also fixes #9533).

I have tested it with the current OMEdit version but the problem is still there.

**Comment by perost** [comment]
> > > I think it is spinning when `getModelInstance(Rexroth_Pumps_Test.AxialPistonUnits.Components.A4VSO40_10_TC01)` is called.
> > 
> > 
> > Fixed in #9586 (which also fixes #9533).
> 
> I have tested it with the current OMEdit version but the problem is still there.

The issue fixed from what I can see, but now the issue is that it's instead extremely slow and eventually segfaults for me after a couple of minutes. It doesn't look like it actually runs out of memory, but I get a warning from the GC about repeated large allocations that might cause memory leaks or other issues. So I guess the segfault is due to the GC not being able to keep up.

I'm not entirely sure how OMEdit works, but I'm assuming that we call `getModelInstance` one every class in the package in order to get the icon annotation. That's just not going to work, it will be far too slow and memory expensive to be usable for real libraries, so we'll need to come up with some other solution for that.

**Comment by adeas31** [comment]
> I'm not entirely sure how OMEdit works, but I'm assuming that we call getModelInstance one every class in the package in order to get the icon annotation. That's just not going to work, it will be far too slow and memory expensive to be usable for real libraries, so we'll need to come up with some other solution for that.

Yes, of course the `getModelInstance` used for drawing icons. It is just not possible to use 2 different implementations for drawing of icons and diagrams. Maybe we can have a minimalist version of `getModelInstance` for icons and when user actuallys wants to see the diagram then the full `getModelInstance` is used.

**Comment by casella** [comment]
This feature was finalized in version 1.22.0 long time ago.
